import { afterEach, beforeAll, beforeEach, describe, expect, it, vi, type MockInstance } from 'vitest'
import { createApp, h, nextTick, reactive, type App } from 'vue'
import { createRequire } from 'node:module'
import IntegrationReadSourceConfigPanel from '../src/components/integration/IntegrationReadSourceConfigPanel.vue'
import IntegrationK3Bl2RunPanel from '../src/components/integration/IntegrationK3Bl2RunPanel.vue'
import { notifyAuthPrincipalChange } from '../src/composables/authPrincipal'
import { normalizeReadSourceConfigRow, type ReadSourceConfigRow } from '../src/services/integration/readSourceConfigs'
import type { IntegrationScope, WorkbenchExternalSystem } from '../src/services/integration/workbench'

// Actual Panel -> actual services -> apiFetch -> synthetic fetch only. Positive evidence is
// generated by the real validator, runtime, resolver and K3 adapter, never a success-shaped mock.
const require = createRequire(import.meta.url)
const { validateReadSourceConfig } = require('../../../plugins/plugin-integration-core/lib/read-source-config.cjs')
const { prepareConfiguredRead, executeConfiguredRead } = require('../../../plugins/plugin-integration-core/lib/read-source-read-runtime.cjs')
const { prepareReadSourceProbe, executeReadSourceProbe } = require('../../../plugins/plugin-integration-core/lib/read-source-probe-runtime.cjs')
const { createK3WiseWebApiAdapter } = require('../../../plugins/plugin-integration-core/lib/adapters/k3-wise-webapi-adapter.cjs')
type Wire = Record<string, unknown>
const SYSTEM = 'synthetic-bl2-k3'
const PRIVATE = 'SYNTHETIC_PRIVATE_NEVER_RENDER'
const BOM = '  SYNTHETIC-BOM-01  '
const clone = <T,>(value: T): T => JSON.parse(JSON.stringify(value)) as T
function config(version = 7, readPath = '/K3API/BOM/GetList'): Wire {
  const checked = validateReadSourceConfig({ version, systemId: SYSTEM, requiredKind: 'erp:k3-wise-webapi', object: 'material-bom-list', mode: 'resolver_lookup', readPath, readMethod: 'POST', operations: ['read'], keyField: 'FPercentItemID', keyEncoding: 'numeric_id', containerPaths: ['Data.DATA'], resolverRule: 'exactly_one', fieldMap: [{ source: 'FBOMNumber', target: 'bom_number' }] })
  expect(checked.valid).toBe(true)
  return clone(checked.normalized)
}
function savedRow(): Wire {
  return { id: 'saved-bl2', systemId: SYSTEM, version: 7, contentKey: 'synthetic-content-7', status: 'approved', object: 'material-bom-list', mode: 'resolver_lookup', config: config() }
}
function runtime(rows: Wire[]) {
  return {
    system: { id: SYSTEM, kind: 'erp:k3-wise-webapi', role: 'source', credentials: { sessionId: 'synthetic-session' }, config: { baseUrl: 'https://synthetic-k3.invalid' } },
    createAdapter: (system: Wire) => createK3WiseWebApiAdapter({ system, fetchImpl: async (_url: string, init: RequestInit) => {
      expect(init.method).toBe('POST')
      const requestData = (JSON.parse(String(init.body)) as { Data: { PageSize: number; PageIndex: number } }).Data
      expect(requestData).toBeDefined()
      return { ok: true, status: 200, text: async () => JSON.stringify({ StatusCode: 200, Message: PRIVATE, Data: {
        ROWCOUNT: rows.length, PAGESIZE: requestData.PageSize, PAGEINDEX: requestData.PageIndex,
        DATA: rows.slice(0, requestData.PageSize),
      } }) }
    } }),
  }
}
async function readFixture(rows: Wire[]): Promise<Wire> {
  return clone(await executeConfiguredRead(prepareConfiguredRead({ config: config(), inputs: { key: '00000000000000031415' } }), runtime(rows)))
}
async function probeFixture(rows: Wire[]): Promise<Wire> {
  return clone(await executeReadSourceProbe(prepareReadSourceProbe({ config: config(), inputs: { key: '31415' }, boundedSmoke: false }), runtime(rows)))
}
function response(data: unknown, status = 200): Response {
  return new Response(JSON.stringify({ ok: true, data }), { status, headers: { 'Content-Type': 'application/json' } })
}
function deferred<T>() {
  let resolve!: (value: T) => void
  let reject!: (error: unknown) => void
  const promise = new Promise<T>((yes, no) => { resolve = yes; reject = no })
  return { promise, resolve, reject }
}
async function flush(): Promise<void> {
  for (let index = 0; index < 20; index += 1) { await Promise.resolve(); await nextTick() }
}
function setPath(value: Wire, path: string, replacement: unknown): void {
  const parts = path.split('.')
  let item = value
  for (const key of parts.slice(0, -1)) item = item[key] as Wire
  item[parts.at(-1)!] = replacement
}

describe('BL2 actual UI / service / API chain', () => {
  let app: App | undefined
  let root: HTMLDivElement
  let listed: Wire[]
  let positive: Wire
  let empty: Wire
  let multiple: Wire
  let capped: Wire
  let emptyProbe: Wire
  let multiProbe: Wire
  let nextRead: () => Promise<Response>
  let nextProbe: () => Promise<Response>
  let nextSave: (body: Wire) => Promise<Response>
  let nextApprove: () => Promise<Response>
  let nextAudit: () => Promise<Response>
  let confirm: MockInstance<[message?: string], boolean>
  let state: { scope: IntegrationScope; systems: WorkbenchExternalSystem[]; admin: boolean; available: boolean; generation: number }
  let directRow: ReadSourceConfigRow
  const calls: Array<{ url: URL; init: RequestInit }> = []
  const posts = (suffix = '/read') => calls.filter(({ url, init }) => init.method === 'POST' && url.pathname.endsWith(suffix))
  const q = <T extends HTMLElement = HTMLElement>(id: string): T => {
    const element = root.querySelector(`[data-testid="${id}"]`)
    if (!element) throw new Error(`missing test element ${id}`)
    return element as T
  }
  const absent = (id: string) => expect(root.querySelector(`[data-testid="${id}"]`)).toBeNull()
  const click = async (id: string) => { q<HTMLButtonElement>(id).click(); await flush() }
  const input = async (id: string, value: string) => {
    const element = q<HTMLInputElement>(id)
    element.value = value
    element.dispatchEvent(new Event(element.tagName === 'SELECT' ? 'change' : 'input', { bubbles: true }))
    await flush()
  }
  function mount(direct = false): void {
    app = createApp({ render: () => direct
      ? h(IntegrationK3Bl2RunPanel, { row: directRow, scope: state.scope, system: state.systems[0], hasIntegrationAdmin: state.admin, available: state.available, generation: state.generation })
      : h(IntegrationReadSourceConfigPanel, { scope: state.scope, systems: state.systems, hasIntegrationAdmin: state.admin, initialViewMode: 'expert' }) })
    app.config.warnHandler = () => {}
    app.mount(root)
  }
  async function enterTemplate(kind: 'bl2' | 'b4' | 'generic' = 'bl2'): Promise<void> {
    if (kind !== 'generic') {
      await click(`rsc-${kind}-enter`)
      await input(`rsc-${kind}-system`, SYSTEM)
      if (kind === 'bl2') await input('rsc-bl2-probe-key', '31415')
    } else {
      await input('rsc-system', SYSTEM)
      await input('rsc-object', 'material')
      await input('rsc-read-path', '/K3API/Material/GetDetail')
      await input('rsc-key-field', 'FNumber')
      await input('rsc-container-paths', 'Data')
      await input('rsc-probe-key', PRIVATE)
    }
  }
  beforeAll(async () => {
    ;[positive, empty, multiple, capped, emptyProbe, multiProbe] = await Promise.all([
      readFixture([{ FBOMNumber: BOM, extra: PRIVATE }]), readFixture([]),
      readFixture([{ FBOMNumber: 'SYN-A' }, { FBOMNumber: 'SYN-B' }]),
      readFixture(Array.from({ length: 12 }, () => ({ FBOMNumber: PRIVATE }))),
      probeFixture([]), probeFixture([{ FBOMNumber: PRIVATE }, { FBOMNumber: PRIVATE }]),
    ])
  })
  beforeEach(() => {
    localStorage.clear()
    localStorage.setItem('auth_token', `synthetic.${btoa(JSON.stringify({ sub: 'synthetic-user', tenantId: 'synthetic-tenant' }))}.signature`)
    localStorage.setItem('tenantId', 'FORGED-HEADER-HINT')
    listed = [savedRow()]
    directRow = reactive(normalizeReadSourceConfigRow(savedRow())!)
    state = reactive({ scope: { tenantId: 'synthetic-tenant', workspaceId: 'synthetic-workspace' }, systems: [{ id: SYSTEM, name: 'Synthetic K3', tenantId: 'synthetic-tenant', workspaceId: 'synthetic-workspace', kind: 'erp:k3-wise-webapi', role: 'source' as const, status: 'active' as const }], admin: true, available: true, generation: 0 })
    calls.length = 0
    nextRead = async () => response(positive)
    nextProbe = async () => response(emptyProbe)
    nextSave = async (body) => response({ ...savedRow(), config: body.config, status: 'draft', reused: false })
    nextApprove = async () => { listed[0].status = 'approved'; return response(listed[0]) }
    nextAudit = async () => response([{ action: 'save_version', actor: 'synthetic-actor', createdAt: 'synthetic-date' }])
    vi.stubGlobal('fetch', vi.fn(async (url: string, init: RequestInit = {}) => {
      const parsed = new URL(url)
      calls.push({ url: parsed, init })
      if (parsed.pathname.endsWith('/read')) return nextRead()
      if (parsed.pathname.endsWith('/read-source-probe')) return nextProbe()
      if (parsed.pathname.endsWith('/approve')) return nextApprove()
      if (parsed.pathname.endsWith('/audit')) return nextAudit()
      if (parsed.pathname.endsWith('/retire')) { listed[0].status = 'retired'; return response(listed[0]) }
      if (init.method === 'POST') return nextSave(JSON.parse(String(init.body)) as Wire)
      return response(listed)
    }))
    confirm = vi.spyOn(window, 'confirm').mockReturnValue(true)
    root = document.createElement('div'); document.body.appendChild(root)
  })
  afterEach(() => {
    app?.unmount(); app = undefined
    root.remove(); vi.restoreAllMocks(); vi.unstubAllGlobals(); localStorage.clear()
  })

  it.each(['/K3API/BOM/GetList', '/BOM/GetList', 'custom/deployment/BOM/GetList'])('saves exact independent template with safe path %s and no business key, then approves separately', async (path) => {
    mount(); await flush(); await enterTemplate()
    expect(q<HTMLInputElement>('rsc-bl2-read-path').value).toBe('/K3API/BOM/GetList')
    expect(q<HTMLInputElement>('rsc-bl2-bounded-smoke').checked).toBe(false)
    expect(calls.filter(({ init }) => init.method === 'POST')).toHaveLength(0)
    await input('rsc-bl2-read-path', path); await input('rsc-bl2-probe-key', '')
    expect(q<HTMLButtonElement>('rsc-bl2-save').disabled).toBe(false)
    expect(q<HTMLButtonElement>('rsc-bl2-probe').disabled).toBe(true)
    await click('rsc-bl2-save')
    const saved = posts('/read-source-configs')[0]
    expect(JSON.parse(String(saved.init.body))).toEqual({ config: config(1, `/${path.replace(/^\//, '')}`) })
    expect(String(saved.init.body)).not.toContain('31415')
    expect(posts('/read-source-probe')).toHaveLength(0)
    expect(posts('/approve')).toHaveLength(0)
    expect(q('rsc-bl2-save-result').textContent).toContain('draft')
    await click('rsc-bl2-approve')
    expect(posts('/approve')).toHaveLength(1)
    expect(q('rsc-bl2-save-result').textContent).toContain('approved')
  })

  it.each(['/BOM/GetDetail', 'https://synthetic.invalid/BOM/GetList', '/prefix/../BOM/GetList', '/BOM/GetList?x=1'])('refuses drifted path %s without saving or probing', async (path) => {
    mount(); await flush(); await enterTemplate(); await input('rsc-bl2-read-path', path)
    expect(q<HTMLButtonElement>('rsc-bl2-save').disabled).toBe(true)
    await click('rsc-bl2-save'); await click('rsc-bl2-probe')
    expect(calls.filter(({ init }) => init.method === 'POST')).toHaveLength(0)
  })

  it.each(['empty', 'multiple'] as const)('labels actual %s probe as container evidence, never uniqueness success', async (kind) => {
    nextProbe = async () => response(kind === 'empty' ? emptyProbe : multiProbe)
    mount(); await flush(); await enterTemplate(); await click('rsc-bl2-probe')
    expect(confirm).toHaveBeenCalledOnce()
    expect(q('rsc-bl2-evidence').textContent).toContain('ok=true')
    expect(q('rsc-bl2-evidence').textContent).toContain('非唯一 BOM 结果')
    absent('k3-bl2-result')
    expect(root.textContent).not.toContain(PRIVATE)
    expect(JSON.parse(String(posts('/read-source-probe')[0].init.body))).toEqual({ config: config(1), boundedSmoke: false, inputs: { key: '31415' } })
  })

  it('clears key and results when switching templates or exiting, without changing TC1 seed behavior', async () => {
    mount(); await flush(); await enterTemplate(); await click('rsc-bl2-probe'); await click('rsc-bl2-save')
    await click('rsc-b4-enter'); absent('rsc-bl2-panel'); absent('rsc-b4-evidence'); absent('rsc-b4-save-result')
    await click('rsc-bl2-enter'); expect(q<HTMLInputElement>('rsc-bl2-probe-key').value).toBe('')
    absent('rsc-bl2-evidence'); absent('rsc-bl2-save-result')
    await input('rsc-bl2-probe-key', '123'); await click('rsc-bl2-exit')
    await input('rsc-key-field', 'FNumber')
    expect(q<HTMLInputElement>('rsc-probe-key').value).toBe('')
    expect(q<HTMLInputElement>('rsc-object').value).toBe('')
    expect(q('rsc-mode-toggle')).toBeTruthy()
  })

  it('reads saved approved version only, preserving 20 digits and rendering only selected value', async () => {
    mount(); await flush()
    await input('rsc-object', PRIVATE)
    await input('k3-bl2-key', '  00000000000000031415  ')
    expect(q<HTMLInputElement>('k3-bl2-key').type).toBe('text')
    expect(q<HTMLInputElement>('k3-bl2-key').inputMode).toBe('numeric')
    expect(posts()).toHaveLength(0)
    await click('k3-bl2-read')
    expect(posts()).toHaveLength(1)
    const wire = posts()[0]
    expect(wire.url.pathname).toBe('/api/integration/read-source-configs/saved-bl2/read')
    expect([...wire.url.searchParams.entries()]).toEqual([['workspaceId', 'synthetic-workspace']])
    expect(JSON.parse(String(wire.init.body))).toEqual({ inputs: { key: '00000000000000031415' } })
    expect(new Headers(wire.init.headers).has('x-tenant-id')).toBe(false)
    expect(new Headers(wire.init.headers).has('authorization')).toBe(true)
    expect(new Headers(calls[0].init.headers).get('x-tenant-id')).toBe('FORGED-HEADER-HINT')
    expect(q('k3-bl2-value').textContent).toBe(BOM)
    expect(q('k3-bl2-result').textContent).not.toContain(PRIVATE)
    expect((positive.evidence as Wire).boundedSmoke).toBe(false)
    expect((positive.evidence as Wire).boundedSmokeExecuted).toBeUndefined()
  })

  it.each(['', ' ', 'A123', '1.0', '1e3', '-1', '１２３', '123456789012345678901'])('invalid key %j sends neither probe nor read', async (key) => {
    mount(); await flush(); await enterTemplate(); await input('rsc-bl2-probe-key', key); await input('k3-bl2-key', key)
    await click('rsc-bl2-probe'); await click('k3-bl2-read')
    expect(calls.filter(({ init }) => init.method === 'POST')).toHaveLength(0)
    expect(confirm).not.toHaveBeenCalled()
  })

  it.each(['draft', 'retired', 'fake-flag', 'wrong-target', 'inactive', 'wrong-kind'] as const)('refuses %s saved row', async (kind) => {
    if (kind === 'draft' || kind === 'retired') listed[0].status = kind
    if (kind === 'fake-flag') { listed[0].k3Bl2Eligible = true; delete listed[0].config }
    if (kind === 'wrong-target') (listed[0].config as Wire).fieldMap = [{ source: 'FBOMNumber', target: 'other' }]
    if (kind === 'inactive') state.systems[0].status = 'inactive'
    if (kind === 'wrong-kind') state.systems[0].kind = 'http'
    mount(); await flush()
    const button = root.querySelector<HTMLButtonElement>('[data-testid="k3-bl2-read"]')
    if (button) await input('k3-bl2-key', '31415')
    expect(button === null || button.disabled).toBe(true)
    button?.click(); await flush(); expect(posts()).toHaveLength(0)
  })

  it.each(['empty', 'multiple', 'capped'] as const)('rejects actual backend %s resolution with a coarse code', async (kind) => {
    nextRead = async () => response(kind === 'empty' ? empty : kind === 'multiple' ? multiple : capped)
    mount(); await flush(); await input('k3-bl2-key', '31415'); await click('k3-bl2-read')
    expect(q('k3-bl2-error').textContent).toContain(kind === 'empty' ? 'NOT_FOUND' : 'AMBIGUOUS')
    absent('k3-bl2-result'); expect(root.textContent).not.toContain(PRIVATE); expect(posts()).toHaveLength(1)
  })

  it.each([
    ['evidence.ok', 'true'], ['evidence.resolved', false], ['evidence.candidateCount', 2],
    ['evidence.containers.primary.arrayLength', 0], ['evidence.ambiguous', true], ['evidence.capReached', true],
    ['data.resolver.target', 'other'], ['data.resolver.value', null], ['data.resolver.value', {}],
    ['data.resolver.value', 9007199254740992], ['data.resolver.value', ' '], ['data.resolver.value', true],
  ] as Array<[string, unknown]>)('rejects mutated runtime receipt %s = %j', async (path, value) => {
    const bad = clone(positive); setPath(bad, path, value); bad.extra = PRIVATE
    nextRead = async () => response(bad)
    mount(); await flush(); await input('k3-bl2-key', '31415'); await click('k3-bl2-read')
    absent('k3-bl2-result'); expect(q('k3-bl2-error').textContent).toContain('K3_BL2_READ_FAILED'); expect(root.textContent).not.toContain(PRIVATE)
  })

  it.each([401, 403, 404, 500])('HTTP %s cannot disclose a supplied result or retry', async (status) => {
    nextRead = async () => response(positive, status)
    mount(); await flush(); await input('k3-bl2-key', '31415'); await click('k3-bl2-read')
    absent('k3-bl2-result'); expect(posts()).toHaveLength(1); expect(q('k3-bl2-error').textContent).toContain('K3_BL2_READ_FAILED')
    expect(localStorage.getItem('auth_token')).not.toBeNull()
  })

  it('handles cancellation and synchronous confirmation re-entry with zero or one read', async () => {
    mount(); await flush(); await input('k3-bl2-key', '31415')
    confirm.mockReturnValue(false); await click('k3-bl2-read'); expect(posts()).toHaveLength(0)
    confirm.mockImplementation(() => { q<HTMLButtonElement>('k3-bl2-read').click(); return true })
    await click('k3-bl2-read'); expect(posts()).toHaveLength(1)
  })

  it.each(['key', 'session', 'scope', 'system'] as const)('rechecks %s after confirmation before any POST', async (kind) => {
    mount(); await flush(); await input('k3-bl2-key', '31415')
    confirm.mockImplementation(() => {
      if (kind === 'key') { const field = q<HTMLInputElement>('k3-bl2-key'); field.value = '2'; field.dispatchEvent(new Event('input', { bubbles: true })) }
      if (kind === 'session') localStorage.setItem('auth_token', 'next-synthetic-token')
      if (kind === 'scope') state.scope.workspaceId = 'next-workspace'
      if (kind === 'system') state.systems[0].status = 'inactive'
      return true
    })
    await click('k3-bl2-read'); expect(posts()).toHaveLength(0); absent('k3-bl2-result')
  })

  it.each(['resolve', 'reject'] as const)('holds actual outstanding slot after key edits until %s, dropping stale output', async (outcome) => {
    const pending = deferred<Response>(); nextRead = () => pending.promise
    mount(); await flush(); await input('k3-bl2-key', '1'); await click('k3-bl2-read')
    await input('k3-bl2-key', '2'); await click('k3-bl2-read')
    expect(q<HTMLInputElement>('k3-bl2-key').value).toBe('2')
    expect(q<HTMLButtonElement>('k3-bl2-read').disabled).toBe(true); expect(posts()).toHaveLength(1)
    if (outcome === 'resolve') pending.resolve(response(positive)); else pending.reject(new Error(PRIVATE))
    await flush(); absent('k3-bl2-result'); absent('k3-bl2-error')
    expect(q<HTMLButtonElement>('k3-bl2-read').disabled).toBe(false)
    nextRead = async () => response(positive); await click('k3-bl2-read'); expect(posts()).toHaveLength(2)
    await input('k3-bl2-key', '3'); absent('k3-bl2-result')
  })

  it.each(['id', 'version', 'contentKey', 'status', 'eligible', 'systemId', 'kind', 'systemStatus', 'tenant', 'workspace', 'admin', 'available', 'generation', 'principal', 'permissions', 'silent-token', 'unmount'] as const)('invalidates pending child on %s, without releasing busy early', async (change) => {
    const pending = deferred<Response>(); nextRead = () => pending.promise
    mount(true); await flush(); await input('k3-bl2-key', '1'); await click('k3-bl2-read')
    if (change === 'id') directRow.id = 'other'
    if (change === 'version') directRow.version += 1
    if (change === 'contentKey') directRow.contentKey = 'other'
    if (change === 'status') directRow.status = 'retired'
    if (change === 'eligible') directRow.k3Bl2Eligible = false
    if (change === 'systemId') state.systems[0].id = 'other'
    if (change === 'kind') state.systems[0].kind = 'http'
    if (change === 'systemStatus') state.systems[0].status = 'inactive'
    if (change === 'tenant') state.scope.tenantId = 'other'
    if (change === 'workspace') state.scope.workspaceId = 'other'
    if (change === 'admin') state.admin = false
    if (change === 'available') state.available = false
    if (change === 'generation') state.generation += 1
    if (change === 'principal') notifyAuthPrincipalChange()
    if (change === 'permissions') { localStorage.setItem('user_permissions', '[]'); window.dispatchEvent(new Event('storage')) }
    if (change === 'silent-token') localStorage.setItem('auth_token', 'new-synthetic-token')
    if (change === 'unmount') { app!.unmount(); app = undefined }
    await flush()
    if (change !== 'unmount') expect(q<HTMLButtonElement>('k3-bl2-read').disabled).toBe(true)
    pending.resolve(response(positive)); await flush()
    absent('k3-bl2-result'); absent('k3-bl2-error'); expect(posts()).toHaveLength(1)
    if (change !== 'unmount') expect(q<HTMLInputElement>('k3-bl2-key').value).toBe('')
  })

  it.each(['refresh', 'retire'] as const)('real parent %s discards pending read', async (action) => {
    const pending = deferred<Response>(); nextRead = () => pending.promise
    mount(); await flush(); await input('k3-bl2-key', '1'); await click('k3-bl2-read')
    await click(action === 'refresh' ? 'rsc-refresh' : 'rsc-retire-saved-bl2')
    pending.resolve(response(positive)); await flush(); absent('k3-bl2-result'); expect(posts()).toHaveLength(1)
  })

  it.each(['bl2', 'b4', 'generic'] as const)('clears %s private draft and drops late probe/save/approval after auth change', async (kind) => {
    for (const operation of ['probe', 'save', 'approve'] as const) {
      if (app) { app.unmount(); app = undefined }
      mount(); await flush(); await enterTemplate(kind)
      const pending = deferred<Response>()
      const prefix = kind === 'generic' ? 'rsc' : `rsc-${kind}`
      if (operation === 'probe') { nextProbe = () => pending.promise; await click(`${prefix}-probe`) }
      if (operation === 'save') { nextSave = () => pending.promise; await click(`${prefix}-save`) }
      if (operation === 'approve') {
        nextSave = async () => response({ ...savedRow(), status: 'draft' })
        await click(`${prefix}-save`)
        nextApprove = () => pending.promise
        // Generic expert mode approves its list row, while both named templates approve save result.
        if (kind === 'generic') { listed[0].status = 'draft'; await click('rsc-refresh'); await click('rsc-approve-saved-bl2') }
        else await click(`${prefix}-approve`)
      }
      const readsBefore = calls.length
      notifyAuthPrincipalChange(); localStorage.setItem('auth_token', `synthetic-next-${kind}-${operation}`); await flush()
      expect(q<HTMLInputElement>('rsc-object').value).toBe('')
      expect(q<HTMLInputElement>('rsc-system').value).toBe('')
      pending.resolve(response(operation === 'probe' ? emptyProbe : savedRow())); await flush()
      absent('rsc-probe-evidence'); absent('rsc-save-result'); absent('rsc-bl2-save-result'); absent('rsc-b4-save-result')
      absent('rsc-row-saved-bl2'); absent('rsc-error')
      expect(calls).toHaveLength(readsBefore)
      // Reveal the conditional key editor only AFTER checking late output; edits must not
      // accidentally invalidate the pending ticket and conceal a broken auth guard.
      await input('rsc-key-field', 'FNumber')
      expect(q<HTMLInputElement>('rsc-probe-key').value).toBe('')
      nextProbe = async () => response(emptyProbe)
      nextSave = async () => response({ ...savedRow(), status: 'draft' })
      nextApprove = async () => response(savedRow())
    }
  })

  it.each(['probe', 'saved-approve', 'row-approve'] as const)('session change inside %s confirmation causes zero POST', async (operation) => {
    listed[0].status = 'draft'; mount(); await flush(); await enterTemplate()
    if (operation === 'saved-approve') await click('rsc-bl2-save')
    const before = calls.filter(({ init }) => init.method === 'POST').length
    confirm.mockImplementation(() => { localStorage.setItem('auth_token', 'synthetic-next-session'); return true })
    await click(operation === 'probe' ? 'rsc-bl2-probe' : operation === 'saved-approve' ? 'rsc-bl2-approve' : 'rsc-approve-saved-bl2')
    expect(calls.filter(({ init }) => init.method === 'POST')).toHaveLength(before)
    expect(q<HTMLInputElement>('rsc-object').value).toBe('')
  })

  it.each(['probe', 'save', 'approve', 'audit'] as const)('silently replaced token discards late %s failure and clears draft without an auth event', async (operation) => {
    listed[0].status = 'draft'
    mount(); await flush(); await enterTemplate()
    const pending = deferred<Response>()
    if (operation === 'probe') { nextProbe = () => pending.promise; await click('rsc-bl2-probe') }
    if (operation === 'save') { nextSave = () => pending.promise; await click('rsc-bl2-save') }
    if (operation === 'approve') { nextApprove = () => pending.promise; await click('rsc-approve-saved-bl2') }
    if (operation === 'audit') { nextAudit = () => pending.promise; await click('rsc-audit-toggle-saved-bl2') }
    localStorage.setItem('auth_token', 'synthetic-silent-replacement')
    pending.reject(new Error(PRIVATE)); await flush()
    absent('rsc-bl2-error'); absent('rsc-error'); absent('rsc-audit-list'); absent('rsc-bl2-save-result'); absent('rsc-bl2-evidence')
    expect(q<HTMLInputElement>('rsc-object').value).toBe('')
    expect(q<HTMLInputElement>('rsc-system').value).toBe('')
  })

  it.each(['draft', 'scope'] as const)('rechecks %s identity after saved approval confirmation', async (kind) => {
    mount(); await flush(); await enterTemplate(); await click('rsc-bl2-save')
    confirm.mockImplementation(() => {
      if (kind === 'scope') state.scope.workspaceId = 'other-workspace'
      else { const field = q<HTMLInputElement>('rsc-bl2-read-path'); field.value = '/next/BOM/GetList'; field.dispatchEvent(new Event('input', { bubbles: true })) }
      return true
    })
    await click('rsc-bl2-approve'); expect(posts('/approve')).toHaveLength(0)
  })

  it('omits absent workspace and accepts numeric zero only as a returned BOM value', async () => {
    state.scope.workspaceId = null
    nextRead = async () => response(await readFixture([{ FBOMNumber: 0 }]))
    mount(); await flush(); await input('k3-bl2-key', '0'); await click('k3-bl2-read')
    expect(posts()[0].url.search).toBe('')
    expect(q('k3-bl2-value').textContent).toBe('0')
  })

  it('unknown network and backend codes never show raw messages, values or failure data', async () => {
    mount(); await flush(); await input('k3-bl2-key', '31415')
    nextRead = async () => { throw new Error(PRIVATE) }
    await click('k3-bl2-read')
    expect(q('k3-bl2-error').textContent).toContain('K3_BL2_READ_FAILED')
    nextRead = async () => response({ ...positive, evidence: { ...positive.evidence as Wire, ok: false, errorCode: PRIVATE }, errorMessage: PRIVATE })
    await click('k3-bl2-read'); absent('k3-bl2-result')
    expect(q('k3-bl2-error').textContent).toContain('K3_BL2_READ_FAILED')
    expect(root.textContent).not.toContain(PRIVATE); expect(posts()).toHaveLength(2)
  })

  it('clears audit and all rendered private state on same-session permission change; late audit error stays hidden', async () => {
    mount(); await flush(); await enterTemplate(); await click('rsc-bl2-probe'); await click('rsc-bl2-save')
    await input('k3-bl2-key', '31415'); await click('k3-bl2-read')
    const pending = deferred<Response>(); nextAudit = () => pending.promise
    await click('rsc-audit-toggle-saved-bl2')
    localStorage.setItem('user_roles', '["next-role"]'); window.dispatchEvent(new Event('focus')); await flush()
    pending.reject(new Error(PRIVATE)); await flush()
    absent('rsc-audit-list'); absent('rsc-bl2-evidence'); absent('rsc-bl2-save-result'); absent('k3-bl2-result'); absent('rsc-error')
    expect(q<HTMLInputElement>('rsc-object').value).toBe('')
  })
})
