import { computed, ref } from 'vue'
import { describe, expect, it, vi } from 'vitest'
import type { PlmBomPanelModel } from '../src/views/plm/plmPanelModels'
import { usePlmBomPanel } from '../src/views/plm/usePlmBomPanel'

describe('usePlmBomPanel', () => {
  it('returns the typed bom panel contract unchanged', () => {
    const loadBom = vi.fn()
    const options = {
      copyDeepLink: vi.fn().mockResolvedValue(undefined),
      loadBom,
      expandAllBom: vi.fn(),
      collapseAllBom: vi.fn(),
      expandBomToDepth: vi.fn(),
      copyBomTablePathIdsBulk: vi.fn().mockResolvedValue(undefined),
      copyBomTreePathIdsBulk: vi.fn().mockResolvedValue(undefined),
      copyBomSelectedChildIds: vi.fn().mockResolvedValue(undefined),
      clearBomSelection: vi.fn(),
      exportBomCsv: vi.fn(),
      setBomDepthQuick: vi.fn(),
      applyBomFilterPreset: vi.fn(),
      deleteBomFilterPreset: vi.fn(),
      shareBomFilterPreset: vi.fn(),
      assignBomPresetGroup: vi.fn(),
      saveBomFilterPreset: vi.fn(),
      exportBomFilterPresets: vi.fn(),
      importBomFilterPresets: vi.fn(),
      triggerBomFilterPresetFileImport: vi.fn(),
      handleBomFilterPresetFileImport: vi.fn(),
      clearBomFilterPresets: vi.fn(),
      selectAllBomPresets: vi.fn(),
      clearBomPresetSelection: vi.fn(),
      applyBomPresetBatchGroup: vi.fn(),
      deleteBomPresetSelection: vi.fn(),
      toggleBomNode: vi.fn(),
      isBomCollapsed: vi.fn().mockReturnValue(false),
      isBomTreeSelected: vi.fn().mockReturnValue(false),
      selectBomTreeRow: vi.fn(),
      resolveBomLineId: vi.fn().mockReturnValue('LINE-1'),
      formatBomFindNum: vi.fn().mockReturnValue('10'),
      formatBomRefdes: vi.fn().mockReturnValue('R1'),
      formatBomPathIds: vi.fn().mockReturnValue('ROOT/LINE-1'),
      copyBomPathIds: vi.fn().mockResolvedValue(undefined),
      resolveBomChildId: vi.fn().mockReturnValue('CHILD-1'),
      resolveBomChildNumber: vi.fn().mockReturnValue('PN-1'),
      applyProductFromBom: vi.fn(),
      applyWhereUsedFromBom: vi.fn(),
      applySubstitutesFromBom: vi.fn(),
      copyBomChildId: vi.fn().mockResolvedValue(undefined),
      isBomItemSelected: vi.fn().mockReturnValue(false),
      selectBomTableRow: vi.fn(),
      formatBomTablePathIds: vi.fn().mockReturnValue('ROOT/LINE-1'),
      copyBomTablePathIds: vi.fn().mockResolvedValue(undefined),
      BOM_DEPTH_QUICK_OPTIONS: [1, 2, 3],
      bomView: ref<'table' | 'tree'>('table'),
      bomHasTree: computed(() => false),
      bomTablePathIdsCount: computed(() => 0),
      bomTreePathIdsCount: computed(() => 0),
      bomSelectedCount: computed(() => 0),
      bomExportCount: computed(() => 0),
      productId: ref('PROD-1'),
      bomLoading: ref(false),
      bomDepth: ref(2),
      bomEffectiveAt: ref(''),
      bomFilterFieldOptions: [{ value: 'all', label: '全部', placeholder: '编号/名称/行 ID' }],
      bomFilterField: ref('all'),
      bomFilter: ref(''),
      bomFilterPlaceholder: computed(() => '编号/名称/行 ID'),
      bomFilterPresetGroupFilter: ref('all'),
      bomFilterPresetGroups: computed(() => []),
      bomFilterPresetKey: ref(''),
      bomFilteredPresets: computed(() => []),
      bomFilterPresetName: ref(''),
      bomFilterPresetGroup: ref(''),
      canSaveBomFilterPreset: computed(() => false),
      bomFilterPresets: ref([]),
      bomFilterPresetImportText: ref(''),
      bomFilterPresetImportMode: ref<'merge' | 'replace'>('merge'),
      bomFilterPresetFileInput: ref<HTMLInputElement | null>(null),
      showBomPresetManager: ref(false),
      bomPresetSelectionCount: computed(() => 0),
      bomPresetBatchGroup: ref(''),
      bomPresetSelection: ref([]),
      bomError: ref(''),
      bomItems: ref([]),
      bomDisplayCount: computed(() => 0),
      bomTreeVisibleCount: computed(() => 0),
      bomFilteredItems: computed(() => []),
      bomTreeVisibleRows: computed(() => []),
      productLoading: ref(false),
      whereUsedLoading: ref(false),
      substitutesLoading: ref(false),
    } as PlmBomPanelModel

    const { bomPanel } = usePlmBomPanel(options)

    expect(bomPanel).toBe(options)
    expect(bomPanel.loadBom).toBe(loadBom)
    expect(bomPanel.productId.value).toBe('PROD-1')
  })
})
