export const SLICES = {
  'directory-migration-baseline': {
    description: 'Directory/IAM migration baseline repair slice',
    files: [
      'package.json',
      'packages/core-backend/package.json',
      'packages/core-backend/src/db/migrate.ts',
      'packages/core-backend/src/db/migration-audit.ts',
      'packages/core-backend/src/db/migration-health.ts',
      'packages/core-backend/src/db/types.ts',
      'packages/core-backend/src/db/migrations/zzzz20260323120000_create_user_external_identities.ts',
      'packages/core-backend/src/db/migrations/zzzz20260323133000_harden_user_external_identities.ts',
      'packages/core-backend/src/db/migrations/zzzz20260324143000_create_user_external_auth_grants.ts',
      'packages/core-backend/src/db/migrations/zzzz20260324150000_create_directory_sync_tables.ts',
      'packages/core-backend/src/db/migrations/zzzz20260325100000_add_mobile_to_users_table.ts',
      'packages/core-backend/src/db/migrations/zzzz20260327110000_create_directory_template_center_and_alerts.ts',
      'packages/core-backend/tests/unit/migration-audit.test.ts',
      'packages/core-backend/tests/unit/migration-health.test.ts',
      'scripts/ops/git-baseline-report.mjs',
      'scripts/ops/git-slice-apply.mjs',
      'scripts/ops/git-slice-bundle.mjs',
      'scripts/ops/git-slice-materialize.mjs',
      'scripts/ops/git-slice-handoff.mjs',
      'scripts/ops/git-slice-promote.mjs',
      'scripts/ops/git-slice-replay.mjs',
      'scripts/ops/git-slice-attest.mjs',
      'scripts/ops/git-slice-submit.mjs',
      'scripts/ops/git-slice-land.mjs',
      'scripts/ops/git-slice-publish.mjs',
      'scripts/ops/git-slice-deliver.mjs',
      'scripts/ops/git-slices.mjs',
      'scripts/ops/git-slice-report.mjs',
      'scripts/ops/git-slice-sync-plan.mjs',
      'scripts/ops/attest-remote-git-slice.sh',
      'scripts/ops/handoff-remote-git-slice.sh',
      'scripts/ops/materialize-remote-git-slice.sh',
      'scripts/ops/promote-remote-git-slice.sh',
      'scripts/ops/replay-remote-git-slice.sh',
      'scripts/ops/land-remote-git-slice.sh',
      'scripts/ops/publish-remote-git-slice.sh',
      'scripts/ops/deliver-remote-git-slice.sh',
      'scripts/ops/submit-remote-git-slice.sh',
      'scripts/ops/install-user-node-runtime.sh',
      'docs/development/directory-baseline-git-apply-design-20260328.md',
      'docs/development/directory-baseline-git-apply-verification-20260328.md',
      'docs/development/directory-baseline-git-bundle-design-20260328.md',
      'docs/development/directory-baseline-git-bundle-verification-20260328.md',
      'docs/development/directory-baseline-git-materialize-design-20260328.md',
      'docs/development/directory-baseline-git-materialize-verification-20260328.md',
      'docs/development/directory-baseline-git-handoff-design-20260329.md',
      'docs/development/directory-baseline-git-handoff-verification-20260329.md',
      'docs/development/directory-baseline-git-promote-design-20260328.md',
      'docs/development/directory-baseline-git-promote-verification-20260328.md',
      'docs/development/directory-baseline-git-replay-design-20260329.md',
      'docs/development/directory-baseline-git-replay-verification-20260329.md',
      'docs/development/directory-baseline-git-attest-design-20260329.md',
      'docs/development/directory-baseline-git-attest-verification-20260329.md',
      'docs/development/directory-baseline-git-submit-design-20260329.md',
      'docs/development/directory-baseline-git-submit-verification-20260329.md',
      'docs/development/remote-git-slice-materialize-design-20260328.md',
      'docs/development/remote-git-slice-materialize-verification-20260328.md',
      'docs/development/remote-git-slice-handoff-design-20260329.md',
      'docs/development/remote-git-slice-handoff-verification-20260329.md',
      'docs/development/remote-git-slice-promote-design-20260328.md',
      'docs/development/remote-git-slice-promote-verification-20260328.md',
      'docs/development/remote-git-slice-replay-design-20260329.md',
      'docs/development/remote-git-slice-replay-verification-20260329.md',
      'docs/development/remote-git-slice-attest-design-20260329.md',
      'docs/development/remote-git-slice-attest-verification-20260329.md',
      'docs/development/remote-git-slice-submit-design-20260329.md',
      'docs/development/remote-git-slice-submit-verification-20260329.md',
      'docs/development/directory-baseline-git-land-design-20260329.md',
      'docs/development/directory-baseline-git-land-verification-20260329.md',
      'docs/development/directory-baseline-git-publish-design-20260329.md',
      'docs/development/directory-baseline-git-publish-verification-20260329.md',
      'docs/development/directory-baseline-git-deliver-design-20260329.md',
      'docs/development/directory-baseline-git-deliver-verification-20260329.md',
      'docs/development/remote-git-slice-land-design-20260329.md',
      'docs/development/remote-git-slice-land-verification-20260329.md',
      'docs/development/remote-git-slice-publish-design-20260329.md',
      'docs/development/remote-git-slice-publish-verification-20260329.md',
      'docs/development/remote-git-slice-deliver-design-20260329.md',
      'docs/development/remote-git-slice-deliver-verification-20260329.md',
      'docs/development/directory-migration-baseline-hardening-design-20260327.md',
      'docs/development/directory-migration-baseline-hardening-verification-20260327.md',
      'docs/development/dingtalk-directory-git-baseline-20260327.md',
      'docs/development/directory-migration-baseline-git-slice-20260328.md',
      'docs/verification-index.md',
      'docs/development/directory-baseline-host-runtime-and-git-slice-design-20260328.md',
      'docs/development/directory-baseline-host-runtime-and-git-slice-verification-20260328.md',
      'docs/development/directory-baseline-git-sync-plan-design-20260328.md',
      'docs/development/directory-baseline-git-sync-plan-verification-20260328.md',
    ],
    commitGroups: [
      {
        id: 'core-backend-migration-cli',
        message: 'feat(core-backend): add migration audit cli and stable ordering',
        files: [
          'packages/core-backend/package.json',
          'packages/core-backend/src/db/migrate.ts',
          'packages/core-backend/src/db/migration-audit.ts',
          'packages/core-backend/src/db/migration-health.ts',
          'packages/core-backend/src/db/types.ts',
        ],
      },
      {
        id: 'directory-iam-migrations',
        message: 'feat(core-backend): add required directory iam migrations',
        files: [
          'packages/core-backend/src/db/migrations/zzzz20260323120000_create_user_external_identities.ts',
          'packages/core-backend/src/db/migrations/zzzz20260323133000_harden_user_external_identities.ts',
          'packages/core-backend/src/db/migrations/zzzz20260324143000_create_user_external_auth_grants.ts',
          'packages/core-backend/src/db/migrations/zzzz20260324150000_create_directory_sync_tables.ts',
          'packages/core-backend/src/db/migrations/zzzz20260325100000_add_mobile_to_users_table.ts',
          'packages/core-backend/src/db/migrations/zzzz20260327110000_create_directory_template_center_and_alerts.ts',
        ],
      },
      {
        id: 'ops-baseline-tooling',
        message: 'chore(ops): add baseline slice sync and host runtime tooling',
        files: [
          'package.json',
          'scripts/ops/git-baseline-report.mjs',
          'scripts/ops/git-slice-apply.mjs',
          'scripts/ops/git-slice-bundle.mjs',
          'scripts/ops/git-slice-handoff.mjs',
          'scripts/ops/git-slice-materialize.mjs',
          'scripts/ops/git-slice-promote.mjs',
          'scripts/ops/git-slice-replay.mjs',
          'scripts/ops/git-slice-attest.mjs',
          'scripts/ops/git-slice-submit.mjs',
          'scripts/ops/git-slice-land.mjs',
          'scripts/ops/git-slice-publish.mjs',
          'scripts/ops/git-slice-deliver.mjs',
          'scripts/ops/git-slices.mjs',
          'scripts/ops/git-slice-report.mjs',
          'scripts/ops/git-slice-sync-plan.mjs',
          'scripts/ops/attest-remote-git-slice.sh',
          'scripts/ops/handoff-remote-git-slice.sh',
          'scripts/ops/materialize-remote-git-slice.sh',
          'scripts/ops/promote-remote-git-slice.sh',
          'scripts/ops/replay-remote-git-slice.sh',
          'scripts/ops/land-remote-git-slice.sh',
          'scripts/ops/publish-remote-git-slice.sh',
          'scripts/ops/deliver-remote-git-slice.sh',
          'scripts/ops/submit-remote-git-slice.sh',
          'scripts/ops/install-user-node-runtime.sh',
        ],
      },
      {
        id: 'migration-audit-tests',
        message: 'test(core-backend): cover migration audit and compatibility',
        files: [
          'packages/core-backend/tests/unit/migration-audit.test.ts',
          'packages/core-backend/tests/unit/migration-health.test.ts',
        ],
      },
      {
        id: 'migration-baseline-docs',
        message: 'docs: record migration baseline hardening and git slice',
        files: [
          'docs/development/directory-baseline-git-apply-design-20260328.md',
          'docs/development/directory-baseline-git-apply-verification-20260328.md',
          'docs/development/directory-baseline-git-bundle-design-20260328.md',
          'docs/development/directory-baseline-git-bundle-verification-20260328.md',
          'docs/development/directory-baseline-git-handoff-design-20260329.md',
          'docs/development/directory-baseline-git-handoff-verification-20260329.md',
          'docs/development/directory-baseline-git-materialize-design-20260328.md',
          'docs/development/directory-baseline-git-materialize-verification-20260328.md',
          'docs/development/directory-baseline-git-promote-design-20260328.md',
          'docs/development/directory-baseline-git-promote-verification-20260328.md',
          'docs/development/directory-baseline-git-replay-design-20260329.md',
          'docs/development/directory-baseline-git-replay-verification-20260329.md',
          'docs/development/directory-baseline-git-attest-design-20260329.md',
          'docs/development/directory-baseline-git-attest-verification-20260329.md',
          'docs/development/directory-baseline-git-submit-design-20260329.md',
          'docs/development/directory-baseline-git-submit-verification-20260329.md',
          'docs/development/remote-git-slice-materialize-design-20260328.md',
          'docs/development/remote-git-slice-materialize-verification-20260328.md',
          'docs/development/remote-git-slice-handoff-design-20260329.md',
          'docs/development/remote-git-slice-handoff-verification-20260329.md',
          'docs/development/remote-git-slice-promote-design-20260328.md',
          'docs/development/remote-git-slice-promote-verification-20260328.md',
          'docs/development/remote-git-slice-replay-design-20260329.md',
          'docs/development/remote-git-slice-replay-verification-20260329.md',
          'docs/development/remote-git-slice-attest-design-20260329.md',
          'docs/development/remote-git-slice-attest-verification-20260329.md',
          'docs/development/remote-git-slice-submit-design-20260329.md',
          'docs/development/remote-git-slice-submit-verification-20260329.md',
          'docs/development/directory-baseline-git-land-design-20260329.md',
          'docs/development/directory-baseline-git-land-verification-20260329.md',
          'docs/development/directory-baseline-git-publish-design-20260329.md',
          'docs/development/directory-baseline-git-publish-verification-20260329.md',
          'docs/development/directory-baseline-git-deliver-design-20260329.md',
          'docs/development/directory-baseline-git-deliver-verification-20260329.md',
          'docs/development/remote-git-slice-land-design-20260329.md',
          'docs/development/remote-git-slice-land-verification-20260329.md',
          'docs/development/remote-git-slice-publish-design-20260329.md',
          'docs/development/remote-git-slice-publish-verification-20260329.md',
          'docs/development/remote-git-slice-deliver-design-20260329.md',
          'docs/development/remote-git-slice-deliver-verification-20260329.md',
          'docs/development/directory-migration-baseline-hardening-design-20260327.md',
          'docs/development/directory-migration-baseline-hardening-verification-20260327.md',
          'docs/development/dingtalk-directory-git-baseline-20260327.md',
          'docs/development/directory-migration-baseline-git-slice-20260328.md',
          'docs/verification-index.md',
          'docs/development/directory-baseline-host-runtime-and-git-slice-design-20260328.md',
          'docs/development/directory-baseline-host-runtime-and-git-slice-verification-20260328.md',
          'docs/development/directory-baseline-git-sync-plan-design-20260328.md',
          'docs/development/directory-baseline-git-sync-plan-verification-20260328.md',
        ],
      },
    ],
    suggestedCommits: [
      'feat(core-backend): add migration audit cli and stable ordering',
      'feat(core-backend): add required directory iam migrations',
      'chore(ops): add baseline slice sync and host runtime tooling',
      'test(core-backend): cover migration audit and compatibility',
      'docs: record migration baseline hardening and git slice',
    ],
  },
}
