import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const manualWorkflowPath = path.join(repoRoot, '.github', 'workflows', 'integration-k3wise-postdeploy-smoke.yml')
const deployWorkflowPath = path.join(repoRoot, '.github', 'workflows', 'docker-build.yml')

function assertContains(haystack, needle, label) {
  assert.ok(
    String(haystack).includes(needle),
    `${label} must include ${needle}`,
  )
}

test('manual K3 WISE postdeploy smoke workflow keeps dispatch and auth contract stable', () => {
  const raw = readFileSync(manualWorkflowPath, 'utf8')

  assertContains(raw, 'name: K3 WISE Postdeploy Smoke', 'manual workflow')
  assertContains(raw, 'workflow_dispatch:', 'manual trigger')
  assertContains(raw, 'base_url:', 'manual inputs')
  assertContains(raw, "default: 'http://142.171.239.56:8081'", 'manual default base URL')
  assertContains(raw, 'require_auth:', 'manual inputs')
  assertContains(raw, 'keep true for internal-trial signoff', 'manual require_auth input')
  assertContains(raw, "default: 'true'", 'manual require_auth input')
  assertContains(raw, 'type: choice', 'manual require_auth input')
  assertContains(raw, "- 'false'", 'manual require_auth input')
  assertContains(raw, "- 'true'", 'manual require_auth input')
  assertContains(raw, 'tenant_id:', 'manual inputs')
  assertContains(raw, 'Optional tenantId for authenticated control-plane list probes', 'manual tenant input')
  assertContains(raw, 'auto_discover_tenant:', 'manual inputs')
  assertContains(raw, 'Allow deploy-host fallback to infer tenant only when exactly one integration tenant exists', 'manual auto-discover input')
  assertContains(raw, "default: '10000'", 'manual timeout input')
  assertContains(raw, 'contents: read', 'manual permissions')
  assertContains(raw, 'actions: read', 'manual permissions')
  assertContains(raw, '- name: Resolve K3 WISE smoke token', 'manual token resolver step')
  assertContains(raw, 'METASHEET_K3WISE_SMOKE_TOKEN_SECRET: ${{ secrets.METASHEET_K3WISE_SMOKE_TOKEN }}', 'manual token resolver step')
  assertContains(raw, "K3_WISE_TOKEN_RESOLVE_REQUIRED: ${{ github.event.inputs.require_auth || 'true' }}", 'manual token resolver step')
  assertContains(raw, "K3_WISE_TOKEN_AUTO_DISCOVER_TENANT: ${{ github.event.inputs.auto_discover_tenant || vars.K3_WISE_TOKEN_AUTO_DISCOVER_TENANT || 'false' }}", 'manual token resolver step')
  assertContains(raw, 'DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}', 'manual token resolver step')
  assertContains(raw, 'scripts/ops/resolve-k3wise-smoke-token.sh', 'manual token resolver step')
  assertContains(raw, 'id: token_resolve', 'manual token resolver step')
  assertContains(raw, 'continue-on-error: true', 'manual token resolver step')
  assertContains(raw, 'token_resolve_rc=$rc', 'manual token resolver step')
  assertContains(raw, '- name: Run K3 WISE postdeploy smoke', 'manual smoke step')
  assertContains(raw, 'continue-on-error: true', 'manual smoke step')
  assertContains(raw, "METASHEET_TENANT_ID: ${{ github.event.inputs.tenant_id || vars.METASHEET_TENANT_ID || '' }}", 'manual smoke step')
  assertContains(raw, "REQUIRE_AUTH: ${{ github.event.inputs.require_auth || 'true' }}", 'manual smoke step')
  assertContains(raw, 'smoke_out_dir="output/integration-k3wise-postdeploy-smoke/manual"', 'manual smoke step')
  assertContains(raw, 'node scripts/ops/integration-k3wise-postdeploy-smoke.mjs', 'manual smoke step')
  assertContains(raw, '--base-url "$METASHEET_BASE_URL"', 'manual smoke step')
  assertContains(raw, '--out-dir "$smoke_out_dir"', 'manual smoke step')
  assertContains(raw, '--timeout-ms "$TIMEOUT_MS"', 'manual smoke step')
  assertContains(raw, 'tenant_id="${METASHEET_TENANT_ID:-${K3_WISE_SMOKE_TENANT_ID:-}}"', 'manual smoke step')
  assertContains(raw, 'args+=(--require-auth)', 'manual smoke step')
  assertContains(raw, 'args+=(--tenant-id "$tenant_id")', 'manual smoke step')
  assertContains(raw, 'export METASHEET_AUTH_TOKEN="$K3_WISE_SMOKE_TOKEN"', 'manual smoke step')
  assertContains(raw, 'stderr.log', 'manual smoke step')
  assertContains(raw, 'cli-summary.json', 'manual smoke step')
  assertContains(raw, 'smoke_rc=$rc', 'manual smoke step')
  assertContains(raw, '- name: Write K3 WISE smoke summary', 'manual summary step')
  assertContains(raw, 'if: always()', 'manual always-run steps')
  assertContains(raw, 'scripts/ops/integration-k3wise-postdeploy-summary.mjs', 'manual summary step')
  assertContains(raw, 'output/integration-k3wise-postdeploy-smoke/manual/integration-k3wise-postdeploy-smoke.json', 'manual summary step')
  assertContains(raw, '--require-auth-signoff', 'manual summary step')
  assertContains(raw, '--missing-ok', 'manual summary step')
  assertContains(raw, 'integration-k3wise-postdeploy-smoke-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}', 'manual summary step')
  assertContains(raw, '- name: Upload K3 WISE smoke artifacts', 'manual artifact upload')
  assertContains(raw, 'uses: actions/upload-artifact@v4', 'manual artifact upload')
  assertContains(raw, 'name: integration-k3wise-postdeploy-smoke-${{ github.run_id }}-${{ github.run_attempt }}', 'manual artifact upload')
  assertContains(raw, 'output/integration-k3wise-postdeploy-smoke/manual/**', 'manual artifact upload')
  assertContains(raw, '- name: Fail when K3 WISE smoke failed', 'manual final gate')
  assertContains(raw, 'steps.token_resolve.outputs.token_resolve_rc', 'manual final gate')
  assertContains(raw, 'steps.smoke.outputs.smoke_rc', 'manual final gate')
  assertContains(raw, 'K3 WISE smoke token resolution failed', 'manual final gate')
  assertContains(raw, 'K3 WISE postdeploy smoke failed', 'manual final gate')
})

test('deploy workflow keeps K3 WISE smoke evidence wired into deploy summary and artifacts', () => {
  const raw = readFileSync(deployWorkflowPath, 'utf8')

  assertContains(raw, 'deploy:', 'docker-build deploy job')
  assertContains(raw, '- name: Resolve K3 WISE smoke token', 'deploy token resolver step')
  assertContains(raw, 'METASHEET_K3WISE_SMOKE_TOKEN_SECRET: ${{ secrets.METASHEET_K3WISE_SMOKE_TOKEN }}', 'deploy token resolver step')
  assertContains(raw, "K3_WISE_TOKEN_RESOLVE_REQUIRED: ${{ vars.K3_WISE_DEPLOY_SMOKE_REQUIRE_AUTH || 'false' }}", 'deploy token resolver step')
  assertContains(raw, "K3_WISE_TOKEN_AUTO_DISCOVER_TENANT: ${{ vars.K3_WISE_TOKEN_AUTO_DISCOVER_TENANT || 'false' }}", 'deploy token resolver step')
  assertContains(raw, 'DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}', 'deploy token resolver step')
  assertContains(raw, 'scripts/ops/resolve-k3wise-smoke-token.sh', 'deploy token resolver step')
  assertContains(raw, 'id: k3_token_resolve', 'deploy token resolver step')
  assertContains(raw, 'continue-on-error: true', 'deploy token resolver step')
  assertContains(raw, 'token_resolve_rc=$rc', 'deploy token resolver step')
  assertContains(raw, '- name: K3 WISE postdeploy smoke', 'deploy smoke step')
  assertContains(raw, "if: ${{ steps.remote_deploy.outputs.deploy_rc == '0' }}", 'deploy smoke step')
  assertContains(raw, 'id: k3_smoke', 'deploy smoke step')
  assertContains(raw, 'continue-on-error: true', 'deploy smoke step')
  assertContains(raw, "METASHEET_TENANT_ID: ${{ vars.METASHEET_TENANT_ID || '' }}", 'deploy smoke step')
  assertContains(raw, "K3_WISE_DEPLOY_SMOKE_REQUIRE_AUTH: ${{ vars.K3_WISE_DEPLOY_SMOKE_REQUIRE_AUTH || 'false' }}", 'deploy smoke step')
  assertContains(raw, 'smoke_out_dir="output/deploy/k3wise-postdeploy-smoke"', 'deploy smoke step')
  assertContains(raw, 'node scripts/ops/integration-k3wise-postdeploy-smoke.mjs', 'deploy smoke step')
  assertContains(raw, '--base-url "$METASHEET_BASE_URL"', 'deploy smoke step')
  assertContains(raw, '--out-dir "$smoke_out_dir"', 'deploy smoke step')
  assertContains(raw, 'require_auth="${K3_WISE_DEPLOY_SMOKE_REQUIRE_AUTH:-false}"', 'deploy smoke step')
  assertContains(raw, 'case "${require_auth}" in', 'deploy smoke step')
  assertContains(raw, 'true|TRUE|True|1|yes|YES|Yes)', 'deploy smoke step')
  assertContains(raw, 'args+=(--require-auth)', 'deploy smoke step')
  assertContains(raw, 'tenant_id="${METASHEET_TENANT_ID:-${K3_WISE_SMOKE_TENANT_ID:-}}"', 'deploy smoke step')
  assertContains(raw, 'args+=(--tenant-id "$tenant_id")', 'deploy smoke step')
  assertContains(raw, 'export METASHEET_AUTH_TOKEN="$K3_WISE_SMOKE_TOKEN"', 'deploy smoke step')
  assertContains(raw, 'stderr.log', 'deploy smoke step')
  assertContains(raw, 'cli-summary.json', 'deploy smoke step')
  assertContains(raw, 'smoke_rc=$rc', 'deploy smoke step')
  assertContains(raw, '- name: Write deploy summary (preflight + runbooks)', 'deploy summary step')
  assertContains(raw, '### K3 WISE Postdeploy Smoke', 'deploy summary step')
  assertContains(raw, 'k3_smoke_json="output/deploy/k3wise-postdeploy-smoke/integration-k3wise-postdeploy-smoke.json"', 'deploy summary step')
  assertContains(raw, 'scripts/ops/integration-k3wise-postdeploy-summary.mjs', 'deploy summary step')
  assertContains(raw, '--input "$k3_smoke_json"', 'deploy summary step')
  assertContains(raw, '--require-auth-signoff', 'deploy summary step')
  assertContains(raw, '--missing-ok', 'deploy summary step')
  assertContains(raw, 'K3 WISE smoke evidence:', 'deploy summary step')
  assertContains(raw, 'output/deploy/k3wise-postdeploy-smoke/', 'deploy summary step')
  assertContains(raw, 'cp "$GITHUB_STEP_SUMMARY" output/deploy/step-summary.md', 'deploy summary archive')
  assertContains(raw, '- name: Upload deploy artifacts', 'deploy artifact upload')
  assertContains(raw, 'uses: actions/upload-artifact@v4', 'deploy artifact upload')
  assertContains(raw, 'output/deploy/**', 'deploy artifact upload')
  assertContains(raw, 'steps.k3_token_resolve.outputs.token_resolve_rc', 'deploy final gate')
  assertContains(raw, 'steps.k3_smoke.outputs.smoke_rc', 'deploy final gate')
  assertContains(raw, 'K3 WISE smoke token resolution failed', 'deploy final gate')
  assertContains(raw, 'K3 WISE postdeploy smoke failed', 'deploy final gate')
})
