import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const scriptPath = path.join(repoRoot, 'scripts', 'ops', 'validate-dingtalk-staging-evidence-packet.mjs')
const exporterPath = path.join(repoRoot, 'scripts', 'ops', 'export-dingtalk-staging-evidence-packet.mjs')
const requiredCheckIds = [
  'create-table-form',
  'bind-two-dingtalk-groups',
  'set-form-dingtalk-granted',
  'send-group-message-form-link',
  'authorized-user-submit',
  'unauthorized-user-denied',
  'delivery-history-group-person',
  'no-email-user-create-bind',
]

function makeTmpDir() {
  return mkdtempSync(path.join(tmpdir(), 'dingtalk-packet-publish-check-'))
}

function writeJson(file, value) {
  mkdirSync(path.dirname(file), { recursive: true })
  writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, 'utf8')
}

function writeFinalSession(evidenceDir, overrides = {}) {
  writeJson(path.join(evidenceDir, 'session-summary.json'), {
    tool: 'dingtalk-p4-smoke-session',
    sessionPhase: 'finalize',
    overallStatus: 'pass',
    finalStrictStatus: 'pass',
    steps: [
      { id: 'preflight', status: 'pass', exitCode: 0 },
      { id: 'api-runner', status: 'pass', exitCode: 0 },
      { id: 'compile', status: 'pass', exitCode: 0 },
      { id: 'strict-compile', status: 'pass', exitCode: 0 },
    ],
    pendingChecks: [],
    ...overrides.sessionSummary,
  })
  writeJson(path.join(evidenceDir, 'compiled', 'summary.json'), {
    tool: 'compile-dingtalk-p4-smoke-evidence',
    overallStatus: 'pass',
    apiBootstrapStatus: 'pass',
    remoteClientStatus: 'pass',
    remoteSmokePhase: 'finalize_pending',
    totals: {
      totalChecks: requiredCheckIds.length,
      requiredChecks: requiredCheckIds.length,
      passedChecks: requiredCheckIds.length,
      failedChecks: 0,
      skippedChecks: 0,
      pendingChecks: 0,
      missingRequiredChecks: 0,
      unknownChecks: 0,
    },
    requiredChecks: requiredCheckIds.map((id) => ({ id, status: 'pass' })),
    missingRequiredChecks: [],
    requiredChecksNotPassed: [],
    failedChecks: [],
    unknownChecks: [],
    manualEvidenceIssues: [],
    ...overrides.compiledSummary,
  })
}

function writePacket(packetDir, overrides = {}) {
  const evidenceDestination = overrides.destination ?? 'evidence/01-142-session'
  const evidenceDir = path.join(packetDir, evidenceDestination)
  mkdirSync(packetDir, { recursive: true })
  writeFileSync(path.join(packetDir, 'README.md'), '# DingTalk Staging Evidence Packet\n', 'utf8')
  writeFinalSession(evidenceDir, overrides)
  writeJson(path.join(packetDir, 'manifest.json'), {
    packet: 'dingtalk-staging-evidence-packet',
    generatedAt: new Date().toISOString(),
    repoRoot,
    requireDingTalkP4Pass: true,
    files: [],
    includedEvidence: [
      {
        source: 'output/dingtalk-p4-remote-smoke-session/142-session',
        destination: evidenceDestination,
        dingtalkP4FinalStatus: {
          status: 'pass',
          sessionSummary: 'session-summary.json',
          compiledSummary: 'compiled/summary.json',
          sessionPhase: 'finalize',
          finalStrictStatus: 'pass',
          compiledOverallStatus: 'pass',
          apiBootstrapStatus: 'pass',
          remoteClientStatus: 'pass',
          remoteSmokePhase: 'finalize_pending',
          requiredChecks: requiredCheckIds.length,
          ...overrides.dingtalkP4FinalStatus,
        },
      },
    ],
    ...overrides.manifest,
  })
  return evidenceDir
}

function runValidator(args) {
  return spawnSync(process.execPath, [scriptPath, ...args], {
    cwd: repoRoot,
    encoding: 'utf8',
  })
}

test('validate-dingtalk-staging-evidence-packet accepts a packet generated by the exporter', () => {
  const tmpDir = makeTmpDir()
  const sessionDir = path.join(tmpDir, '142-session')
  const packetDir = path.join(tmpDir, 'packet')

  try {
    writeFinalSession(sessionDir)
    const exportResult = spawnSync(
      process.execPath,
      [
        exporterPath,
        '--output-dir',
        packetDir,
        '--include-output',
        sessionDir,
        '--require-dingtalk-p4-pass',
      ],
      {
        cwd: repoRoot,
        encoding: 'utf8',
      },
    )

    assert.equal(exportResult.status, 0, exportResult.stderr || exportResult.stdout)
    const result = runValidator(['--packet-dir', packetDir])

    assert.equal(result.status, 0, result.stderr)
    assert.match(result.stdout, /publish check passed/)
  } finally {
    rmSync(tmpDir, { recursive: true, force: true })
  }
})

test('validate-dingtalk-staging-evidence-packet accepts a final gated packet and writes report', () => {
  const tmpDir = makeTmpDir()
  const packetDir = path.join(tmpDir, 'packet')
  const reportPath = path.join(tmpDir, 'publish-check.json')

  try {
    writePacket(packetDir)

    const result = runValidator(['--packet-dir', packetDir, '--output-json', reportPath])

    assert.equal(result.status, 0, result.stderr)
    assert.match(result.stdout, /publish check passed/)
    assert.equal(existsSync(reportPath), true)
    const report = JSON.parse(readFileSync(reportPath, 'utf8'))
    assert.equal(report.status, 'pass')
    assert.equal(report.includedEvidenceCount, 1)
    assert.equal(report.secretFindings.length, 0)
  } finally {
    rmSync(tmpDir, { recursive: true, force: true })
  }
})

test('validate-dingtalk-staging-evidence-packet rejects ungated packet manifest', () => {
  const tmpDir = makeTmpDir()
  const packetDir = path.join(tmpDir, 'packet')

  try {
    writePacket(packetDir, {
      manifest: {
        requireDingTalkP4Pass: false,
      },
    })

    const result = runValidator(['--packet-dir', packetDir])

    assert.equal(result.status, 1)
    assert.match(result.stderr, /manifest requireDingTalkP4Pass is not true/)
  } finally {
    rmSync(tmpDir, { recursive: true, force: true })
  }
})

test('validate-dingtalk-staging-evidence-packet rejects non-final included evidence', () => {
  const tmpDir = makeTmpDir()
  const packetDir = path.join(tmpDir, 'packet')

  try {
    writePacket(packetDir, {
      dingtalkP4FinalStatus: {
        finalStrictStatus: 'fail',
      },
      sessionSummary: {
        finalStrictStatus: 'fail',
        steps: [
          { id: 'preflight', status: 'pass', exitCode: 0 },
          { id: 'api-runner', status: 'pass', exitCode: 0 },
          { id: 'compile', status: 'pass', exitCode: 0 },
          { id: 'strict-compile', status: 'fail', exitCode: 1 },
        ],
      },
    })

    const result = runValidator(['--packet-dir', packetDir])

    assert.equal(result.status, 1)
    assert.match(result.stderr, /dingtalkP4FinalStatus\.finalStrictStatus is not pass/)
    assert.match(result.stderr, /strict-compile step is not pass/)
  } finally {
    rmSync(tmpDir, { recursive: true, force: true })
  }
})

test('validate-dingtalk-staging-evidence-packet rejects invalid remote smoke phase metadata', () => {
  const tmpDir = makeTmpDir()
  const packetDir = path.join(tmpDir, 'packet')

  try {
    writePacket(packetDir, {
      dingtalkP4FinalStatus: {
        remoteSmokePhase: 'release_ready',
      },
      compiledSummary: {
        remoteSmokePhase: 'release_ready',
      },
    })

    const result = runValidator(['--packet-dir', packetDir])

    assert.equal(result.status, 1)
    assert.match(result.stderr, /dingtalkP4FinalStatus\.remoteSmokePhase is not a recognized remote smoke phase/)
    assert.match(result.stderr, /compiled\/summary\.json remoteSmokePhase is not a recognized remote smoke phase/)
  } finally {
    rmSync(tmpDir, { recursive: true, force: true })
  }
})

test('validate-dingtalk-staging-evidence-packet rejects destination path traversal', () => {
  const tmpDir = makeTmpDir()
  const packetDir = path.join(tmpDir, 'packet')
  const evidenceDir = writePacket(packetDir)

  try {
    const manifestPath = path.join(packetDir, 'manifest.json')
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))
    manifest.includedEvidence[0].destination = '../outside'
    writeJson(manifestPath, manifest)

    const result = runValidator(['--packet-dir', packetDir])

    assert.equal(result.status, 1)
    assert.match(result.stderr, /escapes the packet directory/)
    assert.equal(existsSync(evidenceDir), true)
  } finally {
    rmSync(tmpDir, { recursive: true, force: true })
  }
})

test('validate-dingtalk-staging-evidence-packet rejects unregistered evidence entries', () => {
  const tmpDir = makeTmpDir()
  const packetDir = path.join(tmpDir, 'packet')

  try {
    writePacket(packetDir)
    mkdirSync(path.join(packetDir, 'evidence/99-old-session'), { recursive: true })
    writeFileSync(path.join(packetDir, 'evidence/99-old-session/stale.txt'), 'stale\n', 'utf8')

    const result = runValidator(['--packet-dir', packetDir])

    assert.equal(result.status, 1)
    assert.match(result.stderr, /evidence\/99-old-session is not registered in manifest includedEvidence/)
  } finally {
    rmSync(tmpDir, { recursive: true, force: true })
  }
})

test('validate-dingtalk-staging-evidence-packet rejects secret-like raw evidence', () => {
  const tmpDir = makeTmpDir()
  const packetDir = path.join(tmpDir, 'packet')
  const reportPath = path.join(tmpDir, 'publish-check.json')

  try {
    const evidenceDir = writePacket(packetDir)
    mkdirSync(path.join(evidenceDir, 'workspace', 'artifacts', 'send-group-message-form-link'), { recursive: true })
    writeFileSync(
      path.join(evidenceDir, 'workspace', 'artifacts', 'send-group-message-form-link', 'leaked.txt'),
      'robot=https://oapi.dingtalk.com/robot/send?access_token=0123456789abcdef0123456789abcdef\nsecret=SECabcdefghijklmnop12345678\n',
      'utf8',
    )

    const result = runValidator(['--packet-dir', packetDir, '--output-json', reportPath])

    assert.equal(result.status, 1)
    assert.match(result.stderr, /secret-like value detected/)
    assert.match(result.stderr, /dingtalk_robot_webhook|dingtalk_sec_secret/)
    const reportText = readFileSync(reportPath, 'utf8')
    assert.doesNotMatch(reportText, /0123456789abcdef/)
    assert.doesNotMatch(reportText, /SECabcdefghijklmnop12345678/)
    const report = JSON.parse(reportText)
    assert.match(report.secretFindings[0].preview, /^<redacted /)
  } finally {
    rmSync(tmpDir, { recursive: true, force: true })
  }
})

test('validate-dingtalk-staging-evidence-packet rejects unknown arguments', () => {
  const result = runValidator(['--unknown'])

  assert.equal(result.status, 1)
  assert.match(result.stderr, /Unknown argument: --unknown/)
})
