openapi: 3.0.3
info:
  title: Metasheet v2 API
  version: 0.1.0
servers:
  - url: http://localhost:8900
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    StandardResponse:
      type: object
      properties:
        ok:
          type: boolean
        data:
          nullable: true
    ErrorResponse:
      type: object
      properties:
        ok:
          type: boolean
          default: false
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
    AttendanceEvent:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        org_id:
          type: string
        work_date:
          type: string
          format: date
        occurred_at:
          type: string
          format: date-time
        event_type:
          type: string
          enum: [check_in, check_out, adjustment]
        source:
          type: string
        timezone:
          type: string
        location:
          type: object
        meta:
          type: object
        created_at:
          type: string
          format: date-time
    AttendanceRecord:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        org_id:
          type: string
        work_date:
          type: string
          format: date
        timezone:
          type: string
        first_in_at:
          type: string
          format: date-time
          nullable: true
        last_out_at:
          type: string
          format: date-time
          nullable: true
        work_minutes:
          type: integer
        late_minutes:
          type: integer
        early_leave_minutes:
          type: integer
        status:
          type: string
        is_workday:
          type: boolean
        meta:
          type: object
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    AttendanceRequest:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        org_id:
          type: string
        work_date:
          type: string
          format: date
        request_type:
          type: string
          enum: [missed_check_in, missed_check_out, time_correction, leave, overtime]
        requested_in_at:
          type: string
          format: date-time
          nullable: true
        requested_out_at:
          type: string
          format: date-time
          nullable: true
        reason:
          type: string
          nullable: true
        status:
          type: string
          enum: [pending, approved, rejected, cancelled]
        approval_instance_id:
          type: string
          nullable: true
        resolved_by:
          type: string
          nullable: true
        resolved_at:
          type: string
          format: date-time
          nullable: true
        metadata:
          type: object
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    AttendanceLeaveType:
      type: object
      properties:
        id:
          type: string
        orgId:
          type: string
        code:
          type: string
        name:
          type: string
        requiresApproval:
          type: boolean
        requiresAttachment:
          type: boolean
        defaultMinutesPerDay:
          type: integer
        isActive:
          type: boolean
    AttendanceOvertimeRule:
      type: object
      properties:
        id:
          type: string
        orgId:
          type: string
        name:
          type: string
        minMinutes:
          type: integer
        roundingMinutes:
          type: integer
        maxMinutesPerDay:
          type: integer
        requiresApproval:
          type: boolean
        isActive:
          type: boolean
    AttendanceApprovalStep:
      type: object
      properties:
        name:
          type: string
        approverUserIds:
          type: array
          items:
            type: string
        approverRoleIds:
          type: array
          items:
            type: string
    AttendanceApprovalFlow:
      type: object
      properties:
        id:
          type: string
        orgId:
          type: string
        name:
          type: string
        requestType:
          type: string
        steps:
          type: array
          items:
            $ref: '#/components/schemas/AttendanceApprovalStep'
        isActive:
          type: boolean
    AttendanceRotationRule:
      type: object
      properties:
        id:
          type: string
        orgId:
          type: string
        name:
          type: string
        timezone:
          type: string
        shiftSequence:
          type: array
          items:
            type: string
        isActive:
          type: boolean
    AttendanceRotationAssignment:
      type: object
      properties:
        id:
          type: string
        orgId:
          type: string
        userId:
          type: string
        rotationRuleId:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
          nullable: true
        isActive:
          type: boolean
    AttendanceRotationAssignmentItem:
      type: object
      properties:
        assignment:
          $ref: '#/components/schemas/AttendanceRotationAssignment'
        rotation:
          $ref: '#/components/schemas/AttendanceRotationRule'
    AttendanceRequestReportItem:
      type: object
      properties:
        requestType:
          type: string
        status:
          type: string
        total:
          type: integer
        minutes:
          type: integer
    AttendanceSummary:
      type: object
      properties:
        total_days:
          type: integer
        total_minutes:
          type: integer
        normal_days:
          type: integer
        late_days:
          type: integer
        early_leave_days:
          type: integer
        late_early_days:
          type: integer
        partial_days:
          type: integer
        absent_days:
          type: integer
        adjusted_days:
          type: integer
        off_days:
          type: integer
    AttendanceRule:
      type: object
      properties:
        id:
          type: string
        orgId:
          type: string
        name:
          type: string
        timezone:
          type: string
        workStartTime:
          type: string
        workEndTime:
          type: string
        lateGraceMinutes:
          type: integer
        earlyGraceMinutes:
          type: integer
        roundingMinutes:
          type: integer
        workingDays:
          type: array
          items:
            type: integer
        isDefault:
          type: boolean
    AttendanceShift:
      type: object
      properties:
        id:
          type: string
        orgId:
          type: string
        name:
          type: string
        timezone:
          type: string
        workStartTime:
          type: string
        workEndTime:
          type: string
        lateGraceMinutes:
          type: integer
        earlyGraceMinutes:
          type: integer
        roundingMinutes:
          type: integer
        workingDays:
          type: array
          items:
            type: integer
    AttendanceShiftAssignment:
      type: object
      properties:
        id:
          type: string
        orgId:
          type: string
        userId:
          type: string
        shiftId:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
          nullable: true
        isActive:
          type: boolean
    AttendanceHoliday:
      type: object
      properties:
        id:
          type: string
        orgId:
          type: string
        date:
          type: string
          format: date
        name:
          type: string
          nullable: true
        isWorkingDay:
          type: boolean
    AttendanceSettings:
      type: object
      properties:
        autoAbsence:
          type: object
          properties:
            enabled:
              type: boolean
            runAt:
              type: string
            lookbackDays:
              type: integer
        ipAllowlist:
          type: array
          items:
            type: string
        geoFence:
          type: object
          nullable: true
          properties:
            lat:
              type: number
            lng:
              type: number
            radiusMeters:
              type: integer
        minPunchIntervalMinutes:
          type: integer
    Spreadsheet:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        owner_id:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
          nullable: true
    Sheet:
      type: object
      properties:
        id:
          type: string
        spreadsheet_id:
          type: string
        name:
          type: string
        order_index:
          type: integer
        row_count:
          type: integer
        column_count:
          type: integer
        frozen_rows:
          type: integer
          nullable: true
        frozen_columns:
          type: integer
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Cell:
      type: object
      properties:
        id:
          type: string
        sheet_id:
          type: string
        row_index:
          type: integer
        column_index:
          type: integer
        value:
          nullable: true
        data_type:
          type: string
          nullable: true
        formula:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  responses:
    Unauthorized:
      description: Unauthorized - Missing or invalid JWT token
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
          examples:
            missing_token:
              summary: Missing Authorization Header
              value:
                ok: false
                error:
                  code: "UNAUTHORIZED"
                  message: "Authorization header is required"
            invalid_token:
              summary: Invalid JWT Token
              value:
                ok: false
                error:
                  code: "INVALID_TOKEN"
                  message: "Invalid or expired JWT token"
            malformed_token:
              summary: Malformed Token
              value:
                ok: false
                error:
                  code: "MALFORMED_TOKEN"
                  message: "Authorization header must start with 'Bearer '"
    Forbidden:
      description: Forbidden - Insufficient permissions
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
          examples:
            insufficient_permissions:
              summary: Insufficient Permissions
              value:
                ok: false
                error:
                  code: "FORBIDDEN"
                  message: "You do not have permission to perform this action"
            role_restricted:
              summary: Role Restriction
              value:
                ok: false
                error:
                  code: "ROLE_RESTRICTED"
                  message: "This action requires admin privileges"
            resource_access_denied:
              summary: Resource Access Denied
              value:
                ok: false
                error:
                  code: "ACCESS_DENIED"
                  message: "Access denied to this resource"
    ValidationError:
      description: Validation error - Invalid request data
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
          examples:
            missing_required_field:
              summary: Missing Required Field
              value:
                ok: false
                error:
                  code: "VALIDATION_ERROR"
                  message: "Required field 'name' is missing"
            invalid_field_type:
              summary: Invalid Field Type
              value:
                ok: false
                error:
                  code: "INVALID_TYPE"
                  message: "Field 'page' must be a positive integer"
            invalid_field_value:
              summary: Invalid Field Value
              value:
                ok: false
                error:
                  code: "INVALID_VALUE"
                  message: "Field 'pageSize' must be between 1 and 100"
            invalid_request_format:
              summary: Invalid Request Format
              value:
                ok: false
                error:
                  code: "INVALID_FORMAT"
                  message: "Request body must be valid JSON"
    NotFound:
      description: Not found - Resource does not exist
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
          examples:
            resource_not_found:
              summary: Resource Not Found
              value:
                ok: false
                error:
                  code: "NOT_FOUND"
                  message: "The requested resource was not found"
            user_not_found:
              summary: User Not Found
              value:
                ok: false
                error:
                  code: "USER_NOT_FOUND"
                  message: "User with ID 'user123' does not exist"
            role_not_found:
              summary: Role Not Found
              value:
                ok: false
                error:
                  code: "ROLE_NOT_FOUND"
                  message: "Role with ID 'role456' does not exist"
            spreadsheet_not_found:
              summary: Spreadsheet Not Found
              value:
                ok: false
                error:
                  code: "SPREADSHEET_NOT_FOUND"
                  message: "Spreadsheet with ID 'sheet789' does not exist"
            file_not_found:
              summary: File Not Found
              value:
                ok: false
                error:
                  code: "FILE_NOT_FOUND"
                  message: "File with ID 'file123' does not exist"
    ServiceUnavailable:
      description: Service unavailable - Temporary server issues
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
          examples:
            database_unavailable:
              summary: Database Unavailable
              value:
                ok: false
                error:
                  code: "DATABASE_UNAVAILABLE"
                  message: "Database connection temporarily unavailable"
            service_overloaded:
              summary: Service Overloaded
              value:
                ok: false
                error:
                  code: "SERVICE_OVERLOADED"
                  message: "Service temporarily overloaded, please try again later"
            maintenance_mode:
              summary: Maintenance Mode
              value:
                ok: false
                error:
                  code: "MAINTENANCE"
                  message: "Service is temporarily under maintenance"
    Pagination:
      type: object
      properties:
        items:
          type: array
          items: { }
        page:
          type: integer
          minimum: 1
        pageSize:
          type: integer
          minimum: 1
        total:
          type: integer
          minimum: 0
paths: {}
