/**
 * H-6 (2026-09-22, widened round 2 2026-09-22) — the required web lane's token SET must equal a
 * committed manifest.
 *
 * WHY THIS EXISTS
 * ----------------
 * `apps/web/scripts/run-required-web-tests.sh` has 19 logical lines that invoke `vitest run` after
 * `set -euo pipefail` — 18 earlier `npx vitest run …` lines plus the final `exec npx vitest run …`
 * line (see `required-web-lane-registration-shape.test.ts`, its neighbour in this directory, for
 * the exec block's own shape assertions). Together these are the positional token filters the
 * required `test (20.x)` -> `web-tests` pipeline actually runs. The shape guard proves the exec
 * block specifically is well-formed (one exec line, one token per line, sorted, no duplicates) —
 * it does NOT prove any line's token SET is the one anyone intended, and it says nothing at all
 * about the 18 earlier lines. Delete a token from the middle of an otherwise well-formed, sorted,
 * duplicate-free block and every one of the shape guard's assertions still passes: the file is
 * still exactly as shaped, just one filter shorter. A bad rebase, a careless manual edit, or a
 * "cleanup" pass that deletes the wrong line all produce that shape. See
 * docs/development/required-web-lane-token-manifest-guard-design-20260922.md (P2-2 of the
 * independent 2026-09-21 adversarial verification cited there: 357 examples of exactly this kind
 * of silent-drop-shaped-fine passed with zero automated gate on the token SET — restated with
 * measured numbers below, not "zero automated gate" universally: see ROUND 2 note).
 *
 * ROUND 2 (2026-09-22) — SCOPE WIDENED, P1-1 option (a) selected during implementation
 * --------------------------------------------------------------
 * An independent gate review of round 1
 * (`/Users/chouhua/.claude/projects/-Users-chouhua-Downloads-Github-metasheet2/reviews/impl-gate-H6-token-manifest-guard-round1-20260922.md`)
 * found that round 1's guard covered only the FINAL exec line's 397 tokens — one of the lane's 19
 * gating `vitest run` invocations. The other 18 carry **102 more** distinct tokens, of which round
 * 1's census counted **28** pinned by NOTHING else in the repo (P1-1). The review also measured
 * that the premise above is not universally true: **192 of the lane's 499 total tokens are already
 * gated today** by four existing census/shape guards union'd together
 * (`approval-ci-coverage-enumeration.test.ts`, `stock-prep-web-ci-coverage-enumeration.test.ts`,
 * `elearning-media-ci-wiring.test.mjs`, `network-unavailable-copy-ci-wiring.test.ts`) — P2-1. Round
 * 3 (2026-09-22, round-2 gate review, r2-P2-1) found this four-guard enumeration itself missed a
 * fifth/sixth guard, `attendance-web-guard-workflow.spec.ts`, which pins 4 more of the 28 (early
 * line 477's `sessionSpecs`) and 3 more of the 279 (exec-block tokens
 * `attendanceEmployeeMakeupRequestCard`/`attendanceEmployeeLeaveRequestCard`/
 * `attendance-selfservice-dashboard`) — see the design doc §1 for the recompute command and §10
 * for the full r2 disposition. Corrected, as bounds (not re-derived exactly across all four
 * original guards' predicates): the residual is **≤24**, the already-gated union is **≥199**, and
 * this file's actual measured contribution is **≤276** exec-block tokens moving from ungated to
 * gated, plus closing **≤24** earlier-line tokens gated by nothing at all (down from round 1/2's
 * uncorrected 279/28, per the sixth guard's 7 tokens found this round).
 *
 * Option (a) was **selected during implementation, not by the owner** — the round-1 reviewer's own
 * framing was that only (a) closes the residual, but no owner ruling exists on this PR
 * (`gh pr view 5974 --json comments,reviews` → 0 comments, 0 reviews); owner disposition is
 * pending and option (b) remains a fallback if the owner rules otherwise.
 *
 * This guard now asserts SET equality between `apps/web/scripts/run-required-web-tests.tokens`
 * (499 tokens, generated by `node scripts/ops/required-web-lane-token-manifest.mjs --write`, one
 * token per line plus a `#`-prefixed provenance header) and the UNION of all 19 gating
 * invocations' token sets (`allVitestTokens()`,
 * `scripts/ops/required-web-lane-exec-block.mjs`) — in both directions, reported separately so a
 * mutation of one direction cannot hide behind the other:
 *
 *   - a token in the manifest but produced by NO gating invocation -> silently dropped from the
 *     lane. The message names the scanned line numbers, not the token's former line — a dropped
 *     token is, by construction, on no remaining line, so this guard (which reads only the
 *     CURRENT script and manifest text, not git history) cannot know where it used to live.
 *   - a token produced by a gating invocation but not yet in the manifest -> added without
 *     updating the record. The message DOES name the exact source line(s), because that
 *     information is available for a token that still exists in the active text.
 *
 * This does NOT depend on git history (no merge-base, no `origin/main` diff) — see the design doc
 * for why a git-history-diff approach (compared and rejected as Option B) cannot run in this
 * repo's `push` event context (`plugin-tests.yml`'s checkouts are all default `actions/checkout@v4`
 * — fetch-depth 1, no `origin/main` ref available, and `push` events carry no `base_ref` at all).
 * Comparing two checked-in texts needs neither.
 *
 * PARSING: imports `allVitestInvocations` / `allVitestTokenLines` / `allVitestTokens` (round 2) and
 * `logicalLines` / `execLogicalLine` / `tokensOf` / `stripTrailingErrorGuard` from
 * `scripts/ops/required-web-lane-exec-block.mjs` — the SAME module the generator uses. See that
 * file's header for why it is a third extraction of `logicalLines`/`execLogicalLine`/`tokensOf`
 * rather than an import of either existing copy (one has `process.exit` at module top level, the
 * other's top level registers 18 `describe()` tests that would be double-counted by a second
 * import). Those three functions are kept ALGORITHMICALLY equivalent to **the shape guard's
 * copy** — see the "cross-copy agreement" tests below. ROUND 3 (r2-P3-2): a THIRD copy exists,
 * `scripts/ops/required-web-lane-token-set-diff.mjs` — `logicalLines`/`tokensOf` are identical
 * there too; `execLogicalLine` there genuinely diverges (an extra `label` parameter, a
 * `${label}: `-prefixed throw message) and the cross-copy tests below check that explicitly, not
 * silently.
 *
 * ROUND 4 (2026-09-22, merge-train dry-run v3 gate findings G1/G2 — see
 * `docs/development/required-web-lane-token-manifest-guard-verification-20260922.md` §r4):
 *   - G1: the cross-copy agreement tests used to diff the three copies' SOURCE TEXT byte-for-byte.
 *     The dry-run measured that merging this PR alongside an independent, unmerged sibling PR that
 *     refactors `required-web-lane-registration-shape.test.ts`'s `logicalLines()` into a thin
 *     wrapper over a new `logicalLinesWithLineNumbers()` helper (same behaviour, different bytes)
 *     reds that text diff for no actual drift. The tests now materialize each copy's extracted
 *     source into a real callable and compare OUTPUT across a named fixture battery instead — see
 *     the "cross-copy agreement" class comment further down for the fixture list and the one
 *     shape deliberately excluded from it. `required-web-lane-exec-block.mjs` gained a
 *     `logicalLinesWithLineNumbers()` export in the same round (its OWN output on any input is
 *     unchanged — see that file's own ROUND 4 note) so the line-number half of the comparison has
 *     a same-shaped function to compare against once a sibling copy exports one too.
 *   - G2: the M2 mutation-self-proof case asserted a hardcoded exec-block start line (`1257`) that
 *     the dry-run measured an independent sibling PR moving to `1359` by inserting comments above
 *     the block. The expected line is now PARSED from the real script via `allVitestInvocations`
 *     rather than hand-typed, plus a new discriminating test that inserts N comment lines above
 *     the block and asserts the detected start line moves by exactly N.
 *
 * CI WIRING: this file lives in `packages/core-backend/tests/unit/`, the same directory as its
 * shape-guard neighbour, and is picked up by the SAME mechanism — `pnpm --filter @metasheet/core-
 * backend test` (plugin-tests.yml `test` job, `Run core-backend tests` step) runs bare `vitest`,
 * which collects every `*.test.ts` in the package under `vitest.config.ts`'s default include glob
 * (no custom `include:` override exists in that config — verified by reading it) and excludes only
 * the explicit list. This file's name is not in that exclude list, so it is collected on both
 * matrix legs of the `test` job (`test (18.x)` and `test (20.x)`) — but only `test (20.x)` is a
 * REQUIRED status context (`gh api repos/zensgit/metasheet2/branches/main/protection` does not
 * list `test (18.x)`; `test (18.x)` running the identical step is still useful as non-required
 * real-CI evidence, not as the gate itself). Independently confirmed (not just inferred from
 * precedent): `npx vitest run required-web-lane --reporter=verbose` — a substring filter that
 * vitest applies AFTER globbing the whole package under the real config, not a literal path handed
 * straight to the loader — collects BOTH this file and the shape guard's file from that same
 * default-config glob.
 *
 * ROUND 5 (r4-P2-2) — the before/after TEST COUNT this comment used to quote is DELETED here
 * rather than re-measured. That figure went stale in three consecutive rounds (each round that
 * added assertions carried the previous round's number forward by hand), and round 4 shipped a
 * clause asserting the figure came straight from the command's own output in the same commit that
 * carried it over by hand. A number each future round has to remember to re-derive is a liability
 * in a file whose subject is derived-not-hardcoded expectations. What the CI-wiring argument needs
 * is the qualitative claim above — both files come out of the same default-config glob — and that
 * is re-checkable by running the command printed above. The measured figures stay in the
 * verification document's dated transcript sections, where they are historical by construction.
 *
 * Values-free: reads only repo-tracked script/manifest text and asserts on token-name sets.
 */
import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  allVitestInvocations,
  allVitestTokenLines,
  allVitestTokens,
  execLogicalLine,
  logicalLines,
  logicalLinesWithLineNumbers,
  stripTrailingErrorGuard,
  tokensOf,
} from '../../../../scripts/ops/required-web-lane-exec-block.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(HERE, '..', '..', '..', '..')
const LANE_SCRIPT = join(REPO_ROOT, 'apps', 'web', 'scripts', 'run-required-web-tests.sh')
const MANIFEST_PATH = join(REPO_ROOT, 'apps', 'web', 'scripts', 'run-required-web-tests.tokens')
const GITATTRIBUTES = join(REPO_ROOT, '.gitattributes')
const SHAPE_GUARD_PATH = join(REPO_ROOT, 'packages', 'core-backend', 'tests', 'unit', 'required-web-lane-registration-shape.test.ts')
/** ROUND 3 (r2-P3-2) — the third copy of the parser, previously never opened by this test. */
const TOKEN_SET_DIFF_PATH = join(REPO_ROOT, 'scripts', 'ops', 'required-web-lane-token-set-diff.mjs')

const RELATIVE_MANIFEST = 'apps/web/scripts/run-required-web-tests.tokens'
const RELATIVE_LANE_SCRIPT = 'apps/web/scripts/run-required-web-tests.sh'

/** Blank lines and `#`-prefixed provenance/comment lines are not tokens (P3-5, round-1 gate review). */
function manifestTokens(raw: string): string[] {
  return raw
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith('#'))
}

/** Both directions of the set diff, each sorted for a stable, readable failure message. */
function diffSets(active: Set<string>, manifest: Set<string>): { missingFromActive: string[]; extraInActive: string[] } {
  const missingFromActive = [...manifest].filter((t) => !active.has(t)).sort()
  const extraInActive = [...active].filter((t) => !manifest.has(t)).sort()
  return { missingFromActive, extraInActive }
}

/**
 * A token recorded in the manifest but produced by no gating invocation is, by construction, on NO
 * current source line — there is nothing to point at. Name the lines that WERE scanned instead, so
 * the message is honest about what it can and cannot localize (see the class-level header note).
 */
function describeMissing(tokens: string[], scannedLines: number[]): string {
  return `${tokens.length} token(s) recorded in ${RELATIVE_MANIFEST} are produced by NONE of the `
    + `${scannedLines.length} gating \`vitest run\` invocations in ${RELATIVE_LANE_SCRIPT} (lines: `
    + `${scannedLines.join(', ')}) — they silently stopped running in the required web lane: ${tokens.join(' ')}`
}

/** A token still produced by a gating invocation DOES have a current line — name it. */
function describeExtra(tokens: string[], lineMap: Map<string, number[]>): string {
  const withLines = tokens.map((t) => {
    const lines = lineMap.get(t)
    return lines && lines.length ? `${t}@line(s) ${lines.join(',')}` : t
  })
  return `${tokens.length} token(s) are produced by a gating \`vitest run\` invocation in `
    + `${RELATIVE_LANE_SCRIPT} but are not recorded in ${RELATIVE_MANIFEST} — run `
    + `\`node scripts/ops/required-web-lane-token-manifest.mjs --write\` and commit the result in `
    + `the SAME PR that added them: ${withLines.join(' ')}`
}

/**
 * P3-6 (round-1 gate review) — cross-copy agreement.
 *
 * `logicalLines`/`execLogicalLine`/`tokensOf` in `required-web-lane-exec-block.mjs` are meant to
 * stay algorithmically equivalent to `required-web-lane-registration-shape.test.ts`'s own copy
 * (that file cannot be safely `import`ed here — see its neighbour module's header for why — so its
 * exports are never called directly by this file).
 *
 * ROUND 4 (2026-09-22, merge-train dry-run v3 gate finding G1) — round 1 checked this as SOURCE
 * TEXT, not behaviour, on the stated reasoning that a source-text check is strictly STRONGER than
 * a behavioural one on a finite fixture set. That reasoning is correct as far as it goes, but it
 * bought soundness by being MORE FRAGILE than the property this guard actually needs: the dry-run
 * measured that `required-web-lane-registration-shape.test.ts` can be refactored into a
 * `logicalLinesWithLineNumbers()` helper plus a one-line `logicalLines()` wrapper around it — same
 * input/output behaviour on every fixture below, zero bytes in common with the old inline body —
 * and the byte-for-byte check reds on that refactor alone, with no actual drift. A guard that reds
 * on a same-behaviour refactor trains its own maintainers to treat its failures as noise, which
 * is a worse outcome than the narrower fixture coverage this round accepts in exchange.
 *
 * So: this round extracts the sibling's function source the same way as before (still via
 * `extractExportedFunctionSource`/`extractPlainFunctionSource` below — importing the sibling files
 * directly is still unsafe, see their own headers), then MATERIALIZES it into a real, callable
 * function (`materialize()` below) and calls it on the shared FIXTURES battery of named fixtures — comment
 * lines, backslash continuations, a `#` line inside the block region, a dead block after `exec`,
 * a blank line, and a bare single line — asserting the OUTPUT is byte-for-byte identical to this
 * file's own copy, not the source. Where a sibling exports a differently-shaped function (e.g.
 * `logicalLinesWithLineNumbers`, which this file's copy did not have before this same round —
 * see `required-web-lane-exec-block.mjs`'s ROUND 4 note), the comparison is written against that
 * shape directly (an "adapter", not a second copy of the parser) rather than reduced back to text.
 *
 * One case is DELIBERATELY EXCLUDED from the "must agree" fixture set: a `#` line landing INSIDE
 * an active backslash continuation. `logicalLinesWithLineNumbers()`'s own doc comment (this round)
 * states plainly that this file's fold order is NOT bash-exact for that shape, and at least one
 * sibling copy may already have (or later gain) a bash-exact fix for exactly that case — asserting
 * equality there would pin a coincidence, not a contract. See the fixture list below for the
 * measured proof that this specific shape — and only this shape — actually diverges.
 */
function extractExportedFunctionSource(fileText: string, functionName: string): string {
  const marker = new RegExp(`export function ${functionName}\\([^)]*\\)[^{]*\\{`)
  const head = marker.exec(fileText)
  if (!head) {
    throw new Error(`could not find "export function ${functionName}(" in ${SHAPE_GUARD_PATH}`)
  }
  const braceStart = head.index + head[0].length - 1
  let depth = 0
  let i = braceStart
  for (; i < fileText.length; i += 1) {
    if (fileText[i] === '{') depth += 1
    else if (fileText[i] === '}') {
      depth -= 1
      if (depth === 0) {
        i += 1
        break
      }
    }
  }
  return fileText.slice(head.index, i)
}

/**
 * ROUND 3 (r2-P3-2) — same brace-matched extraction as `extractExportedFunctionSource` above, but
 * for a PLAIN (non-`export`ed) top-level function declaration, as `required-web-lane-
 * token-set-diff.mjs`'s copies are (that script is a standalone CLI, not a module — nothing there
 * needs `export`, and importing it would run its top-level `process.exit`, see the design doc §4).
 */
function extractPlainFunctionSource(fileText: string, functionName: string, filePath: string): string {
  const marker = new RegExp(`function ${functionName}\\([^)]*\\)[^{]*\\{`)
  const head = marker.exec(fileText)
  if (!head) {
    throw new Error(`could not find "function ${functionName}(" in ${filePath}`)
  }
  const braceStart = head.index + head[0].length - 1
  let depth = 0
  let i = braceStart
  for (; i < fileText.length; i += 1) {
    if (fileText[i] === '{') depth += 1
    else if (fileText[i] === '}') {
      depth -= 1
      if (depth === 0) {
        i += 1
        break
      }
    }
  }
  return fileText.slice(head.index, i)
}

/**
 * ROUND 4 — strip the leading `export` keyword and TypeScript parameter/return type annotations
 * from an extracted function source, so it becomes plain, executable JavaScript.
 *
 * Deliberately does NOT collapse whitespace (unlike the retired text-comparison normalizer this
 * replaces): every copy of this parser relies on automatic semicolon insertion at line breaks
 * (no source has a single semicolon in it), so joining statements onto one line would itself
 * introduce a syntax error having nothing to do with the algorithms being compared.
 *
 * Deliberately NOT a single blanket `:\s*Ident` strip either — a first attempt at that also ate
 * the `:` in `continued ? a : b` ternaries (there is one in `logicalLines()`'s fold loop), in `//`
 * comment prose ("nothing after it: keep what we have" -> "nothing after it what we have"), AND —
 * the one that actually breaks at runtime instead of just reading oddly — in an object literal's
 * `key: value` inside the function BODY (`{ line: body, lineNumber: bufStart }` in
 * `logicalLinesWithLineNumbers()`'s fold loop: a global `[(,]identifier:\s*TYPE` pattern matches
 * `, lineNumber: bufStart` too, because `bufStart` is itself a valid bare identifier — indistinguishable
 * from a type name by shape alone — and strips it down to the shorthand `{ line: body, lineNumber }`,
 * which then throws `lineNumber is not defined`). All three measured to actually happen, not
 * hypothesized. The fix: comments are dropped first (never executed, so dropping them cannot
 * change behaviour), then the source is split at its OWN first top-level `{` — the parameter-list
 * and return-type patterns are applied ONLY to the header before that brace (where a `(`/`,`-then-
 * identifier-then-colon can only ever be a parameter, never an object literal), while the
 * `let`/`const` variable-annotation pattern is applied to the whole thing (safe everywhere, since
 * `let`/`const` never precedes an object-literal key).
 */
function stripTypesForEval(src: string): string {
  const TYPE = '[A-Za-z_$][\\w$]*(?:\\[\\])?(?:\\s*\\|\\s*[A-Za-z_$][\\w$]*(?:\\[\\])?)*'
  const withoutComments = src.replace(/^export\s+/, '').replace(/\/\/[^\n]*/g, '')
  const headerEnd = withoutComments.indexOf('{')
  const header = headerEnd === -1 ? withoutComments : withoutComments.slice(0, headerEnd + 1)
  const rest = headerEnd === -1 ? '' : withoutComments.slice(headerEnd + 1)
  const strippedHeader = header
    .replace(new RegExp(`\\)\\s*:\\s*${TYPE}\\s*\\{$`), ') {')
    .replace(new RegExp(`([(,]\\s*[A-Za-z_$][\\w$]*)\\s*:\\s*${TYPE}`, 'g'), '$1')
  const strippedRest = rest.replace(new RegExp(`\\b(let|const)(\\s+[A-Za-z_$][\\w$]*)\\s*:\\s*${TYPE}`, 'g'), '$1$2')
  return strippedHeader + strippedRest
}

/**
 * Materialize a set of extracted (regex brace-matched) function sources into real, callable
 * functions, ALL DECLARED IN THE SAME SCOPE — see the P3-6 class comment above for why cross-copy
 * agreement is checked this way (behaviour, not text) as of ROUND 4. One scope, not one `new
 * Function` per source, because `execLogicalLine()` calls `logicalLines()` internally: materializing
 * it alone leaves that call unresolved (`logicalLines is not defined`) the moment it is invoked,
 * even though the extraction/stripping both otherwise succeeded — this was caught empirically, not
 * anticipated. `names` must be exactly the declared top-level function names inside `sources`.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- deliberately untyped: materializes
// arbitrary sibling-file source, whose static type this file cannot see.
function materializeAll<T extends Record<string, (...args: any[]) => unknown>>(sources: string[], names: string[]): T {
  const body = sources.map(stripTypesForEval).join('\n')
  // eslint-disable-next-line no-new-func -- deliberate: this is the whole point of ROUND 4 — turn
  // extracted, type-stripped function bodies into callables so the guard compares OUTPUT on a
  // fixture battery, not source bytes.
  const factory = new Function(`'use strict';\n${body}\nreturn { ${names.join(', ')} };`)
  return factory() as T
}

/**
 * ROUND 4 — the shared FIXTURES battery every cross-copy behavioural comparison below runs. Each is a
 * complete, syntactically well-formed script fragment carrying exactly one `exec npx vitest run`
 * logical line, so `logicalLines`, `execLogicalLine`, and `tokensOf(execLogicalLine(...))` are all
 * exercisable on every entry uniformly.
 *
 * `commentInsideBlockOutsideContinuation` is the "in-block `#` line" case — the comment sits among
 * the script's other gating lines, but BETWEEN two already-terminated logical lines, never inside
 * an active continuation. That placement is the one the sibling's own doc comment guarantees is
 * unchanged behaviour ("a `#`-prefixed physical line encountered OUTSIDE any continuation ...
 * exactly as before"); a `#` line landing INSIDE a continuation is a separately documented,
 * excluded divergence (see the P3-6 class comment) and is deliberately not one of these fixtures.
 *
 * ROUND 5 (r4-P3-2) — `indentedCommentBeforeBlock` / `indentedCommentInsideBlockOutsideContinuation`
 * added. Each round-4 fixture put its `#` at column 0, so a copy that narrowed its comment
 * predicate from `^\s*#` to `^#` — a real behaviour change: the indented line stops being skipped
 * and folds into the logical-line stream instead — stayed green across the whole battery. The r4
 * gate measured exactly that mutation (applied to `required-web-lane-token-set-diff.mjs`) passing.
 * These two place an indented `#` on both sides of the block boundary the fixtures above already
 * distinguish, so the narrowed predicate now diverges on the battery and reds. The lane script has
 * no indented `#` among its gating lines today, which is why this was latent rather than live.
 */
const FIXTURES: Record<string, string> = {
  singleLineNoContinuation: 'exec npx vitest run foo bar --reporter=dot\n',
  continuation: 'exec npx vitest run \\\n  foo \\\n  bar \\\n  --reporter=dot\n',
  commentBeforeBlock: '# a leading comment, not part of any continuation\nexec npx vitest run \\\n  foo \\\n  --reporter=dot\n',
  commentInsideBlockOutsideContinuation: 'npx vitest run alpha --reporter=dot\n# a comment between two SEPARATE, already-terminated logical lines\nexec npx vitest run \\\n  beta \\\n  --reporter=dot\n',
  deadBlockAfterExec: 'exec npx vitest run \\\n  gamma \\\n  --reporter=dot\n\n# a dead comment after the exec block — nothing gates on it\necho unreachable\n',
  blankLineBeforeBlock: 'npx vitest run one --reporter=dot\n\nexec npx vitest run \\\n  two \\\n  --reporter=dot\n',
  indentedCommentBeforeBlock: '  # an INDENTED leading comment, not part of any continuation\nexec npx vitest run \\\n  foo \\\n  --reporter=dot\n',
  indentedCommentInsideBlockOutsideContinuation: 'npx vitest run alpha --reporter=dot\n\t# an INDENTED (tab) comment between two SEPARATE, already-terminated logical lines\nexec npx vitest run \\\n  beta \\\n  --reporter=dot\n',
}

/**
 * The FIXTURES key set, defined exactly once. Both cross-copy assertions below compare
 * `Object.keys(FIXTURES)` against this instead of each carrying its own literal array — a rewritten
 * literal that drifts from FIXTURES itself would otherwise still read as "count and names defined
 * once" while silently being defined twice (S-7 gate P3-B).
 */
const EXPECTED_FIXTURE_KEYS = [
  'singleLineNoContinuation',
  'continuation',
  'commentBeforeBlock',
  'commentInsideBlockOutsideContinuation',
  'deadBlockAfterExec',
  'blankLineBeforeBlock',
  'indentedCommentBeforeBlock',
  'indentedCommentInsideBlockOutsideContinuation',
] as const

/**
 * NIT-3 (round-1 gate review) — a derived sanity floor instead of a hardcoded magic number,
 * factored out so the "does it actually red on the degenerate case" probe below calls the exact
 * same logic the real assertion uses, rather than re-deriving it and risking the two drifting.
 */
function assertNeitherCollapsesRelativeToTheOther(activeCount: number, manifestCount: number): void {
  expect(
    activeCount,
    'the active token collection must not be empty or drastically smaller than the manifest — a '
      + 'broken parse shows up as a large asymmetric drop, not merely "smaller than before", so this '
      + 'floor is derived from the manifest\'s own size rather than a hardcoded constant that would '
      + 'spuriously red if the lane legitimately shrinks',
  ).toBeGreaterThan(manifestCount / 2)
  expect(
    manifestCount,
    'the manifest must not be empty or drastically smaller than the active token collection',
  ).toBeGreaterThan(activeCount / 2)
}

describe('required web lane token manifest — set equality', () => {
  const scriptSrc = readFileSync(LANE_SCRIPT, 'utf8')
  const activeSet = allVitestTokens(scriptSrc)
  const active = [...activeSet]
  const activeLineMap = allVitestTokenLines(scriptSrc)
  const invocationLines = allVitestInvocations(scriptSrc).map((l) => l.startLine)

  const manifestRaw = readFileSync(MANIFEST_PATH, 'utf8')
  const manifest = manifestTokens(manifestRaw)
  const manifestSet = new Set(manifest)

  it('sanity: neither the active token collection nor the manifest collapses to near-empty relative to the other (scan negative control)', () => {
    assertNeitherCollapsesRelativeToTheOther(active.length, manifest.length)
  })

  it('the manifest has no duplicate TOKEN lines (hygiene: --write always emits a de-duplicated Set; header/comment lines are excluded from this count, not counted as duplicates of each other)', () => {
    expect(manifestSet.size, 'a duplicate manifest line is dead weight, not itself a safety gap (set semantics absorb it) — flagged so drift gets cleaned by re-running --write').toBe(manifest.length)
  })

  it('every manifest token is still produced by at least one of the 19 gating invocations (nothing silently dropped from the lane)', () => {
    const { missingFromActive } = diffSets(activeSet, manifestSet)
    expect(missingFromActive, missingFromActive.length ? describeMissing(missingFromActive, invocationLines) : '').toEqual([])
  })

  it('every token produced by a gating invocation is recorded in the manifest (nothing silently added without updating it) — the failure names the offending source line(s)', () => {
    const { extraInActive } = diffSets(activeSet, manifestSet)
    expect(extraInActive, extraInActive.length ? describeExtra(extraInActive, activeLineMap) : '').toEqual([])
  })

  it('the manifest is pinned in .gitattributes as `text eol=lf merge=union`, same as the script it mirrors', () => {
    const attrs = readFileSync(GITATTRIBUTES, 'utf8')
    const rule = attrs
      .split('\n')
      .map((line) => line.replace(/\r$/, '').trim())
      .find((line) => line.startsWith('apps/web/scripts/run-required-web-tests.tokens '))
    expect(rule, '.gitattributes must pin the token manifest').toBeTruthy()
    expect(rule).toContain('eol=lf')
    expect(rule).toContain('merge=union')
  })

  it('r2-NIT-3: the committed manifest\'s token lines are sorted case-insensitively, same as the exec block\'s sibling assertion', () => {
    const caseInsensitive = (a: string, b: string) => {
      const la = a.toLowerCase()
      const lb = b.toLowerCase()
      if (la !== lb) return la < lb ? -1 : 1
      return a < b ? -1 : a > b ? 1 : 0
    }
    const sorted = [...manifest].sort(caseInsensitive)
    expect(
      manifest,
      'the manifest is harmless-but-not-hard-failing when unsorted (set semantics absorb it), but '
        + '`--write` always emits sorted output and a `merge=union` resolution can silently leave it '
        + 'unsorted with nothing else noticing — pinned so drift gets cleaned by re-running --write',
    ).toEqual(sorted)
  })

  it('r4-G1: cross-copy BEHAVIOURAL agreement — logicalLines/execLogicalLine/tokensOf produce byte-identical output (not byte-identical source) to the shape guard\'s own copy, across the shared FIXTURES battery (P3-6, rewritten round 4)', () => {
    const shapeGuardSrc = readFileSync(SHAPE_GUARD_PATH, 'utf8')
    // Materialized TOGETHER, one scope: execLogicalLine() calls logicalLines() internally, so the
    // two must be declared side by side for that call to resolve (see materializeAll's own note).
    // `logicalLines`'s own body may itself call `logicalLinesWithLineNumbers` (true as of the
    // sibling refactor this round exists to tolerate — see the class comment) — include it in the
    // SAME materialized scope whenever the sibling exports it, or that internal call is left
    // unresolved (measured: `logicalLinesWithLineNumbers is not defined`), even though extraction
    // of the three functions actually under test succeeded on its own.
    const sourcesToMaterialize = [
      extractExportedFunctionSource(shapeGuardSrc, 'logicalLines'),
      extractExportedFunctionSource(shapeGuardSrc, 'execLogicalLine'),
      extractExportedFunctionSource(shapeGuardSrc, 'tokensOf'),
    ]
    const namesToMaterialize = ['logicalLines', 'execLogicalLine', 'tokensOf']
    if (/export function logicalLinesWithLineNumbers\(/.test(shapeGuardSrc)) {
      sourcesToMaterialize.push(extractExportedFunctionSource(shapeGuardSrc, 'logicalLinesWithLineNumbers'))
      namesToMaterialize.push('logicalLinesWithLineNumbers')
    }
    const { logicalLines: theirLogicalLines, execLogicalLine: theirExecLogicalLine, tokensOf: theirTokensOf } = materializeAll<{
      logicalLines: (scriptSrc: string) => string[]
      execLogicalLine: (scriptSrc: string) => string
      tokensOf: (logicalLine: string) => string[]
    }>(sourcesToMaterialize, namesToMaterialize)

    expect(
      Object.keys(FIXTURES).sort(),
      'exact FIXTURES key set — count and names defined once',
    ).toEqual([...EXPECTED_FIXTURE_KEYS].sort())
    expect(
      FIXTURES.indentedCommentBeforeBlock,
      'load-bearing property this fixture exists to pin: the leading `#` stays INDENTED — '
        + 'de-indenting it (key name and count unchanged) must fail this assertion',
    ).toMatch(/^[ \t]+#/m)
    expect(
      FIXTURES.indentedCommentInsideBlockOutsideContinuation,
      'load-bearing property this fixture exists to pin: the in-block `#` line stays INDENTED — '
        + 'de-indenting it (key name and count unchanged) must fail this assertion',
    ).toMatch(/^[ \t]+#/m)

    for (const [fixtureName, scriptSrc] of Object.entries(FIXTURES)) {
      expect(
        theirLogicalLines(scriptSrc),
        `[${fixtureName}] scripts/ops/required-web-lane-exec-block.mjs's logicalLines() output `
          + `diverged from required-web-lane-registration-shape.test.ts's copy on this fixture — a `
          + `bug fixed in one and not the other is now invisible to the guard that is supposed to `
          + `catch drift. Update both.`,
      ).toEqual(logicalLines(scriptSrc))

      const ourExec = execLogicalLine(scriptSrc)
      expect(
        theirExecLogicalLine(scriptSrc),
        `[${fixtureName}] execLogicalLine() output diverged from the shape guard's copy`,
      ).toBe(ourExec)
      expect(
        theirTokensOf(ourExec),
        `[${fixtureName}] tokensOf() output diverged from the shape guard's copy`,
      ).toEqual(tokensOf(ourExec))
    }
  })

  it('r4-G1 (rewritten round 5): logicalLinesWithLineNumbers() agrees with BOTH sibling copies on the fold, and its start-line bookkeeping is anchored to the fixture text itself — self-contained, so it does real work whether or not the sibling has grown the same export', () => {
    // ROUND 5 (r4-P3-1) — round 4 wrote this as `if (!siblingExportsIt) { expect(false).toBe(false);
    // return }`. On THIS branch the sibling is byte-identical to origin/main and carries no such
    // export, so the body was skipped and the test was a tautology at the reviewed head: the r4
    // gate measured a sibling mutation reddening 2 tests on the dry-run tree and 1 here, the
    // missing one being this test. Restructured so the comparison is driven by the FIXTURES
    // battery against the two sibling copies that do exist, plus a line-number anchor taken from
    // the fixture's own text — none of which depends on a sibling refactor landing first. The
    // full (line + lineNumber) cross-copy comparison is kept, and simply widens to it when the
    // sibling does grow the export.
    const shapeGuardSrc = readFileSync(SHAPE_GUARD_PATH, 'utf8')
    const diffSrc = readFileSync(TOKEN_SET_DIFF_PATH, 'utf8')
    const siblingExportsLineNumbers = /export function logicalLinesWithLineNumbers\(/.test(shapeGuardSrc)

    // Copy 2 (the shape guard), materialized in ONE scope for the reason `materializeAll`'s header
    // records: on a tree where the sibling HAS the wrapper, its `logicalLines()` is implemented in
    // terms of it, so materializing either name alone leaves the other unresolved at call time.
    const shapeSources = [extractExportedFunctionSource(shapeGuardSrc, 'logicalLines')]
    const shapeNames = ['logicalLines']
    if (siblingExportsLineNumbers) {
      shapeSources.push(extractExportedFunctionSource(shapeGuardSrc, 'logicalLinesWithLineNumbers'))
      shapeNames.push('logicalLinesWithLineNumbers')
    }
    const shapeCopy = materializeAll<{
      logicalLines: (scriptSrc: string) => string[]
      logicalLinesWithLineNumbers?: (scriptSrc: string) => Array<{ line: string; lineNumber: number }>
    }>(shapeSources, shapeNames)

    // Copy 3 (the token-set-diff script) — a standalone CLI whose copies are plain, non-exported
    // declarations, so it needs the plain extractor rather than the `export function` one.
    const diffCopy = materializeAll<{ logicalLines: (scriptSrc: string) => string[] }>(
      [extractPlainFunctionSource(diffSrc, 'logicalLines', TOKEN_SET_DIFF_PATH)],
      ['logicalLines'],
    )

    expect(
      Object.keys(FIXTURES).sort(),
      'exact FIXTURES key set — count and names defined once',
    ).toEqual([...EXPECTED_FIXTURE_KEYS].sort())
    expect(
      FIXTURES.indentedCommentBeforeBlock,
      'load-bearing property this fixture exists to pin: the leading `#` stays INDENTED — '
        + 'de-indenting it (key name and count unchanged) must fail this assertion',
    ).toMatch(/^[ \t]+#/m)
    expect(
      FIXTURES.indentedCommentInsideBlockOutsideContinuation,
      'load-bearing property this fixture exists to pin: the in-block `#` line stays INDENTED — '
        + 'de-indenting it (key name and count unchanged) must fail this assertion',
    ).toMatch(/^[ \t]+#/m)

    for (const [fixtureName, scriptSrc] of Object.entries(FIXTURES)) {
      const mapped = logicalLinesWithLineNumbers(scriptSrc)
      const projected = mapped.map((entry) => entry.line)

      // (a) THE FOLD HALF, three copies. The wrapper's projection must match this file's own
      // `logicalLines()` and both sibling copies' on this fixture.
      expect(
        projected,
        `[${fixtureName}] logicalLinesWithLineNumbers()'s folded projection diverged from this `
          + `file's own logicalLines() — the wrapper and the function it backs disagree`,
      ).toEqual(logicalLines(scriptSrc))
      expect(
        projected,
        `[${fixtureName}] logicalLinesWithLineNumbers()'s folded projection diverged from `
          + `required-web-lane-registration-shape.test.ts's logicalLines() copy`,
      ).toEqual(shapeCopy.logicalLines(scriptSrc))
      expect(
        projected,
        `[${fixtureName}] logicalLinesWithLineNumbers()'s folded projection diverged from `
          + `required-web-lane-token-set-diff.mjs's logicalLines() copy`,
      ).toEqual(diffCopy.logicalLines(scriptSrc))

      // (b) THE LINE-NUMBER HALF, anchored on the fixture TEXT rather than on any copy of the
      // parser. Each fixture carries exactly one `exec npx vitest run` logical line (see the
      // FIXTURES header), so the physical index of its header is findable by a raw scan of the
      // fixture's own lines — a derivation no fold implementation participates in. An off-by-one
      // in the start-line bookkeeping moves the recorded number off that index and reds here.
      const physicalLines = scriptSrc.split('\n')
      const execPhysicalIdx = physicalLines.findIndex((line) => /^\s*exec\s+npx\s+vitest\s+run\b/.test(line))
      expect(execPhysicalIdx, `[${fixtureName}] fixture sanity: the fixture must carry an exec header physical line`).toBeGreaterThan(-1)
      const execEntry = mapped.find((entry) => /^exec\s+npx\s+vitest\s+run\b/.test(entry.line))
      expect(execEntry, `[${fixtureName}] fixture sanity: the folded stream must carry an exec logical line`).toBeTruthy()
      expect(
        execEntry!.lineNumber,
        `[${fixtureName}] the exec logical line's recorded start line disagrees with the physical `
          + `index of the exec header in the fixture's own text — the fold's start-line `
          + `bookkeeping has drifted off by that difference`,
      ).toBe(execPhysicalIdx + 1)

      // (c) Where the sibling HAS grown the same export, the full (line + lineNumber) outputs must
      // be byte-identical — round 4's comparison, kept intact and live on such a tree.
      if (shapeCopy.logicalLinesWithLineNumbers) {
        expect(
          shapeCopy.logicalLinesWithLineNumbers(scriptSrc),
          `[${fixtureName}] logicalLinesWithLineNumbers() (folded result + line-number mapping) `
            + `diverged from the shape guard's copy`,
        ).toEqual(mapped)
      }
    }
  })

  it('r4-G1 fixture sanity: the excluded in-continuation `#` shape actually diverges between the two documented fold orders — proves the exclusion is load-bearing, not a dodge', () => {
    // Not part of FIXTURES / the "must agree" set on purpose (see the P3-6 class comment). Bash
    // terminates the logical line right at a `#` encountered mid-continuation; a naive
    // strip-comments-then-fold pass (this file's algorithm) instead glues both sides together.
    const inContinuation = 'exec npx vitest run \\\n  foo \\\n# a comment INSIDE the continuation\n  bar \\\n  --reporter=dot\n'
    // Trailing '' is the fold's own blank-line-at-EOF entry (the source ends in "\n"), present
    // regardless of the comment-placement question this fixture is about — not part of the point.
    expect(logicalLines(inContinuation)).toEqual(['exec npx vitest run foo bar --reporter=dot', ''])
  })

  it('r2-P3-2: cross-copy BEHAVIOURAL agreement covers the THIRD copy too — logicalLines/tokensOf produce byte-identical output to required-web-lane-token-set-diff.mjs across the shared FIXTURES battery; execLogicalLine there diverges ONLY by its documented extra `label` parameter and message prefix (rewritten round 4)', () => {
    const diffSrc = readFileSync(TOKEN_SET_DIFF_PATH, 'utf8')
    // Materialized TOGETHER for the same reason as the shape-guard copy above: this file's
    // execLogicalLine() also calls its own logicalLines() internally.
    const { logicalLines: diffLogicalLines, tokensOf: diffTokensOf, execLogicalLine: diffExecLogicalLineRaw } = materializeAll<{
      logicalLines: (scriptSrc: string) => string[]
      tokensOf: (logicalLine: string) => string[]
      execLogicalLine: (scriptSrc: string, label: string) => string
    }>(
      [
        extractPlainFunctionSource(diffSrc, 'logicalLines', TOKEN_SET_DIFF_PATH),
        extractPlainFunctionSource(diffSrc, 'tokensOf', TOKEN_SET_DIFF_PATH),
        extractPlainFunctionSource(diffSrc, 'execLogicalLine', TOKEN_SET_DIFF_PATH),
      ],
      ['logicalLines', 'tokensOf', 'execLogicalLine'],
    )

    // execLogicalLine's third copy takes an extra `label` argument, used only in its thrown
    // message — a documented, deliberate divergence (design doc §4's round-3 addendum). Fixture
    // sanity below still proves that documented divergence is actually present verbatim, so an
    // UNDOCUMENTED further divergence (e.g. the label affecting the RETURN value, not just a
    // throw) would still be caught by the byte-identical-return-value comparison in the loop.
    expect(
      extractPlainFunctionSource(diffSrc, 'execLogicalLine', TOKEN_SET_DIFF_PATH),
      'fixture sanity: the documented `label` parameter must still be present verbatim in '
        + 'required-web-lane-token-set-diff.mjs, or this test is comparing two copies that already '
        + 'silently converged',
    ).toContain('function execLogicalLine(scriptSrc, label)')

    for (const [fixtureName, scriptSrc] of Object.entries(FIXTURES)) {
      expect(
        diffLogicalLines(scriptSrc),
        `[${fixtureName}] scripts/ops/required-web-lane-exec-block.mjs's logicalLines() output `
          + `diverged from required-web-lane-token-set-diff.mjs's copy (the third copy of this `
          + `parser) — update both.`,
      ).toEqual(logicalLines(scriptSrc))

      const ourExec = execLogicalLine(scriptSrc)
      expect(
        diffExecLogicalLineRaw(scriptSrc, 'fixture-label'),
        `[${fixtureName}] execLogicalLine() output diverged from the token-set-diff copy by more `
          + `than the documented label prefix`,
      ).toBe(ourExec)
      expect(
        diffTokensOf(ourExec),
        `[${fixtureName}] tokensOf() output diverged from the token-set-diff copy`,
      ).toEqual(tokensOf(ourExec))
    }
  })
})

describe('required web lane token manifest — stripTrailingErrorGuard()', () => {
  const scriptSrc = readFileSync(LANE_SCRIPT, 'utf8')

  it('strips the exact `|| exit $?` tail carried by the early gating lines that have it', () => {
    expect(stripTrailingErrorGuard('npx vitest run foo bar --reporter=dot || exit $?')).toBe('npx vitest run foo bar --reporter=dot')
  })

  it('is a no-op on a line without the tail, including the final exec line\'s form', () => {
    expect(stripTrailingErrorGuard('npx vitest run foo --reporter=dot')).toBe('npx vitest run foo --reporter=dot')
    expect(stripTrailingErrorGuard('exec npx vitest run a b c --reporter=dot')).toBe('exec npx vitest run a b c --reporter=dot')
  })

  it('does NOT touch a positional token literally named "exit" that is not part of the trailing idiom (anchored at end-of-string, not a bare-word replace)', () => {
    expect(stripTrailingErrorGuard('npx vitest run exit --reporter=dot')).toBe('npx vitest run exit --reporter=dot')
  })

  it('applied to the REAL gating invocations that carry the tail, tokenizes clean of `||`/`exit`/`$?` — none of the three survive as if they were vitest positional filters', () => {
    // ROUND 5 (r4-P2-1) — round 4 selected these two invocations by hardcoded start line
    // (`startLine === 1180` / `=== 1183`). Those literals track nothing: an edit anywhere above
    // them shifts the real lines, `find()` returns undefined, and the test reds on its own fixture
    // sanity for a reason that has nothing to do with the tail-stripping it is about (the r4 gate
    // measured exactly that: a 40-line insert after the shebang turned this test red). Selected by
    // the PROPERTY under test instead — the gating invocations whose text the stripper changes —
    // which follows the file wherever those lines move to.
    const invocations = allVitestInvocations(scriptSrc)
    const guardedInvocations = invocations.filter((inv) => stripTrailingErrorGuard(inv.text) !== inv.text)
    expect(
      guardedInvocations.length,
      'fixture sanity: the lane script must still carry at least one `|| exit $?`-tailed gating invocation for this test to be about anything',
    ).toBeGreaterThan(0)
    for (const inv of guardedInvocations) {
      const tokens = tokensOf(stripTrailingErrorGuard(inv.text))
      for (const garbage of ['||', 'exit', '$?']) {
        expect(
          tokens,
          `the gating invocation starting at line ${inv.startLine} must not tokenize the shell control operator/variable "${garbage}"`,
        ).not.toContain(garbage)
      }
    }
    // Positive side: stripping does not merely empty the line. The single-token tailed invocation
    // still yields its real token — located by that token, not by a line number.
    const punchOutcome = guardedInvocations.find((inv) => tokensOf(stripTrailingErrorGuard(inv.text)).includes('attendance-punch-outcome'))
    expect(
      punchOutcome,
      'fixture sanity: a `|| exit $?`-tailed gating invocation for attendance-punch-outcome must still exist for the positive side of this assertion to mean anything',
    ).toBeTruthy()
    expect(tokensOf(stripTrailingErrorGuard(punchOutcome!.text))).toEqual(['attendance-punch-outcome'])
  })
})

/**
 * MUTATION SELF-PROOF (2026-09-22, extended round 2 2026-09-22) — same discipline as the shape
 * guard's own self-proof section: each assertion above is only worth its runtime if it actually
 * reds on the damage it claims to catch. These mutate IN-MEMORY COPIES of the real script text /
 * token sets — the files on disk are never touched — and assert the corresponding detector fires,
 * or (for the reorder cases) deliberately does not.
 *
 * M1-M4 exercise the FINAL EXEC BLOCK (round 1's original scope). M5-M7 exercise one of the 18
 * EARLIER lines — the discriminating cases for P1-1 option (a): under option (b) (rename/rescope
 * to "final exec block only"), none of M5/M6 would be in the manifest's scope to red on at all.
 */
describe('required web lane token manifest — mutation self-proof', () => {
  const scriptSrc = readFileSync(LANE_SCRIPT, 'utf8')
  const manifestRaw = readFileSync(MANIFEST_PATH, 'utf8')
  const manifest = manifestTokens(manifestRaw)
  const manifestSet = new Set(manifest)

  it('baseline: the real active token set (union of all 19 gating invocations) and the real manifest set are equal', () => {
    const activeSet = allVitestTokens(scriptSrc)
    const { missingFromActive, extraInActive } = diffSets(activeSet, manifestSet)
    expect(missingFromActive).toEqual([])
    expect(extraInActive).toEqual([])
  })

  it('M1 a token deleted from the FINAL EXEC BLOCK -> "missing from active" reds, naming it (round-1 case, unchanged)', () => {
    const victimLine = '  amountAutoSum \\'
    const lines = scriptSrc.split('\n')
    const idx = lines.indexOf(victimLine)
    expect(idx, 'fixture sanity: exec block must still carry this exact physical line for amountAutoSum').toBeGreaterThan(-1)
    const mutated = [...lines.slice(0, idx), ...lines.slice(idx + 1)].join('\n')

    const activeSet = allVitestTokens(mutated)
    expect(activeSet.has('amountAutoSum')).toBe(false)
    const { missingFromActive, extraInActive } = diffSets(activeSet, manifestSet)
    expect(missingFromActive, 'M1 must be caught by the "nothing silently dropped" assertion').toContain('amountAutoSum')
    expect(extraInActive, 'M1 is a drop, not an addition — the other direction must stay clean').toEqual([])
  })

  it('M2 a token added to the FINAL EXEC BLOCK that is not in the manifest -> "extra in active" reds, naming it and its line', () => {
    const anchorLine = '  amountAutoSum \\'
    const injected = '  __h6_round2_exec_block_add_probe__ \\'
    const lines = scriptSrc.split('\n')
    const idx = lines.indexOf(anchorLine)
    expect(idx, 'fixture sanity').toBeGreaterThan(-1)
    const mutated = [...lines.slice(0, idx + 1), injected, ...lines.slice(idx + 1)].join('\n')

    const activeSet = allVitestTokens(mutated)
    const lineMap = allVitestTokenLines(mutated)
    const { missingFromActive, extraInActive } = diffSets(activeSet, manifestSet)
    expect(extraInActive, 'M2 must be caught by the "nothing silently added" assertion').toContain('__h6_round2_exec_block_add_probe__')
    expect(missingFromActive, 'M2 is an addition, not a drop — the other direction must stay clean').toEqual([])
    // ROUND 4 (G2 fix, merge-train dry-run v3): the exec block is ONE logical line
    // (backslash-continued) — every token in it, including one injected on a new physical line, is
    // attributed to the logical line's START, not the physical line the injected text happens to
    // sit on. The expected start line is PARSED from the real (unmutated) script via
    // `allVitestInvocations`, not hardcoded: a hardcoded literal (round 1-3's `1257`) silently goes
    // stale the moment any earlier edit shifts the exec block's physical position — measured by the
    // dry-run to actually happen (a sibling lane's insert above the block moved it to 1359) — while
    // this computed value tracks the real file under test by construction. The next test proves the
    // computed value actually moves when the file does, discriminating it from a renamed constant.
    const execInvocation = allVitestInvocations(scriptSrc).find((inv) => /^exec\s+npx\s+vitest\s+run\b/.test(inv.text))
    expect(execInvocation, 'fixture sanity: the real script must have exactly one exec logical line').toBeTruthy()
    const expectedExecStartLine = execInvocation!.startLine
    expect(lineMap.get('__h6_round2_exec_block_add_probe__')).toEqual([expectedExecStartLine])
  })

  it('r4-G2: inserting N comment-only physical lines above the exec block shifts its detected start line by exactly N — discriminates the computed expectation above from a hardcoded constant that would not move with the file', () => {
    const insertedCount = 37
    const execHeaderLine = 'exec npx vitest run \\'
    const lines = scriptSrc.split('\n')
    const execIdx = lines.indexOf(execHeaderLine)
    expect(execIdx, 'fixture sanity: exec header line must exist verbatim in the real script').toBeGreaterThan(-1)
    const inserted = Array.from({ length: insertedCount }, (_, i) => `# r4-G2 probe inserted comment line ${i}`)
    const mutated = [...lines.slice(0, execIdx), ...inserted, ...lines.slice(execIdx)].join('\n')

    const before = allVitestInvocations(scriptSrc).find((inv) => /^exec\s+npx\s+vitest\s+run\b/.test(inv.text))!.startLine
    const after = allVitestInvocations(mutated).find((inv) => /^exec\s+npx\s+vitest\s+run\b/.test(inv.text))!.startLine
    expect(
      after,
      `inserting ${insertedCount} comment-only physical lines above the exec block must move its `
        + `detected start line by exactly ${insertedCount} — a hardcoded expectation would instead `
        + `stay fixed and silently mismatch the very first time a lane rebase moves the block`,
    ).toBe(before + insertedCount)
  })

  it('M3 a line deleted from the MANIFEST (token still active) -> "extra in active" reds, naming it', () => {
    const victim = 'amountAutoSum'
    expect(manifestSet.has(victim), 'fixture sanity').toBe(true)
    const mutatedManifest = new Set(manifestSet)
    mutatedManifest.delete(victim)
    const activeSet = allVitestTokens(scriptSrc)
    const { missingFromActive, extraInActive } = diffSets(activeSet, mutatedManifest)
    expect(extraInActive, 'M3 must be caught the same way as M2 — the manifest no longer vouches for a token the lane still runs').toContain(victim)
    expect(missingFromActive).toEqual([])
  })

  it('M4 reordering the manifest file (no add/remove) changes nothing (set semantics — order carries no meaning)', () => {
    const activeSet = allVitestTokens(scriptSrc)
    const reorderedManifest = new Set([...manifestSet].sort((a, b) => (a < b ? 1 : a > b ? -1 : 0)))
    const { missingFromActive, extraInActive } = diffSets(activeSet, reorderedManifest)
    expect(missingFromActive, 'reordering the manifest must not be mistaken for a drop').toEqual([])
    expect(extraInActive, 'reordering the manifest must not be mistaken for an addition').toEqual([])
  })

  it('M5 (P1-1 option (a) discriminating case) an ENTIRE EARLY LINE deleted (multitable-field-config-panel) -> "missing from active" reds, naming it; message names the SCANNED lines, not a false former-line claim', () => {
    const victimLine = 'npx vitest run multitable-field-config-panel --reporter=dot'
    const lines = scriptSrc.split('\n')
    const idx = lines.indexOf(victimLine)
    expect(idx, 'fixture sanity: the lane script must still carry this exact physical line for multitable-field-config-panel').toBeGreaterThan(-1)
    const mutated = [...lines.slice(0, idx), ...lines.slice(idx + 1)].join('\n')

    // ROUND 5 (r4-P2-1, widened census): the post-mutation invocation count was hardcoded (`18`,
    // with a `19 -> 18` message). Derived from the same script the mutation was built from, so
    // adding or removing a gating line elsewhere in the lane no longer reds this case.
    const gatingInvocationsBefore = allVitestInvocations(scriptSrc).length
    expect(
      allVitestInvocations(mutated).length,
      'deleting the whole physical line must remove exactly one gating invocation from the parsed set',
    ).toBe(gatingInvocationsBefore - 1)
    const activeSet = allVitestTokens(mutated)
    expect(activeSet.has('multitable-field-config-panel')).toBe(false)

    const { missingFromActive, extraInActive } = diffSets(activeSet, manifestSet)
    expect(missingFromActive, 'M5: under option (a) this reds; under option (b) (exec-block-only scope) this token would never have been in the manifest to notice — this is the discriminating case').toContain('multitable-field-config-panel')
    expect(extraInActive).toEqual([])

    const scannedLines = allVitestInvocations(mutated).map((l) => l.startLine)
    const message = describeMissing(missingFromActive, scannedLines)
    // ROUND 5 (r4-P2-1): both expectations were hardcoded — `toContain('477')` and
    // `.not.toMatch(/\b624\b/)`. The second is the worse shape of the two: once an edit above
    // shifts the lane's line numbers, the deleted line is no longer numbered 624 and the negative
    // assertion passes VACUOUSLY rather than reddening. Both are derived below — the first from
    // the scan this test just performed, the second from the physical index the mutation used.
    expect(
      scannedLines.length,
      'fixture sanity: the post-mutation scan must still find gating invocations for the message to name',
    ).toBeGreaterThan(0)
    expect(message, 'the message must name the lines it scanned').toContain(String(scannedLines[0]))
    // The deleted line's own 1-based number, anchored to the mutation this test performed. The
    // anchor is what carries the negative assertion that follows: `.not.toMatch` over a list of
    // post-mutation scanned line numbers holds for nearly any integer, so on its own it would
    // survive a drifted expectation without complaint — which is exactly how round 4's `/\b624\b/`
    // went quietly green once the lane shifted. Asserting that the derived number still indexes
    // the physical line this test removed is the part with discriminating power.
    const deletedPhysicalLine = idx + 1
    expect(
      lines[deletedPhysicalLine - 1],
      'fixture sanity: the derived line number must index the exact physical line this test deletes',
    ).toBe(victimLine)
    expect(
      message,
      'the deleted line no longer exists post-mutation and must NOT appear as if it were the found location',
    ).not.toMatch(new RegExp(`\\b${deletedPhysicalLine}\\b`))
  })

  it('M6 (line-attribution case) a token appended to an EARLY line (permission-match-parity / platform-app-shell / platform-app-launcher) -> "extra in active" reds, naming it AND its exact source line', () => {
    const originalLine = 'npx vitest run permission-match-parity platform-app-shell platform-app-launcher --reporter=dot'
    const mutatedLine = 'npx vitest run permission-match-parity platform-app-shell platform-app-launcher __h6_round2_early_line_add_probe__ --reporter=dot'
    const lines = scriptSrc.split('\n')
    const idx = lines.indexOf(originalLine)
    expect(idx, 'fixture sanity: the lane script must still carry this exact physical line').toBeGreaterThan(-1)
    const mutatedLines = [...lines]
    mutatedLines[idx] = mutatedLine
    const mutated = mutatedLines.join('\n')

    const activeSet = allVitestTokens(mutated)
    const lineMap = allVitestTokenLines(mutated)
    const { missingFromActive, extraInActive } = diffSets(activeSet, manifestSet)
    expect(extraInActive).toContain('__h6_round2_early_line_add_probe__')
    expect(missingFromActive).toEqual([])
    // ROUND 5 (r4-P2-1): derived from the physical index this test already computed above, not the
    // hardcoded `690` round 4 left here. The mutated line carries no backslash continuation, so its
    // logical line starts on that physical line itself; an edit above moves index and expectation
    // together.
    const expectedAttributionLine = idx + 1
    expect(
      lineMap.get('__h6_round2_early_line_add_probe__'),
      'the injected token must be attributed to exactly the physical line it was injected on, unlike the M5 drop direction',
    ).toEqual([expectedAttributionLine])

    const message = describeExtra(extraInActive, lineMap)
    expect(message).toContain(`__h6_round2_early_line_add_probe__@line(s) ${expectedAttributionLine}`)
  })

  it('M7 reordering the two tokens WITHIN one early (non-exec-block) line changes nothing — set, not sequence, semantics', () => {
    const originalLine = 'npx vitest run approval-fwb-mapping-config approval-fwb-mapping-editor --reporter=dot'
    const reorderedLine = 'npx vitest run approval-fwb-mapping-editor approval-fwb-mapping-config --reporter=dot'
    const lines = scriptSrc.split('\n')
    const idx = lines.indexOf(originalLine)
    expect(idx, 'fixture sanity: the lane script must still carry this exact physical line').toBeGreaterThan(-1)
    const mutatedLines = [...lines]
    mutatedLines[idx] = reorderedLine
    const mutated = mutatedLines.join('\n')

    const before = allVitestTokens(scriptSrc)
    const after = allVitestTokens(mutated)
    expect([...after].sort(), 'reordering tokens within a line must not change the derived token set').toEqual([...before].sort())
    // ROUND 5 (r4-P2-1): derived from the physical index computed above, not the hardcoded `555`.
    const expectedAttributionLine = idx + 1
    expect(allVitestTokenLines(mutated).get('approval-fwb-mapping-config'), 'line attribution must survive the reorder').toEqual([expectedAttributionLine])
    expect(allVitestTokenLines(mutated).get('approval-fwb-mapping-editor')).toEqual([expectedAttributionLine])

    const { missingFromActive, extraInActive } = diffSets(after, manifestSet)
    expect(missingFromActive, 'reordering must not be mistaken for a drop').toEqual([])
    expect(extraInActive, 'reordering must not be mistaken for an addition').toEqual([])
  })

  it('NIT-3 probe: the derived sanity floor actually reds on the degenerate case (both collections empty) — it is not a vacuous check', () => {
    expect(() => assertNeitherCollapsesRelativeToTheOther(0, 0)).toThrow()
  })

  it('NIT-3 probe: a legitimate synchronized shrink (both sides shrink together) does NOT spuriously red', () => {
    expect(() => assertNeitherCollapsesRelativeToTheOther(50, 50)).not.toThrow()
  })

  it('NIT-3 probe: a real 300-token snapshot (below the OLD hardcoded literal) does not spuriously red against a same-sized manifest, proving the derived floor is not merely a renamed constant', () => {
    expect(() => assertNeitherCollapsesRelativeToTheOther(300, 300)).not.toThrow()
  })

  it('r2-P3-3: allVitestInvocations has a POSITIVE control for the "exactly 1 exec logical line" throw — a second exec logical line makes it throw, naming the count', () => {
    const anchorLine = 'exec npx vitest run \\'
    const lines = scriptSrc.split('\n')
    const idx = lines.indexOf(anchorLine)
    expect(idx, 'fixture sanity: the exec block must still start with this exact line').toBeGreaterThan(-1)
    // The exec block is the script's LAST logical line, running to end-of-file — duplicating from
    // its start line to the end appends a genuine second `exec npx vitest run …` logical line,
    // not merely a second fragment of the same one.
    const duplicated = [...lines, ...lines.slice(idx)].join('\n')
    // Sanity via logicalLines() (which does not throw) before asserting on allVitestInvocations(),
    // which DOES throw as soon as it calls execLogicalLine() internally — so the "did the mutation
    // actually land" check must happen without calling the throwing function first.
    expect(logicalLines(duplicated).filter((line) => /^exec\s+npx\s+vitest\s+run\b/.test(line)), 'ANCHOR_HIT: fixture sanity — the mutation must actually produce two exec-shaped logical lines before asserting on the throw').toHaveLength(2)
    expect(() => allVitestInvocations(duplicated)).toThrow(/expected exactly 1 exec logical line, found 2/)
  })

  it('r2-P3-4: allVitestInvocations is not a fourth silently-diverged copy of the comment-strip/fold loop — its output equals logicalLines() filtered to vitest-run lines, on the real lane script', () => {
    const fromAllVitestInvocations = allVitestInvocations(scriptSrc).map((l) => l.text)
    const fromLogicalLines = logicalLines(scriptSrc).filter((line) => /\bvitest\s+run\b/.test(line))
    expect(
      fromAllVitestInvocations,
      'allVitestInvocations() re-implements the comment-strip/continuation-fold loop (see its '
        + 'header for why) — this asserts that untyped duplicate loop still agrees with '
        + 'logicalLines() on every gating line, so a future divergence between the two reds here '
        + 'instead of relying only on the header\'s prose promise',
    ).toEqual(fromLogicalLines)
  })

  it('r2-P3-4 (widened round 5, r4-P3-3): the same allVitestInvocations-vs-logicalLines agreement holds across the whole FIXTURES battery, not just the one real lane script', () => {
    // ROUND 5 (r4-P3-3) — the fourth copy of the comment-strip/continuation-fold loop (inside
    // `allVitestInvocations`) had its agreement checked against `logicalLines()` on exactly ONE
    // input: the real lane script. That script carries no indented `#` and no comment inside a
    // continuation, so a whole class of divergence between the two loops was unobservable. Running
    // the same comparison over the named battery widens it to the fourth copy, but the comparison
    // below is filtered through a `vitest run` predicate, which absorbs the divergence the two
    // indented-`#` fixtures were added to catch — that class stays open, not covered by this loop
    // (existing, unresolved; round-5 gate P3-1).
    for (const [fixtureName, fixtureSrc] of Object.entries(FIXTURES)) {
      expect(
        allVitestInvocations(fixtureSrc).map((l) => l.text),
        `[${fixtureName}] allVitestInvocations()'s own fold loop diverged from logicalLines() on `
          + `this fixture — the fourth copy of the loop has drifted from the three that are `
          + `compared behaviourally above`,
      ).toEqual(logicalLines(fixtureSrc).filter((line) => /\bvitest\s+run\b/.test(line)))
    }
  })
})
