/**
 * H-6 (2026-09-22) — the required web lane's token SET must equal a committed manifest.
 *
 * WHY THIS EXISTS
 * ----------------
 * `apps/web/scripts/run-required-web-tests.sh`'s exec block (see
 * `required-web-lane-registration-shape.test.ts`, its neighbour in this directory) is the
 * positional token filter the required `test (20.x)` -> `web-tests` pipeline actually runs. The
 * shape guard proves the block is well-formed (one exec line, one token per line, sorted, no
 * duplicates) — it does NOT prove the token SET is the one anyone intended. Delete a token from
 * the middle of an otherwise well-formed, sorted, duplicate-free block and every one of the shape
 * guard's assertions still passes: the file is still exactly as shaped, just one filter shorter. A
 * bad rebase, a careless manual edit, or a "cleanup" pass that deletes the wrong line all produce
 * that shape. See docs/development/required-web-lane-token-manifest-guard-design-20260922.md
 * (P2-2 of the independent 2026-09-21 verification cited there: 357 examples of exactly this kind
 * of silent-drop-shaped-fine passed with zero automated gate on the token SET.)
 *
 * This guard closes that: `apps/web/scripts/run-required-web-tests.tokens` is a plain, sorted,
 * one-token-per-line manifest committed alongside the script (generated by
 * `node scripts/ops/required-web-lane-token-manifest.mjs --write`), and this file asserts SET
 * equality between it and the live exec block — in both directions, reported separately so a
 * mutation of one direction cannot hide behind the other:
 *
 *   - a token in the manifest but no longer in the active block  -> silently dropped from the lane
 *   - a token in the active block but not yet in the manifist    -> added without updating the record
 *
 * This does NOT depend on git history (no merge-base, no `origin/main` diff) — see the design doc
 * for why a git-history-diff approach (compared and rejected as Option B) cannot run in this
 * repo's `push` event context (`plugin-tests.yml`'s checkouts are all default `actions/checkout@v4`
 * — fetch-depth 1, no `origin/main` ref available, and `push` events carry no `base_ref` at all).
 * Comparing two checked-in texts needs neither.
 *
 * PARSING: imports `execLogicalLine` / `tokensOf` from `scripts/ops/required-web-lane-exec-block.mjs`
 * — the SAME parser the shape guard and the token-set-diff script use, extracted to a plain-ESM
 * module (see that file's header for why it is a new extraction and not an import of either
 * existing copy: one has `process.exit` at module top level, the other's top level registers 18
 * `describe()` tests that would be double-counted by a second import).
 *
 * CI WIRING: this file lives in `packages/core-backend/tests/unit/`, the same directory as its
 * shape-guard neighbour, and is picked up by the SAME mechanism — `pnpm --filter @metasheet/core-
 * backend test` (plugin-tests.yml `test` job, `Run core-backend tests` step) runs bare `vitest`,
 * which collects every `*.test.ts` in the package under `vitest.config.ts`'s default include glob
 * (no custom `include:` override exists in that config — verified by reading it) and excludes only
 * the explicit list. This file's name is not in that exclude list, so it is collected on both
 * matrix legs of the required `test` job (`test (18.x)` and `test (20.x)`), same as the shape
 * guard added for the same reason one day earlier. Independently confirmed (not just inferred from
 * precedent): `npx vitest run required-web-lane --reporter=verbose` — a substring filter that
 * vitest applies AFTER globbing the whole package under the real config, not a literal path handed
 * straight to the loader — collects BOTH this file and the shape guard's file from that same
 * default-config glob; see the design/verification docs for the transcript.
 *
 * Values-free: reads only repo-tracked script/manifest text and asserts on token-name sets.
 */
import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { execLogicalLine, tokensOf } from '../../../../scripts/ops/required-web-lane-exec-block.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(HERE, '..', '..', '..', '..')
const LANE_SCRIPT = join(REPO_ROOT, 'apps', 'web', 'scripts', 'run-required-web-tests.sh')
const MANIFEST_PATH = join(REPO_ROOT, 'apps', 'web', 'scripts', 'run-required-web-tests.tokens')
const GITATTRIBUTES = join(REPO_ROOT, '.gitattributes')

function manifestTokens(raw: string): string[] {
  return raw
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
}

/** Both directions of the set diff, each sorted for a stable, readable failure message. */
function diffSets(active: Set<string>, manifest: Set<string>): { missingFromActive: string[]; extraInActive: string[] } {
  const missingFromActive = [...manifest].filter((t) => !active.has(t)).sort()
  const extraInActive = [...active].filter((t) => !manifest.has(t)).sort()
  return { missingFromActive, extraInActive }
}

describe('required web lane token manifest — set equality', () => {
  const scriptSrc = readFileSync(LANE_SCRIPT, 'utf8')
  const active = tokensOf(execLogicalLine(scriptSrc))
  const activeSet = new Set(active)

  const manifestRaw = readFileSync(MANIFEST_PATH, 'utf8')
  const manifest = manifestTokens(manifestRaw)
  const manifestSet = new Set(manifest)

  it('sanity: both the active block and the manifest are non-trivial (scan negative control)', () => {
    expect(active.length, 'the active exec block must not be empty or unparseable').toBeGreaterThan(300)
    expect(manifest.length, 'the manifest must not be empty — an empty file would make every later assertion vacuous').toBeGreaterThan(300)
  })

  it('the manifest has no duplicate lines (hygiene: --write always emits a de-duplicated Set)', () => {
    expect(manifestSet.size, 'a duplicate manifest line is dead weight, not a safety gap by itself (set semantics absorb it) — flagged so drift gets cleaned by re-running --write').toBe(manifest.length)
  })

  it('every manifest token is still present in the active exec block (nothing silently dropped from the lane)', () => {
    const { missingFromActive } = diffSets(activeSet, manifestSet)
    expect(
      missingFromActive,
      missingFromActive.length
        ? `${missingFromActive.length} token(s) recorded in apps/web/scripts/run-required-web-tests.tokens `
          + `are no longer in the active exec block — they silently stopped running in the required web `
          + `lane: ${missingFromActive.join(' ')}`
        : '',
    ).toEqual([])
  })

  it('every active exec-block token is recorded in the manifest (nothing silently added without updating it)', () => {
    const { extraInActive } = diffSets(activeSet, manifestSet)
    expect(
      extraInActive,
      extraInActive.length
        ? `${extraInActive.length} token(s) in the active exec block are not in `
          + `apps/web/scripts/run-required-web-tests.tokens — run `
          + `\`node scripts/ops/required-web-lane-token-manifest.mjs --write\` and commit the result in `
          + `the SAME PR that added them: ${extraInActive.join(' ')}`
        : '',
    ).toEqual([])
  })

  it('the manifest is pinned in .gitattributes as `text eol=lf merge=union`, same as the script it mirrors', () => {
    const attrs = readFileSync(GITATTRIBUTES, 'utf8')
    const rule = attrs
      .split('\n')
      .map((line) => line.replace(/\r$/, '').trim())
      .find((line) => line.startsWith('apps/web/scripts/run-required-web-tests.tokens '))
    expect(rule, '.gitattributes must pin the token manifest').toBeTruthy()
    expect(rule).toContain('eol=lf')
    expect(rule).toContain('merge=union')
  })
})

/**
 * MUTATION SELF-PROOF (2026-09-22), same discipline as the shape guard's own self-proof section:
 * each assertion above is only worth its runtime if it actually reds on the damage it claims to
 * catch. These cases mutate in-memory copies of the real active/manifest token sets — the files on
 * disk are never touched — and assert the corresponding detector fires, or (for the reorder case)
 * deliberately does not.
 */
describe('required web lane token manifest — mutation self-proof', () => {
  const scriptSrc = readFileSync(LANE_SCRIPT, 'utf8')
  const active = tokensOf(execLogicalLine(scriptSrc))
  const activeSet = new Set(active)

  const manifestRaw = readFileSync(MANIFEST_PATH, 'utf8')
  const manifest = manifestTokens(manifestRaw)
  const manifestSet = new Set(manifest)

  it('baseline: the real active set and the real manifest set are equal', () => {
    const { missingFromActive, extraInActive } = diffSets(activeSet, manifestSet)
    expect(missingFromActive).toEqual([])
    expect(extraInActive).toEqual([])
  })

  it('M1 a token deleted from the active block -> "missing from active" reds, naming it', () => {
    const victim = active[0]
    const mutatedActive = new Set(activeSet)
    mutatedActive.delete(victim)
    const { missingFromActive, extraInActive } = diffSets(mutatedActive, manifestSet)
    expect(missingFromActive, 'M1 must be caught by the "nothing silently dropped" assertion').toContain(victim)
    expect(extraInActive, 'M1 is a drop, not an addition — the other direction must stay clean').toEqual([])
  })

  it('M2 a token added to the active block that is not in the manifest -> "extra in active" reds, naming it', () => {
    const injected = '__h6_mutation_self_proof_extra_token__'
    expect(manifestSet.has(injected), 'fixture sanity: the injected token must not already be real').toBe(false)
    const mutatedActive = new Set(activeSet)
    mutatedActive.add(injected)
    const { missingFromActive, extraInActive } = diffSets(mutatedActive, manifestSet)
    expect(extraInActive, 'M2 must be caught by the "nothing silently added" assertion').toContain(injected)
    expect(missingFromActive, 'M2 is an addition, not a drop — the other direction must stay clean').toEqual([])
  })

  it('M3 a line deleted from the manifest (token still active) -> "extra in active" reds, naming it', () => {
    const victim = manifest[0]
    const mutatedManifest = new Set(manifestSet)
    mutatedManifest.delete(victim)
    const { missingFromActive, extraInActive } = diffSets(activeSet, mutatedManifest)
    expect(extraInActive, 'M3 must be caught the same way as M2 — the manifest no longer vouches for a token the lane still runs').toContain(victim)
    expect(missingFromActive).toEqual([])
  })

  it('M4 reordering either side changes nothing (set semantics — order carries no meaning here)', () => {
    const reorderedActive = new Set([...activeSet].reverse())
    const reorderedManifest = new Set([...manifestSet].sort((a, b) => (a < b ? 1 : a > b ? -1 : 0)))
    const { missingFromActive, extraInActive } = diffSets(reorderedActive, reorderedManifest)
    expect(missingFromActive, 'reordering must not be mistaken for a drop').toEqual([])
    expect(extraInActive, 'reordering must not be mistaken for an addition').toEqual([])
  })
})
