/**
 * H-6 (2026-09-22, widened round 2 2026-09-22) — the required web lane's token SET must equal a
 * committed manifest.
 *
 * WHY THIS EXISTS
 * ----------------
 * `apps/web/scripts/run-required-web-tests.sh` has 19 logical lines that invoke `vitest run` after
 * `set -euo pipefail` — 18 earlier `npx vitest run …` lines plus the final `exec npx vitest run …`
 * line (see `required-web-lane-registration-shape.test.ts`, its neighbour in this directory, for
 * the exec block's own shape assertions). Together these are the positional token filters the
 * required `test (20.x)` -> `web-tests` pipeline actually runs. The shape guard proves the exec
 * block specifically is well-formed (one exec line, one token per line, sorted, no duplicates) —
 * it does NOT prove any line's token SET is the one anyone intended, and it says nothing at all
 * about the 18 earlier lines. Delete a token from the middle of an otherwise well-formed, sorted,
 * duplicate-free block and every one of the shape guard's assertions still passes: the file is
 * still exactly as shaped, just one filter shorter. A bad rebase, a careless manual edit, or a
 * "cleanup" pass that deletes the wrong line all produce that shape. See
 * docs/development/required-web-lane-token-manifest-guard-design-20260922.md (P2-2 of the
 * independent 2026-09-21 adversarial verification cited there: 357 examples of exactly this kind
 * of silent-drop-shaped-fine passed with zero automated gate on the token SET — restated with
 * measured numbers below, not "zero automated gate" universally: see ROUND 2 note).
 *
 * ROUND 2 (2026-09-22) — SCOPE WIDENED, P1-1 option (a) chosen
 * --------------------------------------------------------------
 * An independent gate review of round 1
 * (`/Users/chouhua/.claude/projects/-Users-chouhua-Downloads-Github-metasheet2/reviews/impl-gate-H6-token-manifest-guard-round1-20260922.md`)
 * found that round 1's guard covered only the FINAL exec line's 397 tokens — one of the lane's 19
 * gating `vitest run` invocations. The other 18 carry **102 more** distinct tokens, of which **28**
 * were pinned by NOTHING else in the repo (P1-1). The review also measured that the premise above
 * is not universally true: **192 of the lane's 499 total tokens are already gated today** by four
 * existing census/shape guards union'd together (`approval-ci-coverage-enumeration.test.ts`,
 * `stock-prep-web-ci-coverage-enumeration.test.ts`, `elearning-media-ci-wiring.test.mjs`,
 * `network-unavailable-copy-ci-wiring.test.ts`) — P2-1. This file's actual, measured contribution
 * is the **279** exec-block tokens that move from ungated to gated, plus closing the **28**
 * earlier-line tokens that were gated by nothing at all.
 *
 * This guard now asserts SET equality between `apps/web/scripts/run-required-web-tests.tokens`
 * (499 tokens, generated by `node scripts/ops/required-web-lane-token-manifest.mjs --write`, one
 * token per line plus a `#`-prefixed provenance header) and the UNION of all 19 gating
 * invocations' token sets (`allVitestTokens()`,
 * `scripts/ops/required-web-lane-exec-block.mjs`) — in both directions, reported separately so a
 * mutation of one direction cannot hide behind the other:
 *
 *   - a token in the manifest but produced by NO gating invocation -> silently dropped from the
 *     lane. The message names the scanned line numbers, not the token's former line — a dropped
 *     token is, by construction, on no remaining line, so this guard (which reads only the
 *     CURRENT script and manifest text, not git history) cannot know where it used to live.
 *   - a token produced by a gating invocation but not yet in the manifest -> added without
 *     updating the record. The message DOES name the exact source line(s), because that
 *     information is available for a token that still exists in the active text.
 *
 * This does NOT depend on git history (no merge-base, no `origin/main` diff) — see the design doc
 * for why a git-history-diff approach (compared and rejected as Option B) cannot run in this
 * repo's `push` event context (`plugin-tests.yml`'s checkouts are all default `actions/checkout@v4`
 * — fetch-depth 1, no `origin/main` ref available, and `push` events carry no `base_ref` at all).
 * Comparing two checked-in texts needs neither.
 *
 * PARSING: imports `allVitestInvocations` / `allVitestTokenLines` / `allVitestTokens` (round 2) and
 * `logicalLines` / `execLogicalLine` / `tokensOf` / `stripTrailingErrorGuard` from
 * `scripts/ops/required-web-lane-exec-block.mjs` — the SAME module the generator uses. See that
 * file's header for why it is a third extraction of `logicalLines`/`execLogicalLine`/`tokensOf`
 * rather than an import of either existing copy (one has `process.exit` at module top level, the
 * other's top level registers 18 `describe()` tests that would be double-counted by a second
 * import). Those three functions are kept byte-identical to the other two copies on purpose — see
 * the "cross-copy agreement" test below, which checks that textually, not just behaviourally.
 *
 * CI WIRING: this file lives in `packages/core-backend/tests/unit/`, the same directory as its
 * shape-guard neighbour, and is picked up by the SAME mechanism — `pnpm --filter @metasheet/core-
 * backend test` (plugin-tests.yml `test` job, `Run core-backend tests` step) runs bare `vitest`,
 * which collects every `*.test.ts` in the package under `vitest.config.ts`'s default include glob
 * (no custom `include:` override exists in that config — verified by reading it) and excludes only
 * the explicit list. This file's name is not in that exclude list, so it is collected on both
 * matrix legs of the `test` job (`test (18.x)` and `test (20.x)`) — but only `test (20.x)` is a
 * REQUIRED status context (`gh api repos/zensgit/metasheet2/branches/main/protection` does not
 * list `test (18.x)`; `test (18.x)` running the identical step is still useful as non-required
 * real-CI evidence, not as the gate itself). Independently confirmed (not just inferred from
 * precedent): `npx vitest run required-web-lane --reporter=verbose` — a substring filter that
 * vitest applies AFTER globbing the whole package under the real config, not a literal path handed
 * straight to the loader — collects BOTH this file and the shape guard's file from that same
 * default-config glob; see the design/verification docs for the transcript (18 -> 28 tests before
 * vs. after this file existed).
 *
 * Values-free: reads only repo-tracked script/manifest text and asserts on token-name sets.
 */
import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  allVitestInvocations,
  allVitestTokenLines,
  allVitestTokens,
  execLogicalLine,
  logicalLines,
  stripTrailingErrorGuard,
  tokensOf,
} from '../../../../scripts/ops/required-web-lane-exec-block.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(HERE, '..', '..', '..', '..')
const LANE_SCRIPT = join(REPO_ROOT, 'apps', 'web', 'scripts', 'run-required-web-tests.sh')
const MANIFEST_PATH = join(REPO_ROOT, 'apps', 'web', 'scripts', 'run-required-web-tests.tokens')
const GITATTRIBUTES = join(REPO_ROOT, '.gitattributes')
const SHAPE_GUARD_PATH = join(REPO_ROOT, 'packages', 'core-backend', 'tests', 'unit', 'required-web-lane-registration-shape.test.ts')

const RELATIVE_MANIFEST = 'apps/web/scripts/run-required-web-tests.tokens'
const RELATIVE_LANE_SCRIPT = 'apps/web/scripts/run-required-web-tests.sh'

/** Blank lines and `#`-prefixed provenance/comment lines are not tokens (P3-5, round-1 gate review). */
function manifestTokens(raw: string): string[] {
  return raw
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith('#'))
}

/** Both directions of the set diff, each sorted for a stable, readable failure message. */
function diffSets(active: Set<string>, manifest: Set<string>): { missingFromActive: string[]; extraInActive: string[] } {
  const missingFromActive = [...manifest].filter((t) => !active.has(t)).sort()
  const extraInActive = [...active].filter((t) => !manifest.has(t)).sort()
  return { missingFromActive, extraInActive }
}

/**
 * A token recorded in the manifest but produced by no gating invocation is, by construction, on NO
 * current source line — there is nothing to point at. Name the lines that WERE scanned instead, so
 * the message is honest about what it can and cannot localize (see the class-level header note).
 */
function describeMissing(tokens: string[], scannedLines: number[]): string {
  return `${tokens.length} token(s) recorded in ${RELATIVE_MANIFEST} are produced by NONE of the `
    + `${scannedLines.length} gating \`vitest run\` invocations in ${RELATIVE_LANE_SCRIPT} (lines: `
    + `${scannedLines.join(', ')}) — they silently stopped running in the required web lane: ${tokens.join(' ')}`
}

/** A token still produced by a gating invocation DOES have a current line — name it. */
function describeExtra(tokens: string[], lineMap: Map<string, number[]>): string {
  const withLines = tokens.map((t) => {
    const lines = lineMap.get(t)
    return lines && lines.length ? `${t}@line(s) ${lines.join(',')}` : t
  })
  return `${tokens.length} token(s) are produced by a gating \`vitest run\` invocation in `
    + `${RELATIVE_LANE_SCRIPT} but are not recorded in ${RELATIVE_MANIFEST} — run `
    + `\`node scripts/ops/required-web-lane-token-manifest.mjs --write\` and commit the result in `
    + `the SAME PR that added them: ${withLines.join(' ')}`
}

/**
 * P3-6 (round-1 gate review) — cross-copy agreement, checked as SOURCE TEXT, not behaviour.
 *
 * `logicalLines`/`execLogicalLine`/`tokensOf` in `required-web-lane-exec-block.mjs` are meant to
 * stay byte-for-byte algorithmically identical to `required-web-lane-registration-shape.test.ts`'s
 * own copy (that file cannot be safely `import`ed here — see its neighbour module's header for why
 * — so its exports are never called directly by this file). A source-text check is strictly
 * STRONGER than a behavioural one here: calling both copies on one input (the exec block) cannot
 * detect a divergence that only shows up on a different input; comparing the normalized source
 * proves the algorithms are the same for every input, not just today's.
 */
function extractExportedFunctionSource(fileText: string, functionName: string): string {
  const marker = new RegExp(`export function ${functionName}\\([^)]*\\)[^{]*\\{`)
  const head = marker.exec(fileText)
  if (!head) {
    throw new Error(`could not find "export function ${functionName}(" in ${SHAPE_GUARD_PATH}`)
  }
  const braceStart = head.index + head[0].length - 1
  let depth = 0
  let i = braceStart
  for (; i < fileText.length; i += 1) {
    if (fileText[i] === '{') depth += 1
    else if (fileText[i] === '}') {
      depth -= 1
      if (depth === 0) {
        i += 1
        break
      }
    }
  }
  return fileText.slice(head.index, i)
}

/** Strip the `export` keyword, TypeScript type annotations, and comments — the only documented differences between the copies. */
function normalizeParserSource(src: string): string {
  return src
    .replace(/^export\s+/, '')
    .replace(/\/\/[^\n]*/g, '')
    .replace(/:\s*string\s*\|\s*null/g, '')
    .replace(/:\s*string\[\]/g, '')
    .replace(/:\s*string\b/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

/**
 * NIT-3 (round-1 gate review) — a derived sanity floor instead of a hardcoded magic number,
 * factored out so the "does it actually red on the degenerate case" probe below calls the exact
 * same logic the real assertion uses, rather than re-deriving it and risking the two drifting.
 */
function assertNeitherCollapsesRelativeToTheOther(activeCount: number, manifestCount: number): void {
  expect(
    activeCount,
    'the active token collection must not be empty or drastically smaller than the manifest — a '
      + 'broken parse shows up as a large asymmetric drop, not merely "smaller than before", so this '
      + 'floor is derived from the manifest\'s own size rather than a hardcoded constant that would '
      + 'spuriously red if the lane legitimately shrinks',
  ).toBeGreaterThan(manifestCount / 2)
  expect(
    manifestCount,
    'the manifest must not be empty or drastically smaller than the active token collection',
  ).toBeGreaterThan(activeCount / 2)
}

describe('required web lane token manifest — set equality', () => {
  const scriptSrc = readFileSync(LANE_SCRIPT, 'utf8')
  const activeSet = allVitestTokens(scriptSrc)
  const active = [...activeSet]
  const activeLineMap = allVitestTokenLines(scriptSrc)
  const invocationLines = allVitestInvocations(scriptSrc).map((l) => l.startLine)

  const manifestRaw = readFileSync(MANIFEST_PATH, 'utf8')
  const manifest = manifestTokens(manifestRaw)
  const manifestSet = new Set(manifest)

  it('sanity: neither the active token collection nor the manifest collapses to near-empty relative to the other (scan negative control)', () => {
    assertNeitherCollapsesRelativeToTheOther(active.length, manifest.length)
  })

  it('the manifest has no duplicate TOKEN lines (hygiene: --write always emits a de-duplicated Set; header/comment lines are excluded from this count, not counted as duplicates of each other)', () => {
    expect(manifestSet.size, 'a duplicate manifest line is dead weight, not itself a safety gap (set semantics absorb it) — flagged so drift gets cleaned by re-running --write').toBe(manifest.length)
  })

  it('every manifest token is still produced by at least one of the 19 gating invocations (nothing silently dropped from the lane)', () => {
    const { missingFromActive } = diffSets(activeSet, manifestSet)
    expect(missingFromActive, missingFromActive.length ? describeMissing(missingFromActive, invocationLines) : '').toEqual([])
  })

  it('every token produced by a gating invocation is recorded in the manifest (nothing silently added without updating it) — the failure names the offending source line(s)', () => {
    const { extraInActive } = diffSets(activeSet, manifestSet)
    expect(extraInActive, extraInActive.length ? describeExtra(extraInActive, activeLineMap) : '').toEqual([])
  })

  it('the manifest is pinned in .gitattributes as `text eol=lf merge=union`, same as the script it mirrors', () => {
    const attrs = readFileSync(GITATTRIBUTES, 'utf8')
    const rule = attrs
      .split('\n')
      .map((line) => line.replace(/\r$/, '').trim())
      .find((line) => line.startsWith('apps/web/scripts/run-required-web-tests.tokens '))
    expect(rule, '.gitattributes must pin the token manifest').toBeTruthy()
    expect(rule).toContain('eol=lf')
    expect(rule).toContain('merge=union')
  })

  it('cross-copy agreement: logicalLines/execLogicalLine/tokensOf are textually identical (modulo export/TS-types/comments) to the shape guard\'s own copy (P3-6)', () => {
    const shapeGuardSrc = readFileSync(SHAPE_GUARD_PATH, 'utf8')
    const ours: Record<string, (...args: never[]) => unknown> = { logicalLines, execLogicalLine, tokensOf }
    for (const name of ['logicalLines', 'execLogicalLine', 'tokensOf']) {
      const theirs = normalizeParserSource(extractExportedFunctionSource(shapeGuardSrc, name))
      const ourNormalized = normalizeParserSource(ours[name].toString())
      expect(
        ourNormalized,
        `scripts/ops/required-web-lane-exec-block.mjs's ${name}() has diverged from `
          + `required-web-lane-registration-shape.test.ts's copy — a bug fixed in one and not the `
          + `other is now invisible to the guard that is supposed to catch drift. Update both.`,
      ).toBe(theirs)
    }
  })
})

describe('required web lane token manifest — stripTrailingErrorGuard()', () => {
  const scriptSrc = readFileSync(LANE_SCRIPT, 'utf8')

  it('strips the exact `|| exit $?` tail carried by the two early gating lines that have it (1180, 1183)', () => {
    expect(stripTrailingErrorGuard('npx vitest run foo bar --reporter=dot || exit $?')).toBe('npx vitest run foo bar --reporter=dot')
  })

  it('is a no-op on a line without the tail, including the final exec line\'s form', () => {
    expect(stripTrailingErrorGuard('npx vitest run foo --reporter=dot')).toBe('npx vitest run foo --reporter=dot')
    expect(stripTrailingErrorGuard('exec npx vitest run a b c --reporter=dot')).toBe('exec npx vitest run a b c --reporter=dot')
  })

  it('does NOT touch a positional token literally named "exit" that is not part of the trailing idiom (anchored at end-of-string, not a bare-word replace)', () => {
    expect(stripTrailingErrorGuard('npx vitest run exit --reporter=dot')).toBe('npx vitest run exit --reporter=dot')
  })

  it('applied to the real lines 1180/1183, tokenizes clean of `||`/`exit`/`$?` — none of the three survive as if they were vitest positional filters', () => {
    const invocations = allVitestInvocations(scriptSrc)
    const line1180 = invocations.find((l) => l.startLine === 1180)
    const line1183 = invocations.find((l) => l.startLine === 1183)
    expect(line1180, 'fixture sanity: line 1180 must still be one of the 19 gating invocations').toBeTruthy()
    expect(line1183, 'fixture sanity: line 1183 must still be one of the 19 gating invocations').toBeTruthy()
    const tokens1180 = tokensOf(stripTrailingErrorGuard(line1180!.text))
    const tokens1183 = tokensOf(stripTrailingErrorGuard(line1183!.text))
    for (const garbage of ['||', 'exit', '$?']) {
      expect(tokens1180, `line 1180 must not tokenize the shell control operator/variable "${garbage}"`).not.toContain(garbage)
      expect(tokens1183, `line 1183 must not tokenize the shell control operator/variable "${garbage}"`).not.toContain(garbage)
    }
    expect(tokens1183).toEqual(['attendance-punch-outcome'])
  })
})

/**
 * MUTATION SELF-PROOF (2026-09-22, extended round 2 2026-09-22) — same discipline as the shape
 * guard's own self-proof section: each assertion above is only worth its runtime if it actually
 * reds on the damage it claims to catch. These mutate IN-MEMORY COPIES of the real script text /
 * token sets — the files on disk are never touched — and assert the corresponding detector fires,
 * or (for the reorder cases) deliberately does not.
 *
 * M1-M4 exercise the FINAL EXEC BLOCK (round 1's original scope). M5-M7 exercise one of the 18
 * EARLIER lines — the discriminating cases for P1-1 option (a): under option (b) (rename/rescope
 * to "final exec block only"), none of M5/M6 would be in the manifest's scope to red on at all.
 */
describe('required web lane token manifest — mutation self-proof', () => {
  const scriptSrc = readFileSync(LANE_SCRIPT, 'utf8')
  const manifestRaw = readFileSync(MANIFEST_PATH, 'utf8')
  const manifest = manifestTokens(manifestRaw)
  const manifestSet = new Set(manifest)

  it('baseline: the real active token set (union of all 19 gating invocations) and the real manifest set are equal', () => {
    const activeSet = allVitestTokens(scriptSrc)
    const { missingFromActive, extraInActive } = diffSets(activeSet, manifestSet)
    expect(missingFromActive).toEqual([])
    expect(extraInActive).toEqual([])
  })

  it('M1 a token deleted from the FINAL EXEC BLOCK -> "missing from active" reds, naming it (round-1 case, unchanged)', () => {
    const victimLine = '  amountAutoSum \\'
    const lines = scriptSrc.split('\n')
    const idx = lines.indexOf(victimLine)
    expect(idx, 'fixture sanity: exec block must still carry this exact physical line for amountAutoSum').toBeGreaterThan(-1)
    const mutated = [...lines.slice(0, idx), ...lines.slice(idx + 1)].join('\n')

    const activeSet = allVitestTokens(mutated)
    expect(activeSet.has('amountAutoSum')).toBe(false)
    const { missingFromActive, extraInActive } = diffSets(activeSet, manifestSet)
    expect(missingFromActive, 'M1 must be caught by the "nothing silently dropped" assertion').toContain('amountAutoSum')
    expect(extraInActive, 'M1 is a drop, not an addition — the other direction must stay clean').toEqual([])
  })

  it('M2 a token added to the FINAL EXEC BLOCK that is not in the manifest -> "extra in active" reds, naming it and its line', () => {
    const anchorLine = '  amountAutoSum \\'
    const injected = '  __h6_round2_exec_block_add_probe__ \\'
    const lines = scriptSrc.split('\n')
    const idx = lines.indexOf(anchorLine)
    expect(idx, 'fixture sanity').toBeGreaterThan(-1)
    const mutated = [...lines.slice(0, idx + 1), injected, ...lines.slice(idx + 1)].join('\n')

    const activeSet = allVitestTokens(mutated)
    const lineMap = allVitestTokenLines(mutated)
    const { missingFromActive, extraInActive } = diffSets(activeSet, manifestSet)
    expect(extraInActive, 'M2 must be caught by the "nothing silently added" assertion').toContain('__h6_round2_exec_block_add_probe__')
    expect(missingFromActive, 'M2 is an addition, not a drop — the other direction must stay clean').toEqual([])
    // The exec block is ONE logical line (backslash-continued) starting at physical line 1257 —
    // every token in it, including one injected on a new physical line, is attributed to the
    // logical line's START, not the physical line the injected text happens to sit on.
    expect(lineMap.get('__h6_round2_exec_block_add_probe__')).toEqual([1257])
  })

  it('M3 a line deleted from the MANIFEST (token still active) -> "extra in active" reds, naming it', () => {
    const victim = 'amountAutoSum'
    expect(manifestSet.has(victim), 'fixture sanity').toBe(true)
    const mutatedManifest = new Set(manifestSet)
    mutatedManifest.delete(victim)
    const activeSet = allVitestTokens(scriptSrc)
    const { missingFromActive, extraInActive } = diffSets(activeSet, mutatedManifest)
    expect(extraInActive, 'M3 must be caught the same way as M2 — the manifest no longer vouches for a token the lane still runs').toContain(victim)
    expect(missingFromActive).toEqual([])
  })

  it('M4 reordering the manifest file (no add/remove) changes nothing (set semantics — order carries no meaning)', () => {
    const activeSet = allVitestTokens(scriptSrc)
    const reorderedManifest = new Set([...manifestSet].sort((a, b) => (a < b ? 1 : a > b ? -1 : 0)))
    const { missingFromActive, extraInActive } = diffSets(activeSet, reorderedManifest)
    expect(missingFromActive, 'reordering the manifest must not be mistaken for a drop').toEqual([])
    expect(extraInActive, 'reordering the manifest must not be mistaken for an addition').toEqual([])
  })

  it('M5 (P1-1 option (a) discriminating case) an ENTIRE EARLY LINE deleted (multitable-field-config-panel, line 624) -> "missing from active" reds, naming it; message names the SCANNED lines, not a false former-line claim', () => {
    const victimLine = 'npx vitest run multitable-field-config-panel --reporter=dot'
    const lines = scriptSrc.split('\n')
    const idx = lines.indexOf(victimLine)
    expect(idx, 'fixture sanity: line 624 must still read exactly this').toBeGreaterThan(-1)
    const mutated = [...lines.slice(0, idx), ...lines.slice(idx + 1)].join('\n')

    expect(allVitestInvocations(mutated).length, 'deleting the whole line removes one gating invocation: 19 -> 18').toBe(18)
    const activeSet = allVitestTokens(mutated)
    expect(activeSet.has('multitable-field-config-panel')).toBe(false)

    const { missingFromActive, extraInActive } = diffSets(activeSet, manifestSet)
    expect(missingFromActive, 'M5: under option (a) this reds; under option (b) (exec-block-only scope) this token would never have been in the manifest to notice — this is the discriminating case').toContain('multitable-field-config-panel')
    expect(extraInActive).toEqual([])

    const scannedLines = allVitestInvocations(mutated).map((l) => l.startLine)
    const message = describeMissing(missingFromActive, scannedLines)
    expect(message, 'the message must name the lines it scanned').toContain('477')
    expect(message, 'line 624 no longer exists post-mutation and must NOT appear as if it were the found location').not.toMatch(/\b624\b/)
  })

  it('M6 (line-attribution case) a token appended to an EARLY line (690: permission-match-parity / platform-app-shell / platform-app-launcher) -> "extra in active" reds, naming it AND its exact source line', () => {
    const originalLine = 'npx vitest run permission-match-parity platform-app-shell platform-app-launcher --reporter=dot'
    const mutatedLine = 'npx vitest run permission-match-parity platform-app-shell platform-app-launcher __h6_round2_early_line_add_probe__ --reporter=dot'
    const lines = scriptSrc.split('\n')
    const idx = lines.indexOf(originalLine)
    expect(idx, 'fixture sanity: line 690 must still read exactly this').toBeGreaterThan(-1)
    const mutatedLines = [...lines]
    mutatedLines[idx] = mutatedLine
    const mutated = mutatedLines.join('\n')

    const activeSet = allVitestTokens(mutated)
    const lineMap = allVitestTokenLines(mutated)
    const { missingFromActive, extraInActive } = diffSets(activeSet, manifestSet)
    expect(extraInActive).toContain('__h6_round2_early_line_add_probe__')
    expect(missingFromActive).toEqual([])
    expect(lineMap.get('__h6_round2_early_line_add_probe__'), 'the injected token must be attributed to exactly line 690, unlike the M5 drop direction').toEqual([690])

    const message = describeExtra(extraInActive, lineMap)
    expect(message).toContain('__h6_round2_early_line_add_probe__@line(s) 690')
  })

  it('M7 reordering the two tokens WITHIN one early (non-exec-block) line (555) changes nothing — set, not sequence, semantics', () => {
    const originalLine = 'npx vitest run approval-fwb-mapping-config approval-fwb-mapping-editor --reporter=dot'
    const reorderedLine = 'npx vitest run approval-fwb-mapping-editor approval-fwb-mapping-config --reporter=dot'
    const lines = scriptSrc.split('\n')
    const idx = lines.indexOf(originalLine)
    expect(idx, 'fixture sanity: line 555 must still read exactly this').toBeGreaterThan(-1)
    const mutatedLines = [...lines]
    mutatedLines[idx] = reorderedLine
    const mutated = mutatedLines.join('\n')

    const before = allVitestTokens(scriptSrc)
    const after = allVitestTokens(mutated)
    expect([...after].sort(), 'reordering tokens within a line must not change the derived token set').toEqual([...before].sort())
    expect(allVitestTokenLines(mutated).get('approval-fwb-mapping-config'), 'line attribution must survive the reorder').toEqual([555])
    expect(allVitestTokenLines(mutated).get('approval-fwb-mapping-editor')).toEqual([555])

    const { missingFromActive, extraInActive } = diffSets(after, manifestSet)
    expect(missingFromActive, 'reordering must not be mistaken for a drop').toEqual([])
    expect(extraInActive, 'reordering must not be mistaken for an addition').toEqual([])
  })

  it('NIT-3 probe: the derived sanity floor actually reds on the degenerate case (both collections empty) — it is not a vacuous check', () => {
    expect(() => assertNeitherCollapsesRelativeToTheOther(0, 0)).toThrow()
  })

  it('NIT-3 probe: a legitimate synchronized shrink (both sides shrink together) does NOT spuriously red', () => {
    expect(() => assertNeitherCollapsesRelativeToTheOther(50, 50)).not.toThrow()
  })

  it('NIT-3 probe: a real 300-token snapshot (below the OLD hardcoded literal) does not spuriously red against a same-sized manifest, proving the derived floor is not merely a renamed constant', () => {
    expect(() => assertNeitherCollapsesRelativeToTheOther(300, 300)).not.toThrow()
  })
})
