// Label table for ApprovalNewView — report item O-8, slice F8-1 (approval member-surface locale).
// Same convention as templateCenterLabels.ts / templateDetailLabels.ts (#5545): a flat `NEW_ZH` /
// `NEW_EN` pair (`EN: Record<keyof typeof ZH, string>` so vue-tsc enforces key parity), consumed
// as `computed(() => (isZh.value ? NEW_ZH : NEW_EN))` from the module-scope `useLocale()`
// singleton. Copy with interpolated values (field labels, node names, counts) stays beside its use
// as an `isZh.value ? … : …` pair.
//
// Not localized here: the Chinese amount-in-words value itself (`amountToChineseWords`, 中文大写
// 金额) is a domain feature, only its caption is copy; template-authored text (field labels,
// placeholders, option labels, explanation bodies) is user data and renders as authored; the
// flag-OFF attachment placeholder (B2-28) is pinned byte-identical while the flag stays OFF, so its
// text stays in the template as a named exception of the F8-1 locale guards.

export const NEW_ZH = {
  pageTitle: '发起审批',
  back: '返回',
  reload: '重新加载',
  noDescription: '暂无描述',
  draftRestorePrompt: '检测到上次未提交的草稿，是否恢复？',
  draftRestoreApply: '恢复草稿',
  draftRestoreDiscard: '丢弃',
  prefillNotice: '已从上一次申请预填，请检查后提交',
  flow: '审批流程',
  requester: '发起人',
  routePreview: '按当前表单预览路径',
  routeTruncated: '（路径未能完整解析，以实际流转为准）',
  routeDirectPass: '（按当前表单将直接通过，无审批节点）',
  chooseApprover: '选择审批人',
  chooserMulti: '可选多人',
  chooserSingle: '选一人',
  chooserPlaceholder: '搜索并选择审批人',
  scopeMembers: '限指定成员',
  scopeRole: '限指定角色的成员',
  scopeCompany: '全公司可选',
  fillForm: '填写表单',
  recordLinkPlaceholder: '请选择一条关联记录',
  datetimePlaceholder: '请选择日期和时间',
  pickRecord: '选择记录',
  clear: '清除',
  rangeStart: '起始',
  rangeTo: '至',
  rangeEnd: '结束',
  duration: '时长',
  colActions: '操作',
  deleteRow: '删除',
  detailEmpty: '暂无明细行，请点击下方“添加一行”',
  addRow: '添加一行',
  removeAttachment: '移除',
  attachmentHint: '支持 PDF / JPG / PNG / TXT / CSV，单文件 ≤ 20MB，每字段 ≤ 10 个',
  amountInWords: '大写：',
  autoSummed: '由明细自动汇总，无需手填',
  submit: '提交审批',
  cancel: '取消',
  notFound: '未找到审批表单',
  attachmentTooMany: '附件数量超出上限（每字段最多 10 个）',
  attachmentUploadFailed: '附件上传失败',
  attachmentRemoveFailed: '附件移除失败，请重试',
  checkRequired: '请检查表单中的必填项',
  submitted: '审批已提交',
  submitFailed: '提交审批失败，请重试',
}

export const NEW_EN: Record<keyof typeof NEW_ZH, string> = {
  pageTitle: 'New approval',
  back: 'Back',
  reload: 'Reload',
  noDescription: 'No description',
  draftRestorePrompt: 'An unsubmitted draft from last time was found. Restore it?',
  draftRestoreApply: 'Restore draft',
  draftRestoreDiscard: 'Discard',
  prefillNotice: 'Prefilled from your previous request. Check it before submitting.',
  flow: 'Approval flow',
  requester: 'Requester',
  routePreview: 'Preview the route for this form',
  routeTruncated: '(The route could not be fully resolved; the actual flow decides.)',
  routeDirectPass: '(With this form the request passes directly, with no approval node.)',
  chooseApprover: 'Choose approvers',
  chooserMulti: 'several allowed',
  chooserSingle: 'choose one',
  chooserPlaceholder: 'Search and choose an approver',
  scopeMembers: 'specified members only',
  scopeRole: 'members of the specified roles only',
  scopeCompany: 'anyone in the company',
  fillForm: 'Fill in the form',
  recordLinkPlaceholder: 'Choose one linked record',
  datetimePlaceholder: 'Select a date and time',
  pickRecord: 'Choose record',
  clear: 'Clear',
  rangeStart: 'Start',
  rangeTo: 'to',
  rangeEnd: 'End',
  duration: 'Duration',
  colActions: 'Actions',
  deleteRow: 'Delete',
  detailEmpty: 'No rows yet. Click "Add row" below.',
  addRow: 'Add row',
  removeAttachment: 'Remove',
  attachmentHint: 'PDF / JPG / PNG / TXT / CSV, up to 20MB per file, up to 10 files per field',
  amountInWords: 'In Chinese capitals: ',
  autoSummed: 'Summed from the detail rows automatically; no need to fill in',
  submit: 'Submit',
  cancel: 'Cancel',
  notFound: 'Approval form not found',
  attachmentTooMany: 'Too many attachments (at most 10 per field)',
  attachmentUploadFailed: 'The attachment upload failed',
  attachmentRemoveFailed: 'The attachment could not be removed. Please try again.',
  checkRequired: 'Check the required fields in the form',
  submitted: 'Approval submitted',
  submitFailed: 'The approval could not be submitted. Please try again.',
}
