// Label tables for ApprovalDetailView — report item O-8, slice F8-1 (approval member-surface
// locale). Same convention as templateDetailLabels.ts (#5545): a flat `DETAIL_ZH` / `DETAIL_EN`
// pair (`EN: Record<keyof typeof ZH, string>` so vue-tsc enforces key parity) plus per-VALUE lookup
// maps as separate ZH / EN pairs, consumed through the module-scope `useLocale()` singleton.
//
// Copy with interpolated values stays beside its use as an `isZh.value ? … : …` pair. The five
// member-action dialogs' copy lives in approvals/memberActionDialogGrammar.ts (one table per
// locale). The quick-phrase chips (approvals/quickPhrases.ts) are NOT localized: a chip is inserted
// into the comment text as-is, so translating it would change the language of stored comments —
// an owner decision recorded in the F8-1 note, not this table's.

export const DETAIL_ZH = {
  pageTitleFallback: '审批详情',
  backToList: '返回列表',
  copySummary: '复制摘要',
  print: '打印',
  nextPending: '下一条 →',
  parallelInProgress: '并行中',
  myTurn: '等待你处理',
  reload: '重新加载',
  reloadRequired: '该审批的最新内容未能加载，请重新加载后再操作',
  notFoundTitle: '未找到该审批',
  notFoundHint: '该审批可能已被删除、链接有误或暂时无法加载',
  formInfo: '表单信息',
  metaRequestNo: '审批编号',
  metaRequester: '发起人',
  metaDepartment: '部门',
  metaCreatedAt: '发起时间',
  metaProgress: '进度',
  attachmentDeleted: '附件已删除',
  attachmentUnavailable: '附件暂不可用',
  noFormData: '暂无表单数据',
  sectionNav: '审批详情分区导航',
  tabInfo: '审批详情',
  tabRecord: '审批记录',
  tabComments: '全文评论',
  flow: '审批流程',
  viewTimeline: '时间线',
  viewTable: '表格',
  colNode: '节点名称',
  colApprover: '审批人',
  colResult: '审批结果/时间',
  autoApproved: '自动审批',
  allApprovedComplete: '会签完成',
  anyApprovedComplete: '或签完成',
  requesterFallback: '发起人',
  noHistory: '暂无审批历史',
  approve: '通过',
  reject: '驳回',
  return: '退回',
  transfer: '转交',
  addSign: '加签',
  reduceSign: '减签',
  remind: '催一下',
  revokeConfirmTitle: '确认撤回此审批？',
  confirm: '确认',
  cancel: '取消',
  revoke: '撤回',
  comment: '评论',
  ended: '该审批已结束',
  resubmit: '再次提交',
  transferTo: '转交给',
  transferPickerPlaceholder: '搜索并选择转交对象',
  addSignUsers: '加签人',
  addSignPickerPlaceholder: '搜索并添加加签人',
  addSignMode: '加签方式',
  reduceSignUser: '减签人',
  reduceSignPlaceholder: '选择要移除的加签人',
  attachments: '附件',
  removeAttachment: '移除',
  attachmentHint: '支持 PDF / JPG / PNG / TXT / CSV，单文件 ≤ 20MB',
  returnTo: '退回至节点',
  returnToPlaceholder: '选择退回目标节点',
  submitRow: '提交',
  endRow: '结束',
  otherBucket: '其他',
  approverFallback: '审批人',
  actionDialogApprove: '审批通过',
  actionDialogReject: '审批驳回',
  rejectReasonRequired: '驳回原因（必填）',
  opinionRequired: '审批意见（必填）',
  opinion: '审批意见',
  rejectReasonPlaceholder: '请填写驳回原因',
  opinionPlaceholder: '请输入审批意见',
  autoPassed: '自动通过',
  autoInvalidated: '自动失效',
  systemAutoApproval: '系统自动审批',
  system: '系统',
  systemInitial: '系',
  nodeChanged: '节点已变更',
  complexValue: '复杂内容',
  unknownOption: '未知选项',
  attachmentDownloadFailed: '附件下载失败，请稍后重试',
  attachmentUploadFailed: '附件上传失败',
  attachmentRemoveFailed: '附件移除失败，请重试',
  toastApproved: '审批已通过',
  toastRejected: '审批已驳回',
  actionFailed: '操作失败，请重试',
  transferred: '已成功转交',
  transferFailed: '转交失败，请重试',
  addSigned: '已成功加签',
  addSignFailed: '加签失败，请重试',
  reduceSigned: '已成功减签',
  reduceSignFailed: '减签失败，请重试',
  commentSubmitted: '评论已提交',
  commentFailed: '评论提交失败，请重试',
  returned: '已退回审批',
  returnFailed: '退回失败，请重试',
  revoked: '审批已撤回',
  revokeFailed: '撤回失败，请重试',
  summaryCopied: '审批摘要已复制',
  copyFailed: '复制失败，请重试',
  reminded: '已催办',
  remindFailed: '催办失败，请重试',
  justNow: '刚刚',
  summaryTitle: '审批：',
  summaryRequestNo: '编号：',
  summaryStatus: '状态：',
  summaryRequester: '发起人：',
  summaryCreatedAt: '发起时间：',
  summaryProgress: '进度：',
  summaryLink: '链接：',
}

export const DETAIL_EN: Record<keyof typeof DETAIL_ZH, string> = {
  pageTitleFallback: 'Approval details',
  backToList: 'Back to list',
  copySummary: 'Copy summary',
  print: 'Print',
  nextPending: 'Next →',
  parallelInProgress: 'In parallel',
  myTurn: 'Waiting for you',
  reload: 'Reload',
  reloadRequired: 'The latest version of this approval could not be loaded. Reload before taking any action.',
  notFoundTitle: 'Approval not found',
  notFoundHint: 'It may have been deleted, the link may be wrong, or it cannot be loaded right now.',
  formInfo: 'Form details',
  metaRequestNo: 'Request no.',
  metaRequester: 'Requester',
  metaDepartment: 'Department',
  metaCreatedAt: 'Submitted',
  metaProgress: 'Progress',
  attachmentDeleted: 'Attachment deleted',
  attachmentUnavailable: 'Attachment unavailable',
  noFormData: 'No form data',
  sectionNav: 'Approval detail sections',
  tabInfo: 'Details',
  tabRecord: 'History',
  tabComments: 'Comments',
  flow: 'Approval flow',
  viewTimeline: 'Timeline',
  viewTable: 'Table',
  colNode: 'Node',
  colApprover: 'Approver',
  colResult: 'Result / time',
  autoApproved: 'Auto-approved',
  allApprovedComplete: 'All approvals complete',
  anyApprovedComplete: 'Any-one approval complete',
  requesterFallback: 'the requester',
  noHistory: 'No approval history',
  approve: 'Approve',
  reject: 'Reject',
  return: 'Return',
  transfer: 'Transfer',
  addSign: 'Add approvers',
  reduceSign: 'Remove approvers',
  remind: 'Remind',
  revokeConfirmTitle: 'Withdraw this approval?',
  confirm: 'Confirm',
  cancel: 'Cancel',
  revoke: 'Withdraw',
  comment: 'Comment',
  ended: 'This approval has ended',
  resubmit: 'Submit again',
  transferTo: 'Transfer to',
  transferPickerPlaceholder: 'Search and choose who to transfer to',
  addSignUsers: 'Approvers to add',
  addSignPickerPlaceholder: 'Search and add an approver',
  addSignMode: 'How approvers are added',
  reduceSignUser: 'Approver to remove',
  reduceSignPlaceholder: 'Choose an added approver to remove',
  attachments: 'Attachments',
  removeAttachment: 'Remove',
  attachmentHint: 'PDF / JPG / PNG / TXT / CSV, up to 20MB per file',
  returnTo: 'Return to node',
  returnToPlaceholder: 'Choose the node to return to',
  submitRow: 'Submitted',
  endRow: 'End',
  otherBucket: 'Other',
  approverFallback: 'Approver',
  actionDialogApprove: 'Approve',
  actionDialogReject: 'Reject',
  rejectReasonRequired: 'Reason for rejection (required)',
  opinionRequired: 'Comment (required)',
  opinion: 'Comment',
  rejectReasonPlaceholder: 'Enter the reason for rejection',
  opinionPlaceholder: 'Enter a comment',
  autoPassed: 'Auto-approved',
  autoInvalidated: 'Automatically voided',
  systemAutoApproval: 'System (auto-approval)',
  system: 'System',
  systemInitial: 'S',
  nodeChanged: 'Node changed',
  complexValue: 'Complex value',
  unknownOption: 'Unknown option',
  attachmentDownloadFailed: 'The attachment could not be downloaded. Please try again later.',
  attachmentUploadFailed: 'The attachment upload failed',
  attachmentRemoveFailed: 'The attachment could not be removed. Please try again.',
  toastApproved: 'Approved',
  toastRejected: 'Rejected',
  actionFailed: 'The action failed. Please try again.',
  transferred: 'Transferred',
  transferFailed: 'The transfer failed. Please try again.',
  addSigned: 'Approvers added',
  addSignFailed: 'Adding approvers failed. Please try again.',
  reduceSigned: 'Approver removed',
  reduceSignFailed: 'Removing the approver failed. Please try again.',
  commentSubmitted: 'Comment submitted',
  commentFailed: 'The comment could not be submitted. Please try again.',
  returned: 'Returned',
  returnFailed: 'The return failed. Please try again.',
  revoked: 'Withdrawn',
  revokeFailed: 'The withdrawal failed. Please try again.',
  summaryCopied: 'Summary copied',
  copyFailed: 'Copy failed. Please try again.',
  reminded: 'Reminder sent',
  remindFailed: 'The reminder failed. Please try again.',
  justNow: 'just now',
  summaryTitle: 'Approval: ',
  summaryRequestNo: 'Request no.: ',
  summaryStatus: 'Status: ',
  summaryRequester: 'Requester: ',
  summaryCreatedAt: 'Submitted: ',
  summaryProgress: 'Progress: ',
  summaryLink: 'Link: ',
}

/** History action verbs (timeline / record table) — keyed by the history `action` value. */
export const HISTORY_ACTION_ZH = {
  created: '发起',
  approve: '通过',
  reject: '驳回',
  transfer: '转交',
  revoke: '撤回',
  comment: '评论',
  return: '退回',
  sign: '签字',
  add_sign: '加签',
  reduce_sign: '减签',
  cc: '抄送',
  handle: '办理',
}

export const HISTORY_ACTION_EN: Record<keyof typeof HISTORY_ACTION_ZH, string> = {
  created: 'Submitted',
  approve: 'Approved',
  reject: 'Rejected',
  transfer: 'Transferred',
  revoke: 'Withdrawn',
  comment: 'Commented',
  return: 'Returned',
  sign: 'Signed',
  add_sign: 'Approvers added',
  reduce_sign: 'Approver removed',
  cc: 'CC',
  handle: 'Handled',
}

/** Approval modes (node aggregation) — keyed by `metadata.approvalMode`. */
export const APPROVAL_MODE_ZH = {
  single: '单人',
  all: '会签',
  any: '或签',
  threshold: '门槛会签',
  sequential: '依次审批',
}

export const APPROVAL_MODE_EN: Record<keyof typeof APPROVAL_MODE_ZH, string> = {
  single: 'Single approver',
  all: 'All must approve',
  any: 'Any one approves',
  threshold: 'Threshold approval',
  sequential: 'Sequential approval',
}
