// Label tables for the approval center surfaces — report item O-8, slice F8-1 (approval
// member-surface locale). Same convention as templateCenterLabels.ts / templateDetailLabels.ts
// (#5545): a flat `*_ZH` / `*_EN` object pair per component, `EN: Record<keyof typeof ZH, string>`
// so vue-tsc enforces key parity, consumed as `computed(() => (isZh.value ? ZH : EN))` from the
// module-scope `useLocale()` singleton.
//
// Copy with interpolated values (counts, titles) stays next to its use as an `isZh.value ? … : …`
// ternary in the view, the same split #5545 used. Two constructs in ApprovalCenterView.vue already
// followed the locale before this slice and are left as they are: `tabEmptyText` (#5545) and the
// CSV export copy `exportCopy` (F3-E1).

export const CENTER_ZH = {
  title: '审批中心',
  subtitle: '集中处理待办、跟进我发起的申请，并快速识别超时事项',
  statPending: '待办',
  statUnread: '未读',
  create: '发起审批',
  filtersLabel: '审批筛选',
  searchPlaceholder: '搜索标题或审批编号',
  sourcePlaceholder: '来源系统',
  sourceAll: '全部来源',
  sourcePlatform: '平台审批',
  sourcePlm: 'PLM 审批',
  filtersCollapse: '收起筛选',
  filtersExpand: '更多筛选',
  statusPlaceholder: '状态筛选',
  statusPending: '待处理',
  statusApproved: '已通过',
  statusRejected: '已驳回',
  statusRevoked: '已撤回',
  templatePlaceholder: '表单筛选',
  rangeSeparator: '至',
  rangeStartPlaceholder: '发起开始日期',
  rangeEndPlaceholder: '发起结束日期',
  clearFilters: '清空筛选',
  reload: '重新加载',
  tabPending: '待我处理',
  tabMine: '我发起的',
  tabCc: '抄送我的',
  tabCompleted: '已完成',
  tabProcessed: '我已处理',
  batchApprove: '批量通过',
  batchReject: '批量驳回',
  markAllRead: '全部标记已读',
  attendanceTitle: '考勤审批',
  attendanceBody: '补卡、请假、加班审批当前在考勤模块处理，不计入平台/PLM 待办列表。',
  attendanceOpen: '待处理考勤审批',
  confirm: '确认',
  cancel: '取消',
  approve: '通过',
  reject: '驳回',
  batchRejectTitle: '批量驳回',
  rejectReasonRequired: '驳回原因（必填）',
  rejectOpinionOptional: '驳回意见（选填）',
  confirmReject: '确认驳回',
  rowRejectTitle: '驳回审批',
  batchResultTitle: '批量处理结果',
  close: '关闭',
  retryFailed: '重试失败项',
  toastApproved: '审批已通过',
  toastRejected: '审批已驳回',
  actionFailedRetry: '操作失败，请重试',
  actionFailedRefresh: '操作失败，请刷新后重试',
  urgeSent: '已发送催办提醒',
  urgeTooFrequent: '催办过于频繁，请稍后再试',
  urgeFailed: '催办失败，请重试',
  markAllReadNone: '当前范围内无未读审批',
  markAllReadFailed: '标记已读失败，请重试',
}

export const CENTER_EN: Record<keyof typeof CENTER_ZH, string> = {
  title: 'Approval center',
  subtitle: 'Handle your to-dos, follow the requests you started, and spot overdue items quickly',
  statPending: 'To-do',
  statUnread: 'Unread',
  create: 'New request',
  filtersLabel: 'Approval filters',
  searchPlaceholder: 'Search by title or request number',
  sourcePlaceholder: 'Source',
  sourceAll: 'All sources',
  sourcePlatform: 'Platform approvals',
  sourcePlm: 'PLM approvals',
  filtersCollapse: 'Fewer filters',
  filtersExpand: 'More filters',
  statusPlaceholder: 'Status',
  statusPending: 'Pending',
  statusApproved: 'Approved',
  statusRejected: 'Rejected',
  statusRevoked: 'Revoked',
  templatePlaceholder: 'Form',
  rangeSeparator: 'to',
  rangeStartPlaceholder: 'Submitted from',
  rangeEndPlaceholder: 'Submitted until',
  clearFilters: 'Clear filters',
  reload: 'Reload',
  tabPending: 'Waiting for me',
  tabMine: 'Started by me',
  tabCc: 'CC’d to me',
  tabCompleted: 'Completed',
  tabProcessed: 'Processed by me',
  batchApprove: 'Approve selected',
  batchReject: 'Reject selected',
  markAllRead: 'Mark all as read',
  attendanceTitle: 'Attendance approvals',
  attendanceBody: 'Missed-punch, leave and overtime approvals are handled in the attendance module and are not counted in the platform / PLM to-do list.',
  attendanceOpen: 'Pending attendance approvals',
  confirm: 'Confirm',
  cancel: 'Cancel',
  approve: 'Approve',
  reject: 'Reject',
  batchRejectTitle: 'Reject selected',
  rejectReasonRequired: 'Reason for rejection (required)',
  rejectOpinionOptional: 'Rejection note (optional)',
  confirmReject: 'Confirm rejection',
  rowRejectTitle: 'Reject approval',
  batchResultTitle: 'Batch results',
  close: 'Close',
  retryFailed: 'Retry failed items',
  toastApproved: 'Approved',
  toastRejected: 'Rejected',
  actionFailedRetry: 'The action failed. Please try again.',
  actionFailedRefresh: 'The action failed. Please refresh and try again.',
  urgeSent: 'Reminder sent',
  urgeTooFrequent: 'Too many reminders. Please try again later.',
  urgeFailed: 'The reminder failed. Please try again.',
  markAllReadNone: 'No unread approvals in the current scope',
  markAllReadFailed: 'Could not mark as read. Please try again.',
}

export const CENTER_TABLE_ZH = {
  colRequestNo: '审批编号',
  colTitle: '标题',
  colRequester: '发起人',
  colStatus: '状态',
  colCreatedAt: '发起时间',
  colWaiting: '已等待',
  colActions: '操作',
}

export const CENTER_TABLE_EN: Record<keyof typeof CENTER_TABLE_ZH, string> = {
  colRequestNo: 'Request no.',
  colTitle: 'Title',
  colRequester: 'Requester',
  colStatus: 'Status',
  colCreatedAt: 'Submitted',
  colWaiting: 'Waiting',
  colActions: 'Actions',
}

export const CENTER_PANE_ZH = {
  paneLabel: '审批详情',
  closeLabel: '关闭详情面板',
  nodeLabel: '当前节点与待处理人',
  loading: '加载中…',
  confirm: '确认',
  cancel: '取消',
  approve: '通过',
  reject: '驳回',
  openFull: '打开完整详情',
}

export const CENTER_PANE_EN: Record<keyof typeof CENTER_PANE_ZH, string> = {
  paneLabel: 'Approval details',
  closeLabel: 'Close the details panel',
  nodeLabel: 'Current node and pending approvers',
  loading: 'Loading…',
  confirm: 'Confirm',
  cancel: 'Cancel',
  approve: 'Approve',
  reject: 'Reject',
  openFull: 'Open full details',
}
