// Label table for MyDelegationView — report item O-8, slice F8-1 (approval member-surface locale).
// Same convention as templateCenterLabels.ts / templateDetailLabels.ts (#5545): a flat `MY_ZH` /
// `MY_EN` pair (`EN: Record<keyof typeof ZH, string>` so vue-tsc enforces key parity), consumed as
// `computed(() => (isZh.value ? MY_ZH : MY_EN))` from the module-scope `useLocale()` singleton.
// The admin delegation page (DelegationSettingsView.vue) is slice F8-2 and does not use this table.

export const MY_ZH = {
  title: '我的委托',
  subtitle: '设置或取消你自己的审批委托（委托人恒为你本人）。同一范围目标仅允许一条生效委托。',
  create: '新建委托',
  empty: '暂无委托',
  colDelegatee: '被委托人',
  colScope: '范围',
  colWindow: '时间窗',
  colStatus: '状态',
  expiringSoon: '即将到期',
  colRouted: '已路由审批',
  routedTitle: '经你的委托路由的审批数（按委托人聚合，含历史窗口）',
  colActions: '操作',
  disable: '停用',
  dialogTitle: '新建我的委托',
  scopeAll: '全部审批',
  scopeTemplate: '指定表单',
  formLabel: '表单',
  templateIdPlaceholder: '审批表单 ID',
  startAt: '开始时间',
  endAt: '结束时间',
  cancel: '取消',
  save: '保存',
  unknownUser: '未知用户',
  loadFailed: '加载委托失败',
  created: '委托已创建',
  createFailed: '创建委托失败',
  disableConfirm: '停用后该委托立即失效，进行中的转交不受影响。确定停用吗？',
  disableConfirmTitle: '停用委托',
  disableFailed: '停用委托失败',
}

export const MY_EN: Record<keyof typeof MY_ZH, string> = {
  title: 'My delegations',
  subtitle: 'Set up or cancel your own approval delegations (you are always the delegator). Only one active delegation is allowed per scope.',
  create: 'New delegation',
  empty: 'No delegations',
  colDelegatee: 'Delegate',
  colScope: 'Scope',
  colWindow: 'Time window',
  colStatus: 'Status',
  expiringSoon: 'Expiring soon',
  colRouted: 'Routed approvals',
  routedTitle: 'Approvals routed through your delegations (aggregated by delegator, including past windows)',
  colActions: 'Actions',
  disable: 'Disable',
  dialogTitle: 'New delegation',
  scopeAll: 'All approvals',
  scopeTemplate: 'A single form',
  formLabel: 'Form',
  templateIdPlaceholder: 'Approval form ID',
  startAt: 'Start time',
  endAt: 'End time',
  cancel: 'Cancel',
  save: 'Save',
  unknownUser: 'Unknown user',
  loadFailed: 'Failed to load delegations',
  created: 'Delegation created',
  createFailed: 'Failed to create the delegation',
  disableConfirm: 'The delegation stops immediately; transfers already in progress are not affected. Disable it?',
  disableConfirmTitle: 'Disable delegation',
  disableFailed: 'Failed to disable the delegation',
}
