/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/approvals/{id}": {
    /** Get approval instance */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
        /** @description Not found */
        404: {
          content: never;
        };
      };
    };
  };
  "/api/approvals/{id}/approve": {
    /** Approve instance with optimistic locking */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            version: number;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** @example true */
              ok?: boolean;
              data?: {
                /** @example demo-1 */
                id?: string;
                /** @example APPROVED */
                status?: string;
                /** @example 1 */
                version?: number;
                /** @example 0 */
                prevVersion?: number;
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        /** @description Version conflict */
        409: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/approvals/{id}/reject": {
    /** Reject instance with optimistic locking */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            version: number;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** @example true */
              ok?: boolean;
              data?: {
                /** @example demo-1 */
                id?: string;
                /** @example REJECTED */
                status?: string;
                /** @example 2 */
                version?: number;
                /** @example 1 */
                prevVersion?: number;
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        409: components["responses"]["ValidationError"];
      };
    };
  };
  "/api/approvals/{id}/return": {
    /** Return instance with optimistic locking */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            version: number;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** @example true */
              ok?: boolean;
              data?: {
                /** @example demo-1 */
                id?: string;
                /** @example RETURNED */
                status?: string;
                /** @example 3 */
                version?: number;
                /** @example 2 */
                prevVersion?: number;
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        409: components["responses"]["ValidationError"];
      };
    };
  };
  "/api/approvals/{id}/revoke": {
    /** Revoke instance with optimistic locking */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            version: number;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** @example true */
              ok?: boolean;
              data?: {
                /** @example demo-1 */
                id?: string;
                /** @example REVOKED */
                status?: string;
                /** @example 4 */
                version?: number;
                /** @example 3 */
                prevVersion?: number;
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        409: components["responses"]["ValidationError"];
      };
    };
  };
  "/api/approvals/{id}/history": {
    /** Get approval history (from approval_records) */
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Pagination"];
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        503: components["responses"]["ServiceUnavailable"];
      };
    };
  };
  "/api/attendance/punch": {
    /** Punch attendance (check in/out) */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** @enum {string} */
            eventType: "check_in" | "check_out";
            /** Format: date-time */
            occurredAt?: string;
            timezone?: string;
            source?: string;
            location?: Record<string, never>;
            meta?: Record<string, never>;
            orgId?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: {
                event?: components["schemas"]["AttendanceEvent"];
                record?: components["schemas"]["AttendanceRecord"];
              };
            };
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/api/attendance/records": {
    /** List attendance records */
    get: {
      parameters: {
        query?: {
          userId?: string;
          orgId?: string;
          from?: string;
          to?: string;
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: {
                items?: components["schemas"]["AttendanceRecord"][];
                total?: number;
                page?: number;
                pageSize?: number;
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/api/attendance/summary": {
    /** Attendance summary */
    get: {
      parameters: {
        query?: {
          userId?: string;
          orgId?: string;
          from?: string;
          to?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: components["schemas"]["AttendanceSummary"];
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/api/attendance/requests": {
    /** List attendance requests */
    get: {
      parameters: {
        query?: {
          userId?: string;
          orgId?: string;
          status?: string;
          from?: string;
          to?: string;
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: {
                items?: components["schemas"]["AttendanceRequest"][];
                total?: number;
                page?: number;
                pageSize?: number;
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    /** Create attendance adjustment request */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: date */
            workDate: string;
            /** @enum {string} */
            requestType: "missed_check_in" | "missed_check_out" | "time_correction";
            /** Format: date-time */
            requestedInAt?: string;
            /** Format: date-time */
            requestedOutAt?: string;
            reason?: string;
            orgId?: string;
          };
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: {
                request?: components["schemas"]["AttendanceRequest"];
              };
            };
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/api/attendance/requests/{id}/approve": {
    /** Approve attendance request */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            comment?: string;
            metadata?: Record<string, never>;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: {
                requestId?: string;
                status?: string;
                orgId?: string;
                userId?: string;
                record?: components["schemas"]["AttendanceRecord"];
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/api/attendance/requests/{id}/reject": {
    /** Reject attendance request */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            comment?: string;
            metadata?: Record<string, never>;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: {
                requestId?: string;
                status?: string;
                orgId?: string;
                userId?: string;
                record?: components["schemas"]["AttendanceRecord"] | null;
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/api/attendance/rules/default": {
    /** Get default attendance rule */
    get: {
      parameters: {
        query?: {
          orgId?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: components["schemas"]["AttendanceRule"];
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    /** Update default attendance rule */
    put: {
      requestBody: {
        content: {
          "application/json": {
            name?: string;
            timezone?: string;
            workStartTime?: string;
            workEndTime?: string;
            lateGraceMinutes?: number;
            earlyGraceMinutes?: number;
            roundingMinutes?: number;
            workingDays?: number[];
            orgId?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: components["schemas"]["AttendanceRule"];
            };
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/api/attendance/shifts": {
    /** List attendance shifts */
    get: {
      parameters: {
        query?: {
          orgId?: string;
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: {
                items?: components["schemas"]["AttendanceShift"][];
                total?: number;
                page?: number;
                pageSize?: number;
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    /** Create attendance shift */
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            timezone?: string;
            workStartTime?: string;
            workEndTime?: string;
            lateGraceMinutes?: number;
            earlyGraceMinutes?: number;
            roundingMinutes?: number;
            workingDays?: number[];
            orgId?: string;
          };
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: components["schemas"]["AttendanceShift"];
            };
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/api/attendance/shifts/{id}": {
    /** Update attendance shift */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            name?: string;
            timezone?: string;
            workStartTime?: string;
            workEndTime?: string;
            lateGraceMinutes?: number;
            earlyGraceMinutes?: number;
            roundingMinutes?: number;
            workingDays?: number[];
            orgId?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: components["schemas"]["AttendanceShift"];
            };
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    /** Delete attendance shift */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: {
                id?: string;
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/api/attendance/assignments": {
    /** List attendance shift assignments */
    get: {
      parameters: {
        query?: {
          orgId?: string;
          userId?: string;
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: {
                items?: {
                    assignment?: components["schemas"]["AttendanceShiftAssignment"];
                    shift?: components["schemas"]["AttendanceShift"];
                  }[];
                total?: number;
                page?: number;
                pageSize?: number;
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    /** Create attendance shift assignment */
    post: {
      requestBody: {
        content: {
          "application/json": {
            userId: string;
            shiftId: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate?: string | null;
            isActive?: boolean;
            orgId?: string;
          };
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: {
                assignment?: components["schemas"]["AttendanceShiftAssignment"];
                shift?: components["schemas"]["AttendanceShift"];
              };
            };
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/api/attendance/assignments/{id}": {
    /** Update attendance shift assignment */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            userId?: string;
            shiftId?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string | null;
            isActive?: boolean;
            orgId?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: {
                assignment?: components["schemas"]["AttendanceShiftAssignment"];
                shift?: components["schemas"]["AttendanceShift"];
              };
            };
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    /** Delete attendance shift assignment */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: {
                id?: string;
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/api/attendance/holidays": {
    /** List attendance holidays */
    get: {
      parameters: {
        query?: {
          orgId?: string;
          from?: string;
          to?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: {
                items?: components["schemas"]["AttendanceHoliday"][];
                total?: number;
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    /** Create attendance holiday */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: date */
            date: string;
            name?: string | null;
            isWorkingDay?: boolean;
            orgId?: string;
          };
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: components["schemas"]["AttendanceHoliday"];
            };
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/api/attendance/holidays/{id}": {
    /** Update attendance holiday */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: date */
            date?: string;
            name?: string | null;
            isWorkingDay?: boolean;
            orgId?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: components["schemas"]["AttendanceHoliday"];
            };
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    /** Delete attendance holiday */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: {
                id?: string;
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/api/attendance/settings": {
    /** Get attendance settings */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: components["schemas"]["AttendanceSettings"];
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    /** Update attendance settings */
    put: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["AttendanceSettings"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              ok?: boolean;
              data?: components["schemas"]["AttendanceSettings"];
            };
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/api/attendance/export": {
    /** Export attendance records as CSV */
    get: {
      parameters: {
        query?: {
          userId?: string;
          orgId?: string;
          from?: string;
          to?: string;
          limit?: number;
        };
      };
      responses: {
        /** @description CSV export */
        200: {
          content: {
            "text/csv": string;
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/api/audit-logs": {
    /** Admin-only audit log query */
    get: {
      parameters: {
        query?: {
          actorId?: string;
          resourceType?: string;
          resourceId?: string;
          action?: string;
          from?: string;
          to?: string;
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
        /** @description Forbidden */
        403: {
          content: never;
        };
      };
    };
  };
  "/api/spreadsheets/{id}/permissions": {
    /** List spreadsheet permissions */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** @example true */
              ok?: boolean;
              data?: {
                items?: {
                    userId?: string;
                    permissions?: string[];
                  }[];
              };
            };
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
  };
  "/api/spreadsheets/{id}/permissions/grant": {
    /** Grant spreadsheet permission */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            userId: string;
            permission: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
  };
  "/api/spreadsheets/{id}/permissions/revoke": {
    /** Revoke spreadsheet permission */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            userId: string;
            permission: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
  };
  "/api/spreadsheets": {
    /** List spreadsheets */
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** @example true */
              ok?: boolean;
              data?: {
                items?: components["schemas"]["Spreadsheet"][];
                page?: number;
                pageSize?: number;
                total?: number;
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
    /** Create spreadsheet */
    post: {
      requestBody: {
        content: {
          "application/json": {
            id?: string;
            name: string;
            owner_id?: string;
            ownerId?: string;
            workspace_id?: string;
            initial_sheets?: {
                id?: string;
                name: string;
              }[];
          };
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": {
              /** @example true */
              ok?: boolean;
              data?: {
                spreadsheet?: components["schemas"]["Spreadsheet"];
                sheets?: components["schemas"]["Sheet"][];
              };
            };
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
  "/api/spreadsheets/{id}": {
    /** Get spreadsheet */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** @example true */
              ok?: boolean;
              data?: components["schemas"]["Spreadsheet"] & {
                sheets?: components["schemas"]["Sheet"][];
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    /** Update spreadsheet */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            name?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** @example true */
              ok?: boolean;
              data?: components["schemas"]["Spreadsheet"];
            };
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    /** Delete spreadsheet */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** @example true */
              ok?: boolean;
              data?: {
                id?: string;
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
  };
  "/api/spreadsheets/{id}/sheets/{sheetId}": {
    /** Update sheet metadata */
    put: {
      parameters: {
        path: {
          id: string;
          sheetId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            row_count?: number;
            rowCount?: number;
            column_count?: number;
            columnCount?: number;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** @example true */
              ok?: boolean;
              data?: components["schemas"]["Sheet"];
            };
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
  };
  "/api/spreadsheets/{id}/sheets/{sheetId}/cells": {
    /** Get spreadsheet cells */
    get: {
      parameters: {
        path: {
          id: string;
          sheetId: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** @example true */
              ok?: boolean;
              data?: {
                sheet?: components["schemas"]["Sheet"];
                cells?: components["schemas"]["Cell"][];
              };
            };
          };
        };
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    /** Update spreadsheet cells */
    put: {
      parameters: {
        path: {
          id: string;
          sheetId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            cells: {
                row: number;
                col: number;
                value?: unknown;
                formula?: string;
                dataType?: string;
                data_type?: string;
              }[];
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** @example true */
              ok?: boolean;
              data?: {
                cells?: components["schemas"]["Cell"][];
              };
            };
          };
        };
        400: components["responses"]["ValidationError"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    StandardResponse: {
      ok?: boolean;
      data?: unknown;
    };
    ErrorResponse: {
      /** @default false */
      ok?: boolean;
      error?: {
        code?: string;
        message?: string;
      };
    };
    AttendanceEvent: {
      id?: string;
      user_id?: string;
      org_id?: string;
      /** Format: date */
      work_date?: string;
      /** Format: date-time */
      occurred_at?: string;
      /** @enum {string} */
      event_type?: "check_in" | "check_out" | "adjustment";
      source?: string;
      timezone?: string;
      location?: Record<string, never>;
      meta?: Record<string, never>;
      /** Format: date-time */
      created_at?: string;
    };
    AttendanceRecord: {
      id?: string;
      user_id?: string;
      org_id?: string;
      /** Format: date */
      work_date?: string;
      timezone?: string;
      /** Format: date-time */
      first_in_at?: string | null;
      /** Format: date-time */
      last_out_at?: string | null;
      work_minutes?: number;
      late_minutes?: number;
      early_leave_minutes?: number;
      status?: string;
      is_workday?: boolean;
      meta?: Record<string, never>;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    AttendanceRequest: {
      id?: string;
      user_id?: string;
      org_id?: string;
      /** Format: date */
      work_date?: string;
      /** @enum {string} */
      request_type?: "missed_check_in" | "missed_check_out" | "time_correction";
      /** Format: date-time */
      requested_in_at?: string | null;
      /** Format: date-time */
      requested_out_at?: string | null;
      reason?: string | null;
      /** @enum {string} */
      status?: "pending" | "approved" | "rejected" | "cancelled";
      approval_instance_id?: string | null;
      resolved_by?: string | null;
      /** Format: date-time */
      resolved_at?: string | null;
      metadata?: Record<string, never>;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    AttendanceSummary: {
      total_days?: number;
      total_minutes?: number;
      normal_days?: number;
      late_days?: number;
      early_leave_days?: number;
      late_early_days?: number;
      partial_days?: number;
      absent_days?: number;
      adjusted_days?: number;
      off_days?: number;
    };
    AttendanceRule: {
      id?: string;
      orgId?: string;
      name?: string;
      timezone?: string;
      workStartTime?: string;
      workEndTime?: string;
      lateGraceMinutes?: number;
      earlyGraceMinutes?: number;
      roundingMinutes?: number;
      workingDays?: number[];
      isDefault?: boolean;
    };
    AttendanceShift: {
      id?: string;
      orgId?: string;
      name?: string;
      timezone?: string;
      workStartTime?: string;
      workEndTime?: string;
      lateGraceMinutes?: number;
      earlyGraceMinutes?: number;
      roundingMinutes?: number;
      workingDays?: number[];
    };
    AttendanceShiftAssignment: {
      id?: string;
      orgId?: string;
      userId?: string;
      shiftId?: string;
      /** Format: date */
      startDate?: string;
      /** Format: date */
      endDate?: string | null;
      isActive?: boolean;
    };
    AttendanceHoliday: {
      id?: string;
      orgId?: string;
      /** Format: date */
      date?: string;
      name?: string | null;
      isWorkingDay?: boolean;
    };
    AttendanceSettings: {
      autoAbsence?: {
        enabled?: boolean;
        runAt?: string;
        lookbackDays?: number;
      };
      ipAllowlist?: string[];
      geoFence?: {
        lat?: number;
        lng?: number;
        radiusMeters?: number;
      } | null;
      minPunchIntervalMinutes?: number;
    };
    Spreadsheet: {
      id?: string;
      name?: string;
      owner_id?: string | null;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
      /** Format: date-time */
      deleted_at?: string | null;
    };
    Sheet: {
      id?: string;
      spreadsheet_id?: string;
      name?: string;
      order_index?: number;
      row_count?: number;
      column_count?: number;
      frozen_rows?: number | null;
      frozen_columns?: number | null;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    Cell: {
      id?: string;
      sheet_id?: string;
      row_index?: number;
      column_index?: number;
      value?: unknown;
      data_type?: string | null;
      formula?: string | null;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
  };
  responses: {
    /** @description Unauthorized - Missing or invalid JWT token */
    Unauthorized: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Forbidden - Insufficient permissions */
    Forbidden: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Validation error - Invalid request data */
    ValidationError: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Not found - Resource does not exist */
    NotFound: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Service unavailable - Temporary server issues */
    ServiceUnavailable: {
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    Pagination: {
      content: never;
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
