const { DEFAULT_TEMPLATES } = require('./template-library.cjs')

module.exports = {
  mapping: {
    source: 'DingTalkDailyReport',
    dateField: 'date',
    columns: {
      should_attendance_days: 14888275,
      attendance_class: 14888276,
      attendance_days: 14888277,
      attendance_rest_days: 14888278,
      attendance_work_time: 14888279,
      late_times: 14888280,
      late_minute: 14888281,
      serious_late_times: 14888282,
      serious_late_minute: 14888283,
      absenteeism_late_times: 14888284,
      leave_early_times: 14888285,
      leave_early_minute: 14888286,
      on_work_lack_card_times: 14888287,
      off_work_lack_card_times: 14888288,
      absenteeism_days: 14888289,
      business_trip_time: 14888290,
      out_time: 14888291,
      overtime_approve_count: 14888293,
      overtime_workday: 14888294,
      overtime_restday: 14888295,
      overtime_holiday: 14888296,
      attend_result: 14888297,
      plan_detail: 14888298,
      clock_in_1: 14888299,
      clock_in_1_result: 14888300,
      clock_out_1: 14888301,
      clock_out_1_result: 14888302,
      clock_in_2: 14888303,
      clock_in_2_result: 14888304,
      clock_out_2: 14888305,
      clock_out_2_result: 14888306,
      clock_in_3: 14888307,
      clock_in_3_result: 14888308,
      clock_out_3: 14888309,
      clock_out_3_result: 14888310,
      attendance_approve: 14888311,
      overtime_duration: 50279717,
      fee_overtime_workday: 50279718,
      fee_overtime_restday: 50279719,
      fee_overtime_holiday: 50279720,
      rest_overtime_workday: 50279721,
      rest_overtime_restday: 50279722,
      rest_overtime_holiday: 50279723,
      making_up_lack_times: 186349600,
      actual_attendance_test: 1371065864,
      late_test: 1379151352,
    },
    extraFields: {
      attendance_group: 'profile.attendanceGroup',
      role_tags: 'profile.roleTags',
      department: 'profile.department',
      entry_time: 'profile.entryTime',
      resign_time: 'profile.resignTime',
      exception_reason: 'calc.exceptionReason',
      leave_hours: 'calc.leaveHours',
    },
  },
  coreRules: {
    overtime: {
      merge_overlaps: true,
      deduct_step_hours: 0.5,
    },
    overnight: {
      detect_cross_day: true,
      next_day_policy: 'set_actual_0_or_floor',
    },
    leave: {
      warn_if_leave_but_all_punches: true,
      warn_if_actual_plus_leave_less_than_required: true,
    },
  },
  templates: DEFAULT_TEMPLATES,
    },
    {
      name: '通用提醒',
      category: 'system',
      editable: false,
      rules: [
        {
          id: 'overtime_approval_no_punch_warning',
          when: { approval_contains: '加班', has_punch: false },
          then: { warning: '有加班单但未打卡' },
        },
        {
          id: 'trip_and_overtime_warning',
          when: { exceptionReason_contains: '出差', overtime_hours_gt: 0 },
          then: { warning: '出差同时存在加班工时，请核对' },
        },
        {
          id: 'trip_low_hours_warning',
          when: {
            exceptionReason_contains: '出差',
            shift_not_contains: '休息',
            actual_hours_lt: 8,
            department_not_contains: ['国内销售', '服务测试部-调试'],
          },
          then: { warning: '出差当天实际工时不足8小时，请核对' },
        },
        {
          id: 'leave_makeup_missing_punch_warning',
          when: { exceptionReason_contains: ['缺卡', '补卡'], clockIn2_exists: false },
          then: { warning: '缺卡且补卡，但未找到上班2打卡，请核对' },
        },
        {
          id: 'trip_and_leave_conflict_warning',
          when: { exceptionReason_contains: ['出差', '事假'] },
          then: { warning: '出差+事假请核对' },
        },
        {
          id: 'trip_and_sick_conflict_warning',
          when: { exceptionReason_contains: ['出差', '病假'] },
          then: { warning: '出差+病假请核对' },
        },
        {
          id: 'trip_and_injury_conflict_warning',
          when: { exceptionReason_contains: ['出差', '工伤假'] },
          then: { warning: '出差+工伤假请核对' },
        },
      ],
    },
    {
      name: '角色规则',
      category: 'system',
      editable: false,
      scope: { role_tags: ['security', 'driver'] },
      rules: [
        {
          id: 'security_base_hours',
          when: { role: 'security' },
          then: { required_hours: 8 },
        },
        {
          id: 'security_holiday_overtime',
          when: { role: 'security', is_holiday: true, has_punch: true },
          then: { overtime_hours: 8, reason: '保安节假日算加班' },
        },
        {
          id: 'driver_rest_punch_overtime',
          when: { role: 'driver', shift: '休息', clockIn1_exists: true },
          then: { overtime_hours: 8, reason: '司机休息日打卡算加班' },
        },
      ],
    },
    {
      name: '部门提醒',
      category: 'system',
      editable: false,
      scope: { department: ['国内销售', '服务测试部-调试'] },
      rules: [
        {
          id: 'trip_and_leave_warning',
          when: { exceptionReason_contains: ['出差', '事假'] },
          then: { warning: '出差+事假请核对' },
        },
        {
          id: 'trip_and_sick_warning',
          when: { exceptionReason_contains: ['出差', '病假'] },
          then: { warning: '出差+病假请核对' },
        },
        {
          id: 'trip_and_injury_warning',
          when: { exceptionReason_contains: ['出差', '工伤假'] },
          then: { warning: '出差+工伤假请核对' },
        },
      ],
    },
    {
      name: '用户自定义',
      category: 'custom',
      editable: true,
      description: '为考勤管理员预留的自定义规则模板',
      rules: [],
    },
  ],
}
