#!/bin/bash
# scripts/cleanup-test-branches.sh
# Purpose: 批量清理测试和验证分支
# Author: DevOps Team
# Date: 2025-09-30

set -e

echo "=== 测试分支清理工具 ==="
echo ""

# 1. 列出所有test/verify分支
echo "📋 扫描测试分支..."
TEST_BRANCHES=$(git branch -r | grep -E "origin/(test|verify)-" | sed 's/origin\///' | sed 's/^[[:space:]]*//')

if [ -z "$TEST_BRANCHES" ]; then
  echo "✅ 未发现测试分支，无需清理"
  exit 0
fi

echo ""
echo "发现以下测试分支:"
echo "$TEST_BRANCHES" | nl
echo ""

# 2. 询问确认
read -p "是否继续清理这些分支? [y/N] " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  echo "已取消清理"
  exit 0
fi

# 3. 归档报告到docs/archived-test-reports/
echo ""
echo "📦 归档测试报告..."
mkdir -p docs/archived-test-reports

ARCHIVED_COUNT=0
for branch in $TEST_BRANCHES; do
  echo "  归档 $branch..."

  # 获取PR信息
  PR_INFO=$(gh pr list --head "$branch" --json number,title,body,state --jq '.[0]' 2>/dev/null || echo "{}")

  if [ "$PR_INFO" != "{}" ]; then
    PR_NUM=$(echo "$PR_INFO" | jq -r '.number // "unknown"')
    PR_TITLE=$(echo "$PR_INFO" | jq -r '.title // "Unknown Title"')
    PR_BODY=$(echo "$PR_INFO" | jq -r '.body // "No description"')
    PR_STATE=$(echo "$PR_INFO" | jq -r '.state // "unknown"')

    # 生成归档文件
    ARCHIVE_FILE="docs/archived-test-reports/${branch/\//_}.md"
    cat > "$ARCHIVE_FILE" <<EOF
# 测试分支归档: $branch

**PR编号**: #$PR_NUM
**标题**: $PR_TITLE
**状态**: $PR_STATE
**归档日期**: $(date +%Y-%m-%d)

## 原始描述

$PR_BODY

---

*此文件由 scripts/cleanup-test-branches.sh 自动生成*
EOF

    ARCHIVED_COUNT=$((ARCHIVED_COUNT + 1))
  else
    echo "  ⚠️  未找到PR信息（可能已关闭或不存在PR）"
  fi
done

echo "  ✅ 归档完成: $ARCHIVED_COUNT 个报告"

# 4. 关闭PR并删除分支
echo ""
echo "🗑️  关闭PR并删除分支..."
DELETED_COUNT=0
CLOSED_PR_COUNT=0

for branch in $TEST_BRANCHES; do
  # 获取PR编号
  PR_NUM=$(gh pr list --head "$branch" --json number --jq '.[0].number' 2>/dev/null || echo "")

  if [ -n "$PR_NUM" ]; then
    echo "  关闭 PR #$PR_NUM ($branch)..."
    gh pr close "$PR_NUM" --comment "✅ 测试已完成，功能已合并到main分支

归档报告已保存至: \`docs/archived-test-reports/${branch/\//_}.md\`

---
*由 scripts/cleanup-test-branches.sh 自动关闭*" 2>/dev/null || echo "  ⚠️  PR已关闭或无法访问"
    CLOSED_PR_COUNT=$((CLOSED_PR_COUNT + 1))
  fi

  # 删除远程分支
  echo "  删除远程分支 $branch..."
  git push origin --delete "$branch" 2>/dev/null || echo "  ⚠️  分支已删除或不存在"
  DELETED_COUNT=$((DELETED_COUNT + 1))
done

echo ""
echo "=== 清理完成 ==="
echo "  📦 归档报告: $ARCHIVED_COUNT 个"
echo "  🔒 关闭PR: $CLOSED_PR_COUNT 个"
echo "  🗑️  删除分支: $DELETED_COUNT 个"
echo ""
echo "归档报告保存在: docs/archived-test-reports/"
echo ""

# 5. 提交归档报告到git
if [ $ARCHIVED_COUNT -gt 0 ]; then
  echo "📝 提交归档报告..."
  git add docs/archived-test-reports/
  git commit -m "chore: archive test branch reports

Archived $ARCHIVED_COUNT test branch reports before cleanup.

Branches cleaned:
$(echo "$TEST_BRANCHES" | sed 's/^/- /')

🤖 Generated by scripts/cleanup-test-branches.sh
"
  echo "  ✅ 归档报告已提交到git"
fi

echo ""
echo "✨ 全部完成！"
