// Fixture standing in for packages/core-backend/src/db/migration-provider.ts. Deliberately
// missing the design-doc pointer comment (drift check D), missing 049_create_bpmn_workflow_tables
// (expected-overlap check), and carrying an extra undocumented overlap item (check C).
const SUPERSEDED_LEGACY_SQL_MIGRATIONS = [
  '032_create_approval_records',
  '033_create_rbac_core',
  '034_create_spreadsheets',
  '035_create_files',
  '036_create_spreadsheet_permissions',
  '037_add_gallery_form_support',
  '038_config_and_secrets',
  '040_data_sources',
  '041_script_sandbox',
  '042_core_model_completion',
  '042a_core_model_views',
  '042b_external_data_model',
  '042c_audit_placeholder',
  '042d_audit_and_cache',
  '042d_plugins_and_templates',
  '043_core_model_views',
  '044_external_data_model',
  '045_audit_placeholder',
  '046_plugins_and_templates',
  '047_audit_and_cache',
  '047_create_event_bus_tables',
  '048_create_event_bus_tables',
  '050_create_snapshot_core',
  '051_create_minimal_views',
  '052_recreate_minimal_views',
  '053_create_protection_rules',
  '054_create_users_table',
  '055_create_attendance_import_tokens',
  '20250926_create_audit_tables',
  '999_bogus_undocumented_migration',
]
